### ISSUE TITLE
The output of json archive using std::stringstream as Output will miss the last "}" 

### ISSUE THREAD

**Issue by shwangdev** [USCiLab/cereal#101]
The output of json archive using std::stringstream as Output will miss the last "}"

**Comment by AndyDentFree** [comment]
I think this bit of documentation could be a little bit **LOUDER AND MORE OBVIOUS** because I just wasted half an hour proving it wasn't strange about the setup, before I found this issue.

**Comment by randvoorhies** [comment]
Yeah, documentation is hard.  Fortunately, it is open source. We welcome any specific suggestions (or pull requests!) to help make it better.  Check out the gh-pages branch to see where we keep all of the docs.

**Comment by lucklove** [comment]
got it!
