### ISSUE TITLE
VS2013 problem when polymorphic serialization classes exist in a library

### ISSUE THREAD

**Issue by runarundheim** [USCiLab/cereal#107]
I created a test with two polymorphic classes. If the classes and the write code exist in the same project everything works nice. If I try to split up the polymorphic classes in a library and link this library into the project where the serialization is performed then the code fail.
The CEREAL_REGISTER_TYPE doesn't seem to register when the class is registered in a library.
I also get this warning:

warning C4505: 'cereal::detail::polymorphic_serialization_supportcereal::BinaryInputArchive,T::instantiate' : unreferenced local function has been removed

Is there a way to force this code so that it is not removed when the library is created?

**Comment by robiwano** [comment]
I'm using v1.1.2, but there are no CEREAL_REGISTER_SHARED_LIBRARY  etc. in polymorphic.hpp ?? Please advise.
