### ISSUE TITLE
Roadmap for Cereal?

### ISSUE THREAD

**Issue by patlecat** [USCiLab/cereal#133]
Hi,
How about giving us an idea what will be done in what time spans? I see that some milestones have been created recently and features moved around. But when can we expect the new releases? :dancers:

**Comment by patlecat** [comment]
Just asking, you have a number of pull requests but you don't accept them. How can people help you if you don't allow them to? Is anything moving in this project or will it just slowly die?

**Comment by AzothAmmo** [comment]
There are numerous changes to cereal happening [all the time](https://github.com/USCiLab/cereal/commits/develop) on the develop branch.  Most of the pull requests are slated to be included in future versions of cereal.  It is very rare that we can blindly accept a pull request.  There have been at least two accepted in the past two weeks.

We have to balance making changes with making releases.  We've had two bugs that have been blocking 1.1 for a long time that finally have solutions, so it will actually be released soon™.
