### ISSUE TITLE
rapidjson internal assertion failure when using a locale that uses "," as decimal seperator

### ISSUE THREAD

**Issue by nebw** [USCiLab/cereal#144]
Cereal uses an old version of rapidjson which may use "," as a decimal seperator (see https://github.com/miloyip/rapidjson/issues/72). This was fixed in the rapidjson commit https://github.com/miloyip/rapidjson/commit/adb3974e4d078e253a31f4e9e034583bf41298d8 .

Is it possible to update to a newer rapidjson version or to merge the specific changes in the mentioned commit?

**Comment by AzothAmmo** [comment]
Added a new branch for updating rapidjson: https://github.com/USCiLab/cereal/tree/new_rapidjson, see 1934a3217ccd9b400293762c978cd59ca7cad907
