### ISSUE TITLE
MSVC Warning Level 4 Compliance

### ISSUE THREAD

**Issue by AzothAmmo** [USCiLab/cereal#151]
Apparently we don't play well with W4 on MSVC (see https://groups.google.com/forum/#!topic/cerealcpp/OyytjIUp1eM).

**Comment by javenPHD** [comment]
Thank you for bringing this here. Guess that I was missing the issues part of GitHub in my brain.

**Comment by javenPHD** [comment]
Warning	1	warning C4512: 'cereal::OutputArchive<cereal::XMLOutputArchive,0>' : assignment operator could not be generated	

Not sure if this is an enhancement, seems to be more of a bug.  meh

**Comment by javenPHD** [comment]
Hi there

Wondering if any progress has been had in this direction. 

An example of this error I was seeing below


Warning	11	warning C4512: 'cereal::NameValuePair<Function::ExponentialFunction &>' : assignment operator could not be generated	t:\personalsandbox\javen\third party\cereal-1.0.0\include\cereal\details\helpers.hpp

and 
Warning	2	warning C4512: 'cereal::InputArchive<cereal::XMLInputArchive,0>' : assignment operator could not be generated	t:\personalsandbox\javen\third party\cereal-1.0.0\include\cereal\cereal.hpp

**Comment by javenPHD** [comment]
finished the upgrade to 1.1 today. Notice that some additional warnings are appearing at level 4 for me. 

numerous of these in genericstream

Warning	70	warning C4127: conditional expression is constant	T:\PersonalSandBox\jAven\Third Party\cerealSerialization\cereal\external\rapidjson\genericstream.h	81	1

level 3 warning

Warning	114	warning C4244: '=' : conversion from 'uint32_t' to 'uint8_t', possible loss of data	T:\PersonalSandBox\jAven\Third Party\cerealSerialization\cereal\archives\xml.hpp	519	1

**Comment by AzothAmmo** [comment]
No progress has been made other than my initial look at this.  May have some time this week though.  From what I remember there are a lot of warnings that are caused by RapidJSON/RapidXML which I don't really want to fix - I guess for those we'll just use pragmas to ignore them.  Most of the other issues looked to be easy changes though.

**Comment by javenPHD** [comment]
Yes Shane. Saw those. Not using json so disabled the included in json
stuff. But do see it with xml and binary. Seemed like it was easy. I have
pragmaed them at this time. Ty

**Comment by AzothAmmo** [comment]
Give the latest develop a try and let me know how it is, I'll be pushing this out and any other quick fixes into 1.1.1.

**Comment by AzothAmmo** [comment]
Closing this - if you notice any other warnings feel free to re-open.
