### ISSUE TITLE
using type name attribute in XMLOutputArchive leaves undesired characters in type

### ISSUE THREAD

**Issue by javenPHD** [USCiLab/cereal#153]
The problem is in this segment of code (in xml.hpp, at or around line 261)

      template <class T> inline
      void insertType()
      {
        if( !itsOutputType )
          return;

        // generate a name for this new node
        const auto nameString = util::demangledName<T>();

        // allocate strings for all of the data in the XML object
        auto namePtr = itsXML.allocate_string( nameString.data(), nameString.size() );

        itsNodes.top().node->append_attribute( itsXML.allocate_attribute( "type", namePtr ) );
      }

Since the nameString parameter is mapped to a char ptr of length 99 issues arise. If the string is shorter, say 47 characters long, then what trails will be binary trash. If you open the resulting XML in your favorite browser it should fail to load, if you open it in an editor the trash should be obvious. To fix this problem you should explicitly let allocate_attribute know the size of "type" and "namePTR". The fix can be seen below.

I have not checked to see if something similar has occurred elsewhere in the code.

      template <class T> inline
      void insertType()
      {
        if( !itsOutputType )
          return;

        // generate a name for this new node
        const auto nameString = util::demangledName<T>();

        // allocate strings for all of the data in the XML object
        auto namePtr = itsXML.allocate_string( nameString.data(), nameString.size() );

        itsNodes.top().node->append_attribute( itsXML.allocate_attribute( "type", namePtr , 4 , nameString.size() ) );
      }

**Comment by javenPHD** [comment]
In case this is important for this bug I am using MSVC 2013.4

**Comment by javenPHD** [comment]
The following would be a simpler candidate

template <class T> inline
      void insertType()
      {
        if( !itsOutputType )
          return;

        // generate a name for this new node
        const auto nameString = util::demangledName<T>();

        // allocate strings for all of the data in the XML object
        auto namePtr = itsXML.allocate_string(nameString.str());

        itsNodes.top().node->append_attribute( itsXML.allocate_attribute( "type", namePtr ));
      }


no size information required.

**Comment by erichkeane** [comment]
In this case nameString ought to be a std::string, based on util.hpp.  Therefore I suspect that THIS part of the code is correct.

However, I looked into util.hpp I'm curious as to whether the usage of abi::__cxa_demangle might be the cause of this issue.

**Comment by javenPHD** [comment]
Not sure about that since that is only used if you are running clang or gcc. The demangle call for MSVC is essentially a donothing, returning only the string that was passed in to it.

**Comment by AzothAmmo** [comment]
I have to echo @erichkeane here - I feel like if anything is wrong it is because of null-termination that we might be missing when we hop over to the C style interface.

**Comment by javenPHD** [comment]
I agree that it should be std::string. I didn't say there is an issue there.

It is in these two lines

    auto namePtr = itsXML.allocate_string( nameString.data(), nameString.size() );

    itsNodes.top().node->append_attribute( itsXML.allocate_attribute( "type", namePtr ) );

the auto style call with data and size both passed results in a ptr of indeterminate size, resulting in null termination. 

allocate_string can determine the size of a string, there is not need to pass it the size. That actually breaks the call. If you pass a size to namePtr, then you need to pass the sizes in the second line for "type" and namePtr, otherwise there is no proper termination point inside of the call. Simply changing the first line to

    auto namePtr = itsXML.allocate_string( nameString.data() );

should be down the right path. 

I guess there could be a null termination, but I doubt it, since the change I placed above works just fine. 

There is no problem with the .size() call, debugging in shows that it works properly, it is the allocation that occurs in allocate_string() which fails to allocate an object of the appropriate size.

**Comment by erichkeane** [comment]
After looking further, I suspect that the issue IS here, or rather, how it is being dealt with.  This is an off-by-one error.  I can reproduce the same problem in gcc, however it requires memory-fuzzing to set it up.

In this line:

        auto namePtr = itsXML.allocate_string( nameString.data(), nameString.size() );

note that std::string::size == std::string::length.  HOWEVER, the allocate_string function prototype above expects (data, size), where 'size' is the amount of data to be copied in BYTES.

In this case, since this is sending the length and not the actual "size" of a c_str (which is length +1 to include the null terminator), this will not allocate enough room for the \0, then copy just the contents of the string(no \0).  If a zero doesn't immediately follow this in memory, this will overrun the buffer.

Note the auto size determination inside of allocate_string does a strlen equiv., then adds one(rapidxml.hpp:479):
 
    size = internal::measure(source) + 1;

I'll submit a pull request in a few minutes.

**Comment by javenPHD** [comment]
Yeah. Figured something along those lines.

**Comment by erichkeane** [comment]
I shoulda seen that much earlier :(  The sentence about it being of length 99 (rather than just a char array being sized improperly) caused me to think you were talking about the size/length being encoded improperly.

**Comment by javenPHD** [comment]
I should have been clearer. Glad it was found.

**Comment by AzothAmmo** [comment]
Give this a test on VS if you get a chance and feel free to close afterwards.  Looks fine through valgrind on Linux.

**Comment by javenPHD** [comment]
Will do on Monday. And will let you know.

**Comment by AzothAmmo** [comment]
Closing this since I haven't run into any issues.
