### ISSUE TITLE
use of ranged for

### ISSUE THREAD

**Issue by javenPHD** [USCiLab/cereal#154]
I am wondering if there is a reason why ranged for's are not used in the code when they would be appropriate. This is seen in vector.hpp for example. You are still using the older iteration using an iterator. Would it not be more suitable and easier to read if you used the ranged for.

BEFORE

//! Serialization for non-arithmetic vector types
  template <class Archive, class T, class A> inline
  typename std::enable_if<!traits::is_input_serializable<BinaryData<T>, Archive>::value
                          || !std::is_arithmetic<T>::value, void>::type
  load( Archive & ar, std::vector<T, A> & vector )
  {
    size_type size;
    ar( make_size_tag( size ) );

    vector.resize( static_cast<std::size_t>( size ) );
    for( auto it = vector.begin(), end = vector.end(); it != end; ++it )
      ar( *it );
  }

AFTER

//! Serialization for non-arithmetic vector types
  template <class Archive, class T, class A> inline
  typename std::enable_if<!traits::is_input_serializable<BinaryData<T>, Archive>::value
                          || !std::is_arithmetic<T>::value, void>::type
  load( Archive & ar, std::vector<T, A> & vector )
  {
    size_type size;
    ar( make_size_tag( size ) );

    vector.resize( static_cast<std::size_t>( size ) );
    for( auto & values : vector )
      ar( values );
  }

Just a thought.

**Comment by AzothAmmo** [comment]
Check out the [develop version](https://github.com/USCiLab/cereal/blob/develop/include/cereal/types/vector.hpp) of vector.

**Comment by javenPHD** [comment]
Ty Azoth!
