### ISSUE TITLE
Interest in compiling with an older GCC compiler?

### ISSUE THREAD

**Issue by erichkeane** [USCiLab/cereal#161]
Hi-
My use of this library (1.1) ended up needing gcc 4.6.3 in order to work.  I ended up having to change afew things (using a=b to typedef) and it ends up working fine.

I realize this project wants to be completely C++11 (and I understand that, and is why I haven't pushed this in the month+ since I got it working), but if there was interest, perhaps a branch of these changes would be worth while?

What does everyone think, anyone care?

**Comment by randvoorhies** [comment]
If the changes are really just cosmetic (e.g. typdefs), then I think I'm all for it.

**Comment by AzothAmmo** [comment]
We might also use some delegating constructors somewhere.  Relevant: https://gcc.gnu.org/projects/cxx0x.html.  I think we started using using over typedefs here (7ef5a9311bc1245fc98f5352a254aba895bcf492) when MSVC 2013 was officially released (typedefs are so ugly).

**Comment by patlecat** [comment]
Ancient compilers shouldn't be supported, only takes too much time and risks in doing so.

Btw by using CMake you can avoid a lot of macro usage in code ;)
