### ISSUE TITLE
Happily build non-boost sandboxes when Boost not found

### ISSUE THREAD

**Issue by eschnett** [USCiLab/cereal#162]
I configure Cereal with `-DCMAKE_DISABLE_FIND_PACKAGE_Boost=TRUE` to disable Boost. This fails when `sandbox/sandbox_vs.cpp` is built, since this unconditionally includes `cereal/types/boost_variant.hpp`.

**Comment by AzothAmmo** [comment]
cereal requires Boost to build its unit tests and various other sandbox files.  The actual cereal library is header only and has no external requirements.

**Comment by AzothAmmo** [comment]
Just read this again and may have closed in haste, can't remember if our unit tests don't get built when boost is not found. We can put a similar requirement for the sandbox too. There isn't much worth compiling without Boost though.

-----Original Message-----

**Comment by eschnett** [comment]
Yes, I think building `sandbox_vs` should be omitted if Boost is not present. The other sandbox builds seem to work fine without Boost.

**Comment by erichkeane** [comment]
It seems to me  a simple ifdef around the boost_variant include should be all it would take, no?

A quick audit shows that performance.cpp also uses it a lot however.  The unit tests are actually all using boost unit_test, so I doubt they'll be building at all without boost.

**Comment by AzothAmmo** [comment]
Removed the variant include from sandbox and a dead sandbox file we didn't use.  Unit tests and performance already check for boost before building, so everything should be OK now (on develop).
