### ISSUE TITLE
NuGet bump to 1.1.0

### ISSUE THREAD

**Issue by ph03** [USCiLab/cereal#163]
Hi!

We are using cereal in a sizy project using NuGet [https://www.nuget.org/packages/cereal/] and would like to update our version to 1.1.0 . Is it possible to bump the version in that code repository to the latest version and keep it updated with new releases?

Thanks a lot! J

**Comment by AzothAmmo** [comment]
We aren't the ones who submitted it to NuGet, so I'm not sure what the policy is here on getting it updated there.  Perhaps contact the maintainer who seems to be https://www.nuget.org/profiles/lsantos.

**Comment by AzothAmmo** [comment]
Trying to get ownership of the NuGet page now as 'Azoth' (hello NuGet!)

**Comment by AzothAmmo** [comment]
Tried to get control over the NuGet page but was never successful.  Doesn't seem like many people are using it to get cereal anyway, so I'm going to close this and not worry about it.
