### ISSUE TITLE
CEREAL_REGISTER_DYNAMIC_INIT and CEREAL_FORCE_DYNAMIC_INIT macros don't support nesting

### ISSUE THREAD

**Issue by jhol** [USCiLab/cereal#164]
`CEREAL_REGISTER_DYNAMIC_INIT(Name)` and `CEREAL_FORCE_DYNAMIC_INIT(Name)` make a symbol name `cereal::detail::dynamic_init_dummy_##LibName()` where `##` is replaced with the value of `Name`. This will work find with a simple class name `Foo`, but will fail with namespaces and nested classes: `CEREAL_REGISTER_DYNAMIC_INIT( my::namespace::Foo::Bar )`

**Comment by luca-penasa** [comment]
was this problem solved? or was not a problem?

**Comment by jhol** [comment]
IIRC it was my mistake.

**Comment by luca-penasa** [comment]
ok thanks !
