### ISSUE TITLE
Partial update using json archive missfire

### ISSUE THREAD

**Issue by felixzng** [USCiLab/cereal#167]
we have a Foo struct

struct Foo
{
    int abc = 1;
    int abcxyz = 2;   

    friend class cereal::access;
    template <class Archive>
    void serialize( Archive & ar )
    {
       ar(CEREAL_NVP(abc));
       ar(CEREAL_NVP(abcxyz));
    }
};

If we use json archive and try to apply a partial update like  '{ "Foo": {"abcxyz":67} }'
it will misfire and update both variables to 67.

The issue is in json.hpp
       inline void search( const char * searchName )

The following shoud fix it
replace
    if ( std::strncmp( searchName, it->name.GetString(), len ) == 0 )

with
    if ( std::strncmp( searchName, it->name.GetString(), len ) == 0 && len == nlen)

**Comment by AzothAmmo** [comment]
Would you be able to create a pull request and a unit test to demonstrate this issue?

**Comment by felixzng** [comment]
Sure. This is my first time. I need figure out how it is done. Just in case adding a complete code example here.

-----------------------------


/*
from command line

	footest  '{ "Foo": {"abcxyz":67} }'
*/




#include <cereal/archives/json.hpp>
#include <iostream>
#include <sstream>


// ignore exeptions
#define WRAP(n)  try {ar(CEREAL_NVP(n));} catch(...){}


struct Foo
{
	int					abc = 11;
	int					abcxyz = 12;

    friend class cereal::access;
    template <class Archive>
    void serialize( Archive & ar )
    {
		WRAP(abc);
		WRAP(abcxyz);
    }
};


int
main(int argc, char ** argv)
{
	std::string s = "";
	if (argc > 1)
	{
		s = argv[1];
		std::cout << "s="<< s << std::endl;
	}

	Foo foo;
	std::cout << std::endl << "===" << std::endl;
	{
		cereal::JSONOutputArchive ar(std::cout);
		ar( cereal::make_nvp("Foo", foo) );
	}
	std::cout << std::endl;
	
	if (s != "")
	{
		std::cout << std::endl << "---" << std::endl;
		std::istringstream istr( s.c_str() ); 

		cereal::JSONInputArchive ar(istr);
		ar( cereal::make_nvp("Foo", foo) );				
		{
			cereal::JSONOutputArchive ar_out(std::cout);
			ar_out( cereal::make_nvp("Foo", foo) );
		}
	}
}

**Comment by AzothAmmo** [comment]
fixed by 5d541d3
