### ISSUE TITLE
BOOST_SERIALIZATION_SPLIT_MEMBER() preventing compile

### ISSUE THREAD

**Issue by LLay** [USCiLab/cereal#170]
Hi there, 
I'm going over your Transitioning from Boost tutorial. Are the examples supposed to compile as such? I'm finding that BOOST_SERIALIZATION_SPLIT_MEMBER() is (implicitly) stopping cereal from recognizing the save/load pair. I cannot have code in main() to serialize with both boost and cereal, and have it compile, presumably because of BOOST_SERIALIZATION_SPLIT_MEMBER() whose existence stops cereal from recognizing the load save functions. And whose lack of existences stops boost from recognizing the load save functions. I've tried with all different archive and stream types. I've tried using your different releases, and cloned the working version. Without the save/load pair, and just serialize, it works fine.
Is this supposed to be the case?

**Comment by AzothAmmo** [comment]
Looking at that example I don't think we ever tried to compile it - the variables that are serialized in `SomeData` are never defined, for instance.

Looks like the implementation of `BOOST_SERIALIZATION_SPLIT_MEMBER` actually defines a function called `serialize`, which is a conflict for us.  So you'd actually have to pair this with some disambiguation for cereal until you could remove the boost code, such as:

`CEREAL_SPECIALIZE_FOR_ALL_ARCHIVES( SomeData, cereal::specialization::member_load_save )`

We'll update the example to reflect this.
