### ISSUE TITLE
Load legacy boost data alongside cereal data

### ISSUE THREAD

**Issue by LLay** [USCiLab/cereal#172]
Hi there, I'm migrating some software from boost to cereal. How can I handle legacy data saved in Boost binary? The idea was to have something like:
class MyClass {
...
template<class Archive>
void load(Archive & ar, const unsigned int version) {
    if (version == 1) { // Load with boost
         ar >> boost::serialization::make_nvp("foo_object", foo);
    else if (version >= 2) { // Load with Cereal
         ar (cereal::make_nvp("foo_object", foo));
    }
  }
...
}

But since the archive is created at compile time as a Boost archive or Cereal archive and passed to this template class there is no way for it to know that the boost and cereal (nvp) functions are not in conflict. It won't compile. 

Preliminary thoughts were to use different namespaces, or one internal load functions and one external, or a subclass MyClassCerealSerializer with the Cereal serialize methods and leave the old boost methods in MyClass. But none of these will work. 

Do you supply a way to load legacy boost data alongside saving and loading cereal data?

Thanks for your help on my last issue! 

Lyon

**Comment by AzothAmmo** [comment]
You can rename all of the cereal serialization functions using [macros.hpp](https://github.com/USCiLab/cereal/blob/master/include/cereal/macros.hpp) and avoid any conflict between boost and cereal that way.  cereal/boost are not binary compatible so you need to make a hard distinction between the two before you attempt to read or write to them.
