### ISSUE TITLE
Strange file name when downloading cereal

### ISSUE THREAD

**Issue by eschnett** [USCiLab/cereal#173]
When I download cereal via wget, wget is redirected (http 302). This used to be different. The file to which wget is redirected does not have a `.tar.gz` extension any more. See the screen output:

```
[eschnett@shelob1 q]$ wget https://github.com/USCiLab/cereal/archive/v1.1.0.tar.gz
--2015-02-28 14:41:27--  https://github.com/USCiLab/cereal/archive/v1.1.0.tar.gz
Resolving github.com... 192.30.252.128
Connecting to github.com|192.30.252.128|:443... connected.
HTTP request sent, awaiting response... 302 Found
Location: https://codeload.github.com/USCiLab/cereal/tar.gz/v1.1.0 [following]
--2015-02-28 14:41:27--  https://codeload.github.com/USCiLab/cereal/tar.gz/v1.1.0
Resolving codeload.github.com... 192.30.252.144
Connecting to codeload.github.com|192.30.252.144|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 200495 (196K) [application/x-gzip]
Saving to: “v1.1.0”

100%[======================================>] 200,495     1.18M/s   in 0.2s    

2015-02-28 14:41:27 (1.18 MB/s) - “v1.1.0” saved [200495/200495]
```

The file that is saved to disk is called `v1.1.0` instead of the `v1.1.0.tar.gz` I would expect. This is quite inconvenient, as many Unix tools depend on the file extension to determine the file type.

This redirection happens to me on Unix, but not on OS X.

**Comment by AzothAmmo** [comment]
I don't think we have any control over this - those files are generated automatically when we create releases and hosted by GitHub.  Perhaps GitHub has changed or broken something related to this.

**Comment by eschnett** [comment]
The problem seems to have gone away. I assume it then was a temporary glitch with github.
