### ISSUE TITLE
Polymorphic loading simply isn't there.

### ISSUE THREAD

**Issue by robstoddard** [USCiLab/cereal#174]
Suppose I have a class called Object,   derived from that are three classes,  Ball, Bat and Glove.   A file holds a Ball, Bat or Glove, without specifying what type it actually holds.   I can't load the data into an Object pointer, reference or other thing without actually knowing whether the Object in the file is a Ball, Bat or Glove.   The whole point to polymorphism is not needing to know what an Object actually is, all I should be required to do is load the Object, and then playBall(), and the Object should behave according to its real type.

This is a real showstopper for me, and because of this issue, this library is completely useless to me.

**Comment by randvoorhies** [comment]
Polymorphism is fully handled by cereal. Please read the docs here: http://uscilab.github.io/cereal/polymorphism.html

If you have further issues please post a code sample.

**Comment by robstoddard** [comment]
In your example:

    // Create instances of the derived classes, but only keep base class pointers
    std::shared_ptr<BaseClass> ptr1 = std::make_shared<DerivedClassOne>();
    std::shared_ptr<BaseClass> ptr2 = std::make_shared<EmbarrassingDerivedClass>();
    oarchive( ptr1, ptr2 );

Your example proves it right here:

    std::shared_ptr<BaseClass> ptr1 = std::make_shared<DerivedClassOne>();
    std::shared_ptr<BaseClass> ptr2 = std::make_shared<EmbarrassingDerivedClass>();

You have to know a-priori what objects are being loaded.   This completely escapes the whole reason for polymorphism.   I suppose I can put a value or string or something in the stream before-hand that tells me what object to expect, but why duplicate this data since it's already in there?    If the library simply allocated the objects itself, this situation wouldn't be happening, however, it requires I preallocate the blocks, which requires me to know what is being loaded before it's loaded.

**Comment by robstoddard** [comment]
I must have completely read the document wrong before hand.   I will try this out.

**Comment by randvoorhies** [comment]
No problem, let us know if you encounter any issues.
