### ISSUE TITLE
Serializing function pointers

### ISSUE THREAD

**Issue by eschnett** [USCiLab/cereal#177]
I want to serialize function pointers (and member function pointers and member object pointers). I know that their layout is architecture specific, and that this only makes sense if the receiver is the same executable. I have an implementation that works on x86 Linux and OS X (following the x86 psABI). This allows e.g sending function pointers between several processes that are executing simultaneously, communicating via MPI.

However, this implementation conflicts with a `static_assert` in Cereal that prevents serializing raw pointers. Would it be possible to introduce a mechanism to disable this mechanism? For example:

``` diff
--- include/cereal/types/common.hpp
+++ include/cereal/types/common.hpp
@@ -106,14 +106,16 @@
     t = reinterpret_cast<typename common_detail::is_enum<T>::type const &>( value );
   }

+#ifndef CEREAL_ENABLE_RAW_POINTER_SERIALIZATION
   //! Serialization for raw pointers
   /*! This exists only to throw a static_assert to let users know we don't support raw pointers. */
   template <class Archive, class T> inline
   void CEREAL_SERIALIZE_FUNCTION_NAME( Archive &, T * & )
   {
     static_assert(cereal::traits::detail::delay_static_assert<T>::value,
       "Cereal does not support serializing raw pointers - please use a smart pointer");
   }
+#endif

   //! Serialization for C style arrays
   template <class Archive, class T> inline
```

If you are interested, I'd be happy to contribute my function-pointer serializing code to Cereal. My current implementation is available at https://bitbucket.org/eschnett/funhpc.cxx/src/8dfa72f9c152f2a9e36f17ce36d51a890a214509/cxx/serialize.hpp?at=rewrite. However, given the caveats regarding operating systems and CPU architectures, this would likely be an expert-only feature.

**Comment by AzothAmmo** [comment]
We'd potentially consider this as a module but probably not as a core cereal feature, especially given the caveat.  Modules are the next big thing I'll be working on when I have some free time - from your point of view the only thing cereal needs to provide is a way to have that exception not fire for function pointers, correct?

**Comment by eschnett** [comment]
Almost -- it should fire neither for function pointers, nor member function pointers, nor member object pointers. However, you are currently not checking for the latter two.
