### ISSUE TITLE
Conversion from (u)int32_t to (u)int8_t

### ISSUE THREAD

**Issue by javenPHD** [USCiLab/cereal#178]
Following error found 

MSVC 2013

Warning	1	warning C4244: '=' : conversion from 'int32_t' to 'int8_t', possible loss of data	\cereal\archives\xml.hpp	513 

(519 also)

Is this intended, if so shouldn't warnings be disabled on this section of code

**Comment by randvoorhies** [comment]
Good catch, this looks like a copy paste error to me.  If you want to change that to uint8_t and run the test suite, you can submit a pull request.  Otherwise I can do it in the next day or so.

**Comment by javenPHD** [comment]
No boost so I am guessing that I won't be able to. If you want to that's
fine too.

**Comment by AzothAmmo** [comment]
These warnings shouldn't ever actually result in errors, I think these will be removed with #151.  The fix for both is just to static_cast the assignment from the int32_t to int8_t.

**Comment by javenPHD** [comment]
You pass in an int8. Why create an int32 and cast. Just wondering. Yeah no
see no issue in running with warning.

**Comment by AzothAmmo** [comment]
It's an int8 reference we assign to.  RapidXML doesn't do anything special for int8 so we actually save them as int32s.
