### ISSUE TITLE
error in serialization after commit 994aceeec09cee78378fd5e172aafde5c13d4800

### ISSUE THREAD

**Issue by luca-penasa** [USCiLab/cereal#180]
I recently pulled the latest commits from cereal repo and suddently one of my classes stopped serializing like it used to do before. The error message is this one:

```
Some problem serializing the file: Trying to save an unregistered polymorphic type [...]
```

after some bisecting the commit "introducing this error" is this one: 994aceeec09cee78378fd5e172aafde5c13d4800

the class failing serialization is build i a solib, its a polymorphyc type and it used to serialize perfectly before this commit. I though some cereal change was trying to force me to use CEREAL_REGISTER_DYNAMIC_INIT and CEREAL_FORCE_DYNAMIC_INIT to force instantiate my class but I did not had too much success in using them, maybe cause it is not compeltely clear to me where these should be placed (do I need to place them both?)

I am registering my polymorphic types in the source file associated with the class's header.

any help on this topic?

many thanks

**Comment by luca-penasa** [comment]
ADD 1: the failing class has a splitted load/save serialization function with versioning. Other classes, which does not use splitted load/save couple serialize just fine after that commit. Maybe the changes in 

```diff
- create_bindings<Archive,T>::save( std::is_base_of<detail::OutputArchiveBase, Archive>() );
+ create_bindings<Archive,T>::save( std::integral_constant<bool,
+ std::is_base_of<detail::OutputArchiveBase, Archive>::value &&
+ traits::is_output_serializable<T, Archive>::value>{} );
- create_bindings<Archive,T>::load( std::is_base_of<detail::InputArchiveBase, Archive>() );
+ create_bindings<Archive,T>::load( std::integral_constant<bool,
+ std::is_base_of<detail::InputArchiveBase, Archive>::value &&
+ traits::is_input_serializable<T, Archive>::value>{} );
```

could be responsable (?)

**Comment by AzothAmmo** [comment]
For the archive type you are using (e.g. binary, xml, etc), have you included its header prior to performing the registration?  The safest place to do this include would be in the source file where you perform the registration.

The change made it so that registration would fail silently if a specific archive type was not compatible with a type but work otherwise.  Can you tell me the output of `cereal::traits::is_output_serializable<T, Archive>::value` for the type/archive combination?  Also `cereal::traits::is_input_serializable<T, Archive>::value`.

**Comment by luca-penasa** [comment]
my base class uses a serialize() method. the derived one is specialized with load/save couple. The strange thing is that the class is serialized ok when I switch to the serialize method only also for the derived class. In both cases I am using a call to CEREAL_SPECIALIZE_FOR_ALL_ARCHIVES

Yes I  am including my archive types hpp before registering the class.  You can have a look at my registration here:
https://github.com/luca-penasa/spc/blob/master/spc/elements/SelectionRubberband.cpp

Sure! I'll try. But I am convinced it evaluates to FALSE. because if I change 
```cpp
create_bindings<Archive,T>::load( std::integral_constant<bool,
 std::is_base_of<detail::InputArchiveBase, Archive>::value &&
 traits::is_input_serializable<T, Archive>::value>{} );
```

with 
```cpp
create_bindings<Archive,T>::load( std::is_base_of<detail::InputArchiveBase, Archive>() );
```

(and the same for save)
everything works fine. So i must be a problem of is_input_serializable 

Maybe the count_input_serializers not summing to one??

**Comment by luca-penasa** [comment]
In fact the output of:

```cpp
	std::cout << cereal::traits::is_input_serializable< spc::SelectionRubberband, cereal::BinaryOutputArchive>::value << std::endl;

	std::cout << cereal::traits::detail::count_output_serializers<spc::SelectionRubberband, cereal::BinaryOutputArchive>::value << std::endl;
 ```
is :
```
0
2
```


Thus it is counting to 2! Shouldnt cereal warn about that??

**Comment by luca-penasa** [comment]
Notice that I am specializing with:
CEREAL_SPECIALIZE_FOR_ALL_ARCHIVES( spc::SelectionRubberband, cereal::specialization::member_load_save )

**Comment by AzothAmmo** [comment]
I'll try and make a small test case of this, it looks like there might be a problem with the count and specialization.

**Comment by luca-penasa** [comment]
test code here https://github.com/luca-penasa/cereal-test 
reproduces the error

**Comment by AzothAmmo** [comment]
Should be all good to go now!
