### ISSUE TITLE
VS2013 exception with empty std::string

### ISSUE THREAD

**Issue by grivlis** [USCiLab/cereal#182]
The following code:

    #include "cereal/archives/xml.hpp"
    #include "cereal/types/string.hpp"
    
    int _tmain(int argc, _TCHAR* argv[])
    {
        std::string ci;
        std::ostringstream oss;
        {
            cereal::XMLOutputArchive oar(oss);
            oar(ci);
        }
        return 0;
    }

gives an exception only in DEBUG mode on VS2013.
line 238 of xml.hpp:

    if( !strValue.empty() && ( xml_detail::isWhitespace( strValue[0] ) || xml_detail::isWhitespace( strValue[strValue.length() - 2] ) ) )

This is similar to issue #69

**Comment by AzothAmmo** [comment]
Will take a look at this and squeeze in as the last fix for 1.1.1.
