### ISSUE TITLE
JSONInputArchive does not match whole node name

### ISSUE THREAD

**Issue by Pentops** [USCiLab/cereal#183]
An exception should be thrown when searching for "node_name" in a JSON structure that only contains "node_name_2". It is currently identifying this as a match and failing to throw an exception.

See `JSONInputArchive::Iterator::search()`.

**Comment by AzothAmmo** [comment]
I think this is related to the following pull requests that weren't merged for whatever reason: #168, #169.

**Comment by Pentops** [comment]
Yes indeed. That looks like a good fix.

**Comment by AzothAmmo** [comment]
dup of #167
