### ISSUE TITLE
Multiple Inheritance + Polymorphism Seg Fault

### ISSUE THREAD

**Issue by AzothAmmo** [USCiLab/cereal#188]
See discussion on mailing list and related issue #187.

Minimal example provided by David Bond:

```cpp
#include <cereal/archives/json.hpp>
#include <cereal/types/polymorphic.hpp>
#include <iostream>

struct Base {
    virtual void foo() { } 
    template<class Archive> void serialize(Archive& archive) { } 
};

struct Base2 {
    virtual void foo() { } 
    std::string var;
    template<class Archive> void serialize(Archive& archive) {   
        archive(cereal::make_nvp("var", var));
    }   
};

struct Derived : public Base2, public Base {
    template<class Archive> void serialize(Archive& archive) {   
        archive(cereal::make_nvp("Base2",
                                 cereal::base_class<Base2>(this)),
                cereal::make_nvp("Base",
                                 cereal::base_class<Base>(this)));
    }   
};

CEREAL_REGISTER_TYPE(Derived);

int main() {
    auto ptr = std::make_shared<Derived>();
    cereal::JSONOutputArchive ar(std::cout);
    ar(cereal::make_nvp("ptr", std::dynamic_pointer_cast<Base>(ptr)));

    return 0;
}
```

**Comment by bbouzan** [comment]
I have this same bug on my system, is there any workaround?

**Comment by AzothAmmo** [comment]
No solution yet, I haven't had the time to look into it.  Potentially related issue discussed on the mailing list here: https://groups.google.com/forum/#!topic/cerealcpp/ifoi4a36C5k

**Comment by Mokon** [comment]
@bbouzan on my project where I hit this I simply removed multiple inheritance. (In my case it was simply a output class that I could do that without any trouble.) That isn't really a solution though... But the key here is the internal code is casting a class to a void* then back to another of the types.

**Comment by ylobanov** [comment]
Hello,
In our project we are about to start implementation of serializatioin, and there is a choice between cereal and boost::serialization. Cereal looks much more attractive then boost, but this bug is an issue for us. I wonder if it is reasonable to wait for the fix or it's better to use boost. Do you have any estimates? Thanks

**Comment by AzothAmmo** [comment]
All progress is on a mini-hiatus until December, when I'll have time to tackle the various issues. I can't estimate how long fixing this one individual bug will take, but that's the point when I'd start trying to fix it.

If this timeframe won't work for you, take a look at [our boost transition page](http://uscilab.github.io/cereal/transition_from_boost.html). It may be possible for you to easily switch to cereal once the issue is resolved as we support an identical syntax to that found in boost serialization.

**Comment by ylobanov** [comment]
Thanks for the information, we'll wait for December

**Comment by AzothAmmo** [comment]
Small update on this: I've investigated the problem and know what is causing it though I haven't come up with a solution yet. David Bond correctly identified the source of the issue on the mailing list, we're ending up at an incorrect address do a void * cast.

**Comment by AzothAmmo** [comment]
So we'll basically have to implement something very much like boost's `void_cast_register`.

**Comment by AzothAmmo** [comment]
I have this fixed locally, finishing up documentation and cleanup and will push it through soon. This will involve a breaking change for certain polymorphic serialization situations.

**Comment by ylobanov** [comment]
thanks for updating!
