### ISSUE TITLE
std::vector < std::array > - throws std::length_error

### ISSUE THREAD

**Issue by ninnghazad** [USCiLab/cereal#192]
struct Mesh {
	    std::vector < std::array<float, 2> > vertices;
	    std::vector < std::array<unsigned int, 3> > triangles;
	    std::vector < std::array<unsigned int, 2> > segments;
	    std::vector < std::vector<unsigned int> > boundaries;
	    std::array<float, 4> extent;
	    template <class Archive> void serialize( Archive & ar ) {
		    ar(vertices,triangles,segments,boundaries,extent);
        }
    }

compiles fine, on runtime (on deserialization, serialization seems ok):

    terminate called after throwing an instance of 'std::length_error'
      what():  vector::_M_default_append

i have vector and array included, and otherwise both serialize fine. serializing only 'vertices' works, it seems to err on the second item of std::vector<std::array> i add. if i switch vertices and triangles position in ar() it throws 'std::bad_alloc'. not sure if bug or me.

**Comment by AzothAmmo** [comment]
Sounds like you might not be initializing your vectors before you save them. That exception is thrown when the vector attempts to reserve a size larger than a pre defined maximum possible size. If you save invalid sizes, cereal will use that invalid size when it does the load.

-----Original Message-----

**Comment by ninnghazad** [comment]
it happens on load, saving works fine. before loading the vectors are all empty also.

**Comment by ninnghazad** [comment]
i wrote a minimal test and it works, so it is not a bug and i will just close this.  guess i am trying to read the mesh from the wrong place in the archive.

**Comment by guozhizou** [comment]
Got the exactly same issues, any solutions to share?

**Comment by ninnghazad** [comment]
sorry, that was years ago an i haven't had the problem since. but drop some code and maybe i can spot something. chances are writing a minimal testcase will reveal the solution.

**Comment by Krzmbrzl** [comment]
FWIW the error also appears to be thrown, when attempting to resize a vector to a negative size (which presumably gets converted to `std::size_t` and is then a ludicrously large number).
