### ISSUE TITLE
JSONInputArchive deserializes partially matched keys

### ISSUE THREAD

**Issue by patjdor** [USCiLab/cereal#195]
1. What I do:
Serialize an archive
Deserialize an archive
Try to read an NVP that is not present during serialization and matches as a substring of another key

2. What I expect:
An error

3. What happens:
The value is read from the matched substring

Example Program:

    #include <cereal/archives/json.hpp>
    #include <iostream>
    #include <sstream>

    int main(int argc, char** argv){
        std::stringstream ss;
        {
            cereal::JSONOutputArchive ar(ss);
            int foobar = 1;
            ar(cereal::make_nvp("foobar",foobar));
        }
        
        {
            cereal::JSONInputArchive ar(ss);
            int foobar = -1;
            int foo = -1;
            ar(cereal::make_nvp("foobar",foobar));
            ar(cereal::make_nvp("foo",foo));
            std::cerr<<"Foobar: "<<foobar<<std::endl;
            std::cerr<<"Foo: "<<foo<<std::endl;
        }
    }

Compile:

    g++ --std=c++11 main.cpp -o hello

Run 

    ./hello
    Foobar: 1
    Foo: 1

**Comment by AzothAmmo** [comment]
This is fixed in #167, I'll release that milestone today since it's been sitting done for a month.
