### ISSUE TITLE
JSONInputArchive's different behavior from XMLInputArchive 

### ISSUE THREAD

**Issue by henrywoo** [USCiLab/cereal#208]
I have code as follows and it works fine:

      ifstream f(xmlpath);
      if (fs::exists(xmlpath)){
        cereal::XMLInputArchive iarchive(f);
        if (f.is_open() && f.good()){
          iarchive(*this);
        }
      }else{
        return;
      }

After replacing XMLInputArchive  with JSONInputArchive , f.is_open() && f.good() will return false.

Anybody know the reason why?

**Comment by AzothAmmo** [comment]
RapidJSON does all of its parsing during the constructor for the archive, so the file is already closed by the time you do your check.  Try seeing what `eof()` returns.

**Comment by henrywoo** [comment]
Thanks for the explanation
