### ISSUE TITLE
explicit versioning with namespaces

### ISSUE THREAD

**Issue by orzechow** [USCiLab/cereal#209]
How can I use the [explicit versioning functions](http://uscilab.github.io/cereal/serialization_functions.html#versioning) for classes in namespaces?
I have tried both to declare the CEREAL_CLASS_VERSION within or outside of my private namespace, but both versions fail.
See [this Gist](https://gist.github.com/orzechow/e8066e022571cd82b2a1) for a full, but minimal, example based on the cereal Docs.

Compiling `cereal_version_test_outside_ns.cpp` returns

```
In file included from cereal_version_test_outside_ns.cpp:1:0:
my_dir/cereal-master/include/cereal/cereal.hpp:207:23: error: ‘CEREAL_CLASS_VERSION_REGISTERmy_cool_namespace’ has not been declared
     static const auto CEREAL_CLASS_VERSION_REGISTER##TYPE##VERSION_NUMBER =      \
                       ^
cereal_version_test_outside_ns.cpp:34:1: note: in expansion of macro ‘CEREAL_CLASS_VERSION’
 CEREAL_CLASS_VERSION( my_cool_namespace::MyCoolClass, 1 );
 ^
```

Compiling `` returns

```
my_dir/cereal-master/include/cereal/cereal.hpp:197:24: error: ‘Version’ is not a class template
     template <> struct Version<TYPE>                                             \
                        ^
cereal_version_test_within_ns.cpp:32:1: note: in expansion of macro ‘CEREAL_CLASS_VERSION’
 CEREAL_CLASS_VERSION( MyCoolClass, 1 );
 ^
my_dir/cereal-master/include/cereal/cereal.hpp:198:5: error: explicit specialization of non-template ‘my_cool_namespace::cereal::detail::Version’
     {                                                                            \
     ^
cereal_version_test_within_ns.cpp:32:1: note: in expansion of macro ‘CEREAL_CLASS_VERSION’
 CEREAL_CLASS_VERSION( MyCoolClass, 1 );
 ^
my_dir/cereal-master/include/cereal/cereal.hpp:200:14: error: ‘my_cool_namespace::cereal::detail::Version’ is not a template
       static Version<TYPE> registerVersion()                                     \
              ^
cereal_version_test_within_ns.cpp:32:1: note: in expansion of macro ‘CEREAL_CLASS_VERSION’
 CEREAL_CLASS_VERSION( MyCoolClass, 1 );
 ^
...
```

It seems to me, that the CEREAL_CLASS_VERSION macro has not been intended for the use with namespaced classes.
This is basic requirement for such a feature in my opinion.

**Comment by AzothAmmo** [comment]
I can't reproduce your error when `CEREAL_CLASS_VERSION` is placed in the global scope (`cereal_version_test_outside_ns.cpp` compiles correctly on all compilers I have immediate access to).

**Comment by orzechow** [comment]
Thanks for checking - it turned out, that I included an outdated cereal version.
Stupid mistake...

With the current master (and 1.1.2) it works :)
