### ISSUE TITLE
MSVC JSON: mix serialize and save_minimal error

### ISSUE THREAD

**Issue by sschaetz** [USCiLab/cereal#217]
Hi everyone,

I ran into a runtime issue with the JSON archives on visual studio express 2013. It seems like I can not mix `serialize` and `save_minimal` functions when serializing hierarchical types. Here is a reproducer:

```cpp
#include <stdio.h>
#include <stdint.h>
#include <cereal/archives/json.hpp>

template <typename T>
struct foo
{
	T value;
};


template<class Archive, typename T>
T save_minimal(const Archive&, const foo<T>& v)
{
	return v.value;
}

/*
// This version works.
template<class Archive, typename T>
void serialize(Archive & archive, foo<T>& v)
{
	archive(v.value);
}
*/

struct bar
{
	foo<uint8_t> v1;
	foo<uint8_t> v2;
	foo<uint16_t> v3;
	foo<uint8_t> v4;
};


template<class Archive>
void serialize(Archive & archive, bar& m)
{
	archive(::cereal::make_nvp("v1", m.v1));
	archive(::cereal::make_nvp("v2", m.v2));
	archive(::cereal::make_nvp("v3", m.v3));
	archive(::cereal::make_nvp("v4", m.v4));
}


int main(void)
{
	bar b;
	// Serialize to stream.
	std::ostringstream out;
	{
		cereal::JSONOutputArchive outArchive(out);
		outArchive(::cereal::make_nvp("param", b));
	}
}
```

This crashes when writing the third value. I started debugging and it seems like it is not considering the fact that the values serialized with save_minimal don't have a name. In `writeName` the first line popping the stack seems to fail because the stack is zero. The portable binary archive seems to work.

I hope somebody can reproduce this and help fix the issue.

Best,
Sebastian

**Comment by sschaetz** [comment]
The same code works fine on Linux with gcc 4.8.3.

**Comment by AzothAmmo** [comment]
I'll take a look at this - can confirm it works correctly on Linux.

**Comment by sschaetz** [comment]
Azoth, thanks for looking into this. Did you make any progress - could you reproduce the problem?

**Comment by AzothAmmo** [comment]
I can reproduce this on MSVC2013.

**Comment by AzothAmmo** [comment]
Seems that the minimal serialization is incorrectly entering the non-minimal [epilogue](https://github.com/USCiLab/cereal/blob/master/include/cereal/archives/json.hpp#L781) for `foo<unsigned char>`.

The type traits correctly return false for arithmetic, false for having a minimal base class serialization, and true for having a minimal output serialization.  These OR together to give a true value to DisableIf, which should turn off the function if all of its arguments (in this case only the result of the OR) evaluate to true.

There's some kind of bug with MSVC here where it isn't evaluating the OR properly for whatever reason.  We can get around this error by putting parenthesis around at least the `std::is_arithmetic<T>::value` portion of the test.

Should be able to check in a fix for this tomorrow sometime.  I'll have to look around and see if there are any other `EnableIf`/`DisableIf` that MSVC might have some issue with.

**Comment by sschaetz** [comment]
This sounds exactly right @AzothAmmo. I could track it down to it entering the non-minimal epilogue and it trying to erase a name that was not there because for the prologue the minimal path was taken. Unfortunately my investigation ended there.

Very happy you're looking into this!

**Comment by AzothAmmo** [comment]
Fixed on develop, will organize issues and milestones to get recently done changes pushed out sooner rather than later.
