### ISSUE TITLE
CMake addition request

### ISSUE THREAD

**Issue by robiwano** [USCiLab/cereal#222]
With the following addition it is extremely easy to add cereal to CMake based projects:

ADD_LIBRARY(cereal INTERFACE)

TARGET_INCLUDE_DIRECTORIES(
	cereal
	INTERFACE include
)

When a project uses TARGET_LINK_LIBRARIES(target ... cereal ... ), include paths will be set automatically for the given target.

**Comment by AzothAmmo** [comment]
Do you think you can create a pull request for this?

**Comment by robiwano** [comment]
Don't know currently how that works, just recently took the great "git plunge" :) Shall see what I can do.

**Comment by tamaskenez** [comment]
I continued this issue in #254
