### ISSUE TITLE
Help Serializing Template Class

### ISSUE THREAD

**Issue by M2tM** [USCiLab/cereal#225]
I couldn't see any examples of serializing a template class directly. I've dealt a lot with polymorphic classes, but never with templates.  The following class has issues (and I'd prefer to use load_and_construct so I can remove the public SafeComponent() constructor and enforce only valid SafeComponents.):

		template <typename T>
		class SafeComponent {
		public:
			SafeComponent(const std::shared_ptr<const Node> &a_node = nullptr, const std::shared_ptr<T> &a_component = nullptr) :
				wrappedNode(a_node),
				wrappedComponent(a_component) {
			}
			SafeComponent() {
			}

			void operator=(const SafeComponent<T> &a_other) {
				wrappedNode = a_other.wrappedNode;
				wrappedComponent = a_other.wrappedComponent;
			}

			void operator=(const std::shared_ptr<T> &a_component) {
				wrappedNode = a_component->owner();
				wrappedComponent = a_component;
			}

			std::shared_ptr<T> operator->() const {
				return wrappedComponent;
			}

			operator bool() const {
				return wrappedComponent && wrappedNode;
			}

			bool operator!() const {
				return !static_cast<bool>(*this);
			}

			bool operator==(const SafeComponent& a_other) const {
				return a_other.wrappedComponent == wrappedComponent;
			}

			bool operator!=(const SafeComponent& a_other) const {
				return a_other.wrappedComponent != wrappedComponent;
			}

			bool operator==(const std::shared_ptr<T> &a_other) const {
				return a_other == wrappedComponent;
			}

			bool operator!=(const std::shared_ptr<T> &a_other) const {
				return a_other != wrappedComponent;
			}

			std::shared_ptr<T> self() const {
				return wrappedComponent;
			}

			std::shared_ptr<Node> owner() const {
				return wrappedComponent->owner();
			}

			template<typename NewType>
			SafeComponent<NewType> cast() const {
				return SafeComponent<NewType>(wrappedNode, std::static_pointer_cast<NewType>(wrappedComponent));
			}

			void reset() {
				wrappedComponent.reset();
				wrappedNode.reset();
			}

			template <class Archive>
			void serialize(Archive & archive) {
				archive(
					CEREAL_NVP(wrappedNode),
					CEREAL_NVP(wrappedComponent)
				);
			}
		private:
			std::shared_ptr<const Node> wrappedNode;
			std::shared_ptr<T> wrappedComponent;
		};

**Comment by AzothAmmo** [comment]
Everything should work the same way for templated classes - can you be more specific on what the problem/issue is? The built in serialization code for the standard library is all designed to work with templated classes and should be a pretty good set of example code.

**Comment by M2tM** [comment]
I had a few other issues, this can be closed.  I think I was trying something kind of braindead and I don't think it's cereal's fault I was having issues.  If I end up doing something like this in the future and having an issue I'll create a minimal reproducible example.
