### ISSUE TITLE
Non-Const Save?

### ISSUE THREAD

**Issue by M2tM** [USCiLab/cereal#238]
You can call non-const methods in serialize which does load + save, sometimes it's useful to do something like "if(cacheDirty){ updateObjectToReflectCurrentState(); } .... NOW SAVE ...."

But if you want to call load/save pairs separately, save is defined as "const" which makes this impossible.

Is there an easy way to make the const optional? Otherwise you can "work around" this issue, by copying whatever buffers/data you need updated to local function scope and not affecting actual object state, just writing out the processed data...

Anyway, this is not major, just an enhancement, and I'm not sure how you guys feel about it... But it seems like a save method may have non-const desired behavior if dealing with dirty flags/caching/etc.

**Comment by AzothAmmo** [comment]
If you need to modify something in a const function consider making the variable [mutable](http://en.cppreference.com/w/cpp/language/cv).  I don't think this is something we'd change about cereal.

**Comment by randvoorhies** [comment]
This kind of thing is one of the very few good use cases for [const_cast](http://en.cppreference.com/w/cpp/language/const_cast).

**Comment by M2tM** [comment]
Cool, agreed.

**Comment by tloka** [comment]
I now this is closed for a long time already, still I stumbled upon a similar problem and the `mutable` solution was not really appropriate in my case (though, technically possible).  
  
I now solved it in the following way (internal version):
``` c++
template <class archive_t>
void serialize(archive_t & archive)
{
    // Prepare the type for serialization
    // This is only done for output archives, so for serialization
    if constexpr (std::is_base_of_v<cereal::detail::OutputArchiveBase, archive_t>)
        prepare_for_serialization(); // non-const function

    // Now, do archiving for both serialization and deserialization
    archive(whatever_member);
}
```
  
I know this is still not a super clean solution, whenever possible you should still use the `load` and `save` functions, or use `mutable` declarations if appropriate. But for really special cases, this works as an additional solution, so I wanted to share it here.
