### ISSUE TITLE
Compilation warnings

### ISSUE THREAD

**Issue by srheaume** [USCiLab/cereal#246]
With the gcc compiler flags listed below, the library generates a lot of compilation warnings. Most of them are generated by the -Weffc++ flag.

: -Wall -Wshadow -Wpointer-arith -Wcast-qual -Wcast-align -Wwrite-strings -Weffc++ -Woverloaded-virtual

gcc version = 5.2.1

**Comment by AzothAmmo** [comment]
Are any of these warnings worrisome? I hadn't heard of this flag before. We already compile with a fairly strict set of flags (all, extra, shadow, and pedantic), and equivalents on MSVC.

**Comment by AzothAmmo** [comment]
I just looked at all of these in more detail and tried compiling; we compile fine with everything except for Weffc++, which is an unrealistic flag to use. I'm happy with the warnings we use already.
