### ISSUE TITLE
XMLInputArchive crashes in release mode when using precompiled headers with VS

### ISSUE THREAD

**Issue by mikoro** [USCiLab/cereal#247]
If I enable precompiled headers in VS for the cpp file where I use XMLInputArchive, the deserialization will throw an access violation expection in XMLInputArchive::loadValue function.

If I run it in debug mode or if I disable precompiled headers for the file, everything works fine. Binary and JSON deserialization do not have this problem.

(I tried compiling the unit tests to test this with VS but the resulting test executable seems to hang at 100% CPU usage when started.)

**Comment by AzothAmmo** [comment]
Do you think you could create a self contained example of this problem and upload it somewhere?

Also regarding the unit tests, it may actually be doing something. You should run it with --show_progress to ensure it is actually working its way through tests. On some builds (e.g. debug) it can take a while to run.
