### ISSUE TITLE
Compiling with Clang on Windows

### ISSUE THREAD

**Issue by alastairUK** [USCiLab/cereal#248]
I have been experimenting using Clang on Windows through the installs here: http://llvm.org/builds/ and the Clang/C2 functionality in VS2015 Update 1.

Seeing an error ("must have external linkage when declared 'dllexport'") in 

https://github.com/USCiLab/cereal/blob/2f9471bc401590cf58b38bbbc33d412dade6d589/include/cereal/details/static_object.hpp#L41-L47

As _MSC_VER is defined for this compiler option.

**Comment by AzothAmmo** [comment]
What happens if your force cereal to use the clang version in all of the cases where we check for `_MSC_VER`?

**Comment by alastairUK** [comment]
I think this fixes it

```c++
#if defined (_MSC_VER) && !defined (__clang__)
#   define CEREAL_DLL_EXPORT __declspec(dllexport)
#   define CEREAL_USED
#else // clang or gcc
#   define CEREAL_DLL_EXPORT
#   define CEREAL_USED __attribute__ ((__used__))
#endif
```

I  guess the question is are there other instances where the use of `#ifdef _MSC_VER` needs to be changed?

**Comment by AzothAmmo** [comment]
This issue seems like there is a mistake either on the part of clang or Visual Studio for defining `_MSC_VER` when clang is being used - perhaps a bug report should be filed about it.

As we (cereal) as well as the libraries we embed (rapidxml, rapidjson) use tests for MSVC in many places, we would want to change every instance as you did with #252, perhaps with a define somewhere so we only have to use `#ifdef MSVC_COMPILER` or something.

**Comment by h-2** [comment]
> This issue seems like there is a mistake either on the part of clang or Visual Studio for defining _MSC_VER when clang is being used - perhaps a bug report should be filed about it.

_MSC_VER is always defined by visual studio, also for the Intel compiler on Windows so it is not safe to assume the microsoft compiler frontend.

**Comment by erichkeane** [comment]
> _MSC_VER is always defined by visual studio, also for the Intel compiler on Windows so it is not safe to assume the microsoft compiler frontend.

Note that this is the purpose of the Intel compiler. It defines that because it wants you to think it is MSVC. In general, it is A compatible compiler.

**Comment by patrikhuber** [comment]
I think you maybe don't have to bother with this anymore, MS will not work on Clang/C2 anymore, as their own compiler caught up a lot now:
https://twitter.com/stephantlavavej/status/871861920315211776?lang=en
And Andrew Pardoe's comment at the bottom of this blog post: https://blogs.msdn.microsoft.com/vcblog/2017/05/10/c17-features-in-vs-2017-3/
