### ISSUE TITLE
question about version

### ISSUE THREAD

**Issue by daniilsavchenko** [USCiLab/cereal#249]
«When performing loads, cereal will load versioning information if your serialization function is versioned. (!)If you did not use a versioned serialization function to create the archive you are loading from, your data will be corrupted and your program will likely crash. (!) This loaded version number will be supplied via the version parameter you add to your serialization functions.»

What's the point in such restriction? It forces the user to make a decision if every serializable class could be changed in the future. This decision has to be made in the very beginning and there are big chances the decision is wrong. Or one could add version parameter in all serialization functions in all classes, just in case. Would it be a better solution to use default version (0 for example) in case of version abcense in archive, then just to crash? In this case one may not add version info to the class in the beginning, but can add it later when the class gets changed, and it won't break backward compatibility with archives made erlier.

**Comment by AzothAmmo** [comment]
This restriction exists for two reasons: the simplest reason is that cereal did not initially support versioning. The primary reason it exists, however, is that we designed cereal to be minimal in respect to metadata, so the default in this and other situations is to output nothing, if possible. 

cereal does in fact internally use a default version of 0 for all types - the problem you run into is a mismatch in expectation of whether metadata should exist. If the serialization function is not serialized and the serialized data had a version, there is now metadata in some location where the running program expects something else, which usually causes a crash. In the other case, where there was no version in the serialized data, but the serialization function is versioned, data will be misinterpreted as the versioning information and likely cause a crash.

**Comment by daniilsavchenko** [comment]
Oh, yes, I thought about xml and json archives, where all data fields have a metadata, so absence of serialized version info could be simply detected. But in binaries archives, you are right, this trick will not work. Is it a bad idea to make different rules for different kinds of archives?

**Comment by luca-penasa** [comment]
I am migrating some code from non-versioned serializiation functions to versioned ones, any chance to maintain reading compatibility for serialized archives? 

while I get your reply above, is there any chance to just consider all archives that were saved with unversioned functions just as version 0 archives??

what would the right way of migrating to versioned functions??
any idea?

**Comment by gilhagi** [comment]
I have to say, this shortcoming has hurt us badly.  The inability to go from unversioned classes to versioned the first time you need it should at the very least be MUCH more prominent in the documentation.  In really big red letters right in the "getting started" section.  This is a massive gotcha that we missed in our initial implementation.  If anyone has any thoughts about how to work around this, other than making a copy of the class itself, I'm sure many of us would greatly appreciate a workaround.

**Comment by geoffoxholm** [comment]
I agree. Would be great if it just put `0` for the version if you didn't specify.
