### ISSUE TITLE
cmake support / interface library commits are broken

### ISSUE THREAD

**Issue by tamaskenez** [USCiLab/cereal#254]
The commit 7b10a08836cc4db52d376c7521610f9ec9031212 (resolves #222) adds a CMake `INTERFACE` library which breaks the build for older CMake versions.
The commit 1ef6415f156e65c2f1513a0743874ad5e3f4f106 tries to fix this but it's still wrong. The `INTERFACE` library has been introduced in CMake 3.0.

I'd like to draw your attention to PR #239 which solves this and other, related issues and still runs correctly with older CMake versions. I suggest you to revert 1ef6415f156e65c2f1513a0743874ad5e3f4f106 and 7b10a08836cc4db52d376c7521610f9ec9031212 and merge #239 instead.

#239 has been in the queue for almost 3 months. I guess you had some problems with it, that's why you merged 7b10a08836cc4db52d376c7521610f9ec9031212 instead. Please let me know how to improve #239 if that's the case.

**Comment by AzothAmmo** [comment]
I don't think there is any problem with #239, I just missed it when I was organizing things recently - I'll revert and take it instead.

**Comment by AzothAmmo** [comment]
merged #239
