### ISSUE TITLE
Long serialization ambiguous with MinGW

### ISSUE THREAD

**Issue by rdeterre** [USCiLab/cereal#255]
This issue seems very similar to #105, it happens on a Windows 7 64-bit machine with the MinGW 4.9.1 compiler. Removing the `long` and `unsigned long` specializations of `loadValue()` in `json.hpp` seems to be a quick and dirty fix here.

**Comment by kallehuttunen** [comment]
Could you check if this pull request fixes the issue: https://github.com/USCiLab/cereal/pull/257
