### ISSUE TITLE
cereal now in Debian: issues building on 32bit, powerpc, mips, and s390x systems

### ISSUE THREAD

**Issue by mr-c** [USCiLab/cereal#258]
Hello,

I've packaged cereal for the Debian project: https://packages.debian.org/sid/libcereal-dev

We've had some build issues on a few platforms:

[call of overloaded 'loadValue(long unsigned int&)' is ambiguous](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813280#5) for 32 bit systems
```
The i386, mips, mipsel, and x32 builds of libcereal all failed:

  /«PKGBUILDDIR»/./include/cereal/archives/json.hpp:872:5: error: call of overloaded 'loadValue(long unsigned int&)' is ambiguous
       ar.loadValue( t );
       ^
  /«PKGBUILDDIR»/./include/cereal/archives/json.hpp:595:12: note: candidate: void cereal::JSONInputArchive::loadValue(T&) [with T = long unsigned int; typename cereal::traits::detail::EnableIfHelper<std::is_unsigned<_Tp>::value, (sizeof (T) < sizeof (long long unsigned int)), (! std::is_same<bool, T>::value)>::type <anonymous> = (cereal::traits::detail::type)0]
         void loadValue(T & val)
              ^
  /«PKGBUILDDIR»/./include/cereal/archives/json.hpp:653:7: note: candidate: typename std::enable_if<((std::is_same<T, long unsigned int>::value && (! std::is_same<T, unsigned int>::value)) && (! std::is_same<T, long long unsigned int>::value)), void>::type cereal::JSONInputArchive::loadValue(T&) [with T = long unsigned int; typename std::enable_if<((std::is_same<T, long unsigned int>::value && (! std::is_same<T, unsigned int>::value)) && (! std::is_same<T, long long unsigned int>::value)), void>::type = void]
         loadValue( T & t ){ loadLong(t); }
         ^

Please conditionalize one of the variants that is redundant on 32-bit
systems appropriately.
```
[powerpc: call of overloaded 'loadValue(char&)' is ambiguous](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813281#5) for PowerPC systems
```

The powerpc build of libcereal failed:

  /«PKGBUILDDIR»/./include/cereal/archives/xml.hpp:856:5: error: call of overloaded 'loadValue(char&)' is ambiguous
       ar.loadValue( t );
       ^
  /«PKGBUILDDIR»/./include/cereal/archives/xml.hpp:508:12: note: candidate: void cereal::XMLInputArchive::loadValue(T&) [with T = char; typename cereal::traits::detail::EnableIfHelper<std::is_integral<_Tp>::value, (! std::is_same<T, bool>::value), (sizeof (T) == sizeof (char))>::type <anonymous> = (cereal::traits::detail::type)0]
         void loadValue( T & value )
              ^
  /«PKGBUILDDIR»/./include/cereal/archives/xml.hpp:530:12: note: candidate: void cereal::XMLInputArchive::loadValue(T&) [with T = char; typename cereal::traits::detail::EnableIfHelper<std::is_unsigned<_Tp>::value, (! std::is_same<T, bool>::value), (! std::is_same<T, unsigned char>::value), (sizeof (T) < sizeof (long long int))>::type <anonymous> = (cereal::traits::detail::type)0]
         void loadValue( T & value )
              ^

Could you please take a look?  FWIW, plain char is traditionally
unsigned on powerpc.
```

[unrecognized command line option '-m32'](https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=813282#5) for s390x and mips64el
```
The s390x and mips64el builds of libcereal failed:

  c++: error: unrecognized command line option '-m32'
  unittests/CMakeFiles/portability_test32.dir/build.make:65: recipe for target 'unittests/CMakeFiles/portability_test32.dir/portability_test.cpp.o' failed

In general, 64-bit architectures don't necessarily support -m32, or
even explicit -m64.
```

Thanks!

**Comment by AzothAmmo** [comment]
We've consistently had problems with ambiguous overloads in the json/xml archives on various platforms and it's something we do want to (and appreciate any help to) fix.

Regarding the `-m32` error, we have a CMAKE compiler flag `SKIP_PORTABILITY_TEST` which is OFF by default, which if ON causes this test to be skipped. Can the build be controlled for Debian packaging or would the flag need to be ON by default? If there were a way to test if the -m32 flag is supported, that would also be a good fix here.

**Comment by kallehuttunen** [comment]
First two issues should be fixed by this pull request: https://github.com/USCiLab/cereal/pull/257

**Comment by mr-c** [comment]
@AzothAmmo I've passed the SKIP_PORTABILITY_TEST flag for our version -2, and it did help thanks. I'm preparing a package with #257 applied and will post the results from the build cluster.

**Comment by alexfanqi** [comment]
> Regarding the `-m32` error, we have a CMAKE compiler flag `SKIP_PORTABILITY_TEST`

Sorry for replying on this closed long time ago issue. I have a little suggestion to ask.

@AzothAmmo , If it is okay, could you move the option(SKIP_PORTABILITY_TEST, false) out from IF(APPLE) so that it becomes a clear config option (shown on cmake gui perhaps) for all platforms. That will avoid the case if new commit copies the IF(APPLE) for logic that is actually applicable for all platform in the future and sometimes downstream maintainer may be not aware of.
