### ISSUE TITLE
Could not build sandbox on g++-4.9.1

### ISSUE THREAD

**Issue by uilianries** [USCiLab/cereal#262]
When I try build the project with the follow steps:

`git clone https://github.com/USCiLab/cereal.git`
`cd cereal`
`git checkout 2f9471bc401590cf58b38bbbc33d412dade6d589`
`mkdir build && cd build`
`cmake ../ -DCMAKE_BUILD_TYPE=Release`
`make`

I got the follow error:
_Scanning dependencies of target sandbox_
_[ 88%] Building CXX object sandbox/CMakeFiles/sandbox.dir/sandbox.cpp.o_
_/home/uilian.ries/Downloads/cereal/sandbox/sandbox.cpp: In function ‘int main()’:_
_/home/uilian.ries/Downloads/cereal/sandbox/sandbox.cpp:634:17: error: unused variable ‘v’ [-Werror=unused-variable]
     for( auto & v : vec2 )
                 ^_
_cc1plus: all warnings being treated as errors_
_make[2]: *** [sandbox/CMakeFiles/sandbox.dir/sandbox.cpp.o] Error 1_
_make[1]: *** [sandbox/CMakeFiles/sandbox.dir/all] Error 2_
_make: *** [all] Error 2_

I tested with g++-4.8.4 and I received the same error.

My actual system info:

Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.3 LTS
Release:	14.04
Codename:	trusty

Linux 3.13.0-52-generic #86-Ubuntu SMP Mon May 4 04:32:59 UTC 2015 x86_64 x86_64 x86_64 GNU/Linux

g++ 4:4.8.2-1ubuntu6 amd64
g++-multilib 4:4.8.2-1ubuntu6 amd64
libboost-all-dev 1.54.0.1ubuntu1 amd64
doxygen 1.8.6-2 amd64

**Comment by AzothAmmo** [comment]
`-DCMAKE_BUILD_TYPE=Release` is disabling the assert statements used in the sandbox, making it look like the variables go unused. I would just compile the sandbox without the release flag, it's basically a vestigial testing area. 

If you think it is important to be able to compile this with release flags on, we'd welcome a pull request getting around assertion being disabled for the file. We don't use assert in any of the actual cereal core code.

**Comment by uilianries** [comment]
It's not required for me, use explicit _release_ build type. I can use _debug_, no problem.

Thanks for the answer.

**Comment by jujumo** [comment]
Anyway, it would be easy to fix, and its still there (and annoying to find).
