### ISSUE TITLE
Incorrect documentation for Polymorphic serialization

### ISSUE THREAD

**Issue by rcdailey** [USCiLab/cereal#265]
I am referring to the documentation here:
http://uscilab.github.io/cereal/polymorphism.html

It is shown that all you need to do is call `CEREAL_REGISTER_TYPE()` on the derived type, with no changes to the serialization function on the derived class itself. However, when I did only this, I got an exception during serialization because the type's base was unknown.

I then dug into the Cereal code and found this:

```
//! Registers the base-derived relationship for a polymorphic type
/*! When polymorphic serialization occurs, cereal needs to know how to
    properly cast between derived and base types for the polymorphic
    type. Normally this happens automatically whenever cereal::base_class
    or cereal::virtual_base_class are used to serialize a base class. In
    cases where neither of these is ever called but a base class still
    exists, this explicit registration is required.

    The Derived class should be the most derived type that will be serialized,
    and the Base type any possible base that has not been covered under a base
    class serialization that will be used to store a Derived pointer.

    Placement of this is the same as for CEREAL_REGISTER_TYPE. */
#define CEREAL_REGISTER_POLYMORPHIC_RELATION(Base, Derived)                     \
  namespace cereal {                                                            \
  namespace detail {                                                            \
  template <>                                                                   \
  struct PolymorphicRelation<Base, Derived>                                     \
  { static void bind() { RegisterPolymorphicCaster<Base, Derived>::bind(); } }; \
  } } /* end namespaces */
```

So it seems that you either need to serialize the base class from the derived serialize function, OR you need to use `CEREAL_REGISTER_POLYMORPHIC_RELATION`. I think the documentation should be updated to reflect this.

**Comment by AzothAmmo** [comment]
You are indeed correct that this does not match the current documentation, however `CEREAL_REGISTER_POLYMORPHIC_RELATION` is in develop slated for the next release, and has received updated documentation in the develop gh-pages-develop branch, which will be merged to the main gh-pages when develop is merged to master.

Take a look at this commit and see if the changes are satisfying: https://github.com/USCiLab/cereal/commit/aed084a6ef114d4d03b9daf0404c48fc40549653

**Comment by AzothAmmo** [comment]
Currently no nightly build for develop or the develop doc.
