### ISSUE TITLE
Can't include cereal in my c++ project

### ISSUE THREAD

**Issue by nicolasbotto** [USCiLab/cereal#272]
Hi, I'm including cereal in my c++ project (gcc 4.8.4) and I'm getting compilation errors:

g++    -c -g -I../BridgeDTO -I/home/test/Documents/cereal-1.1.2/include/ -MMD -MP -MF "build/Debug/GNU-Linux/welcome.o.d" -o build/Debug/GNU-Linux/welcome.o welcome.cc
In file included from /usr/include/c++/4.8/type_traits:35:0,
                 from /home/test/Documents/cereal-1.1.2/include/cereal/cereal.hpp:32,
                 from /home/test/Documents/cereal-1.1.2/include/cereal/types/unordered_map.hpp:33,
                 from welcome.cc:11:
/usr/include/c++/4.8/bits/c++0x_warning.h:32:2: error: #error This file requires compiler and library support for the ISO C++ 2011 standard. This support is currently experimental, and must be enabled with the -std=c++11 or -std=gnu++11 compiler options.
 #error This file requires compiler and library support for the \
  ^
In file included from /home/test/Documents/cereal-1.1.2/include/cereal/access.hpp:37:0,
                 from /home/test/Documents/cereal-1.1.2/include/cereal/details/traits.hpp:43,
                 from /home/test/Documents/cereal-1.1.2/include/cereal/cereal.hpp:43,
                 from /home/test/Documents/cereal-1.1.2/include/cereal/types/unordered_map.hpp:33,
                 from welcome.cc:11:
/home/test/Documents/cereal-1.1.2/include/cereal/details/helpers.hpp:59:9: error: expected nested-name-specifier before ‘size_type’
   using size_type = uint64_t;
         ^
Thanks

**Comment by nabijaczleweli** [comment]
`cereal` requires C++11, for which you need to pass `-std=c++11` to `g++`
