### ISSUE TITLE
alignas support in MSVC2013

### ISSUE THREAD

**Issue by AzothAmmo** [USCiLab/cereal#279]
In merging #266 we broke MSVC 2013 builds because [there is no support for alignas](https://msdn.microsoft.com/en-us/library/hh567368.aspx). Will have to put in a small workaround for this. I'd love to start dropping older compilers but I'll save that for a more substantial release. This along with making the new RapidJSON play nicely with MSVC warnings is currently blocking 1.2.

**Comment by stevehickman** [comment]
MSVC2013  also does not support 'noexcept'. See https://msdn.microsoft.com/en-us/library/wfa0edys(v=vs.120).aspx
