### ISSUE TITLE
github.io page renders navbar improperly

### ISSUE THREAD

**Issue by bracketttc** [USCiLab/cereal#289]
The github.io page for this project renders the navbar improperly under Chrome and Firefox on desktop Linux.

![image](https://cloud.githubusercontent.com/assets/19490826/15514289/731134e6-21b6-11e6-9e36-121c82a1b940.png)

**Comment by bracketttc** [comment]
Chrome 50.2661.102 (64-bit) on Fedora 22.
Firefox 46.0.1 on same.

Firefox 43.0.1 on Windows 7 VM renders it fine.

**Comment by nabijaczleweli** [comment]
norepro Win10 FF 48.0a2 (2016-05-21)

**Comment by AzothAmmo** [comment]
I can't reproduce this on any browser I've tried - are you sure this wasn't some network problem?

**Comment by bracketttc** [comment]
It's unsafe script fetching.
I downloaded the page source and it rendered just fine.

You may notice the shield in the far right of the address bar -- that's Chrome refusing to fetch some of Github's scripts because they're being fetched over http instead of https. This is their issue not theirs, and while I never really thought it was your issue per se, I thought that maybe a template change would fix it.

**Comment by bracketttc** [comment]
Github support said that Github pages didn't support https yet, and that no one should be using https on it.
