### ISSUE TITLE
VS2013 does not support 'noexcept'

### ISSUE THREAD

**Issue by stevehickman** [USCiLab/cereal#290]
reference: https://msdn.microsoft.com/en-us/library/wfa0edys(v=vs.120).aspx

Current develop branch contains numerous uses of 'noexcept' which causes compile errors. One possible workaround (See Ivan Ukr's response to this issue on [StackOverflow](http://stackoverflow.com/questions/18387640/how-to-deal-with-noexcept-in-visual-studio )

```
#if !defined(HAS_NOEXCEPT)
#if defined(__clang__)
#if __has_feature(cxx_noexcept)
#define HAS_NOEXCEPT
#endif
#else
#if defined(__GXX_EXPERIMENTAL_CXX0X__) && __GNUC__ * 10 + __GNUC_MINOR__ >= 46 || \
    defined(_MSC_FULL_VER) && _MSC_FULL_VER >= 190023026
#define HAS_NOEXCEPT
#endif
#endif

#ifdef HAS_NOEXCEPT
#define NOEXCEPT noexcept
#else
#define NOEXCEPT
#endif
```

**Comment by nabijaczleweli** [comment]
wrap your code as code kthxbai

**Comment by stevehickman** [comment]
```
#if !defined(HAS_NOEXCEPT)
#if defined(clang)
#if has_feature(cxx_noexcept)
#define HAS_NOEXCEPT
#endif
#else
#if defined(__GXX_EXPERIMENTAL_CXX0X) && GNUC * 10 + GNUC_MINOR >= 46 || \
defined(_MSC_FULL_VER) && _MSC_FULL_VER >= 190023026
#define HAS_NOEXCEPT
#endif
#endif

#ifdef HAS_NOEXCEPT
#define NOEXCEPT noexcept
#else
#define NOEXCEPT
#endif
```

**Comment by patlecat** [comment]
I really don't know why this claim always pops up again and again that MSVC does not support noexcept. It does and has so for quiet some time but with a little known macro:

```
_NOEXCEPT
```

Use this and it'll work fine with older versions of MSVC. :+1:

**Comment by AzothAmmo** [comment]
> Use this and it'll work fine with older versions of MSVC. :+1:

Good to know! Your second sentence contains the answer to the rhetorical question in your first one, by the way.

**Comment by nabijaczleweli** [comment]
He poses not questions, rhethorical or otherwise

**Comment by AzothAmmo** [comment]
Turns out _NOEXCEPT is just a macro for throw(), which is not equivalent to noexcept, so for MSVC2013 we'll continue to compile with no noexcept specifier.
