### ISSUE TITLE
Preventing cereal from serializing portable type information

### ISSUE THREAD

**Issue by jossgray** [USCiLab/cereal#296]
I'm using cereal for serialization to a simple packet format for an existing protocol.

However cereal is prefixing the serialized data with portable type information, which I don't want. I don't need to deserialize polymorphic types.

Is there any way to prevent cereal from writing portable type information?

**Comment by AzothAmmo** [comment]
Am I correct in assuming you are doing something like the following, where you serialize a polymorphic type without using a base pointer?

```cpp
struct A
{
  virtual void hello() {}
  int x;

  template <class Archive>
  void serialize( Archive & ar )
  {
    ar( x );
  }
};

struct B : A
{
  void hello() {}

  template <class Archive>
  void serialize( Archive & ar )
  {
    ar( cereal::base_class<A>( this ) );
  }
};

CEREAL_REGISTER_TYPE(B)

int main()
{
  std::stringstream ss;
  {
    cereal::JSONOutputArchive ar( ss );
    std::shared_ptr<B> ptr = std::make_shared<B>();

    ar( ptr );
  }
}
```

**Comment by jossgray** [comment]
No I am trying to serialize a base pointer to a derived type. I just don't need the type information serialized.

```
struct Base
{
    virtual const char* type() { return "Base"; }
};

struct Derived : public Base
{
    int foo;

    const char* type() override { return "Derived"; }

    template <class Archive>
    void serialize(Archive& ar)
    {
        ar(CEREAL_NVP(foo));
    }
};

CEREAL_REGISTER_TYPE(Derived);
 
int main()
{
    auto derived = std::make_shared<Derived>();
    derived->foo = 1;

    auto base = std::static_pointer_cast<Base>(derived);

    std::stringstream ss;
    {
        cereal::CitpOutputArchive oarchive(ss);
        oarchive(base);
    }
}
```
cereal::CitpOutputArchive is my custom archive. I will just serialize POD types to binary, the same way as cereal::BinaryOutputArchive.

So serializing `base` should result in 4 bytes containing `0x00000001`.

**Comment by AzothAmmo** [comment]
If you are using a base pointer to a derived polymorphic class, cereal needs that type information to perform the load - otherwise it can't determine the proper routing for the serialization function. I'm still trying to understand the use case here - you say you don't need to deserialize this data in your original post, so why is it even serialized?

**Comment by jossgray** [comment]
I'm using my own cereal archive for serialization for this protocol, [CITP](https://bitbucket.org/lars_wernlund/citp/downloads/master%202016-05-26.pdf).

My archive type supports serialization for the types defined in that spec. There are lots of packet types so I would rather use a base class to perform the serialization generically. In this particular case I can deserialize the headers first to find you what is the correct packet type to deserialize.

To be honest, I can just use a template function to do this, I was mainly interested if there was a way to do this.

**Comment by jossgray** [comment]
I think I can do what I want by writing a custom serialization function for shared_ptr, unique_ptr, etc.

**Comment by AzothAmmo** [comment]
There isn't a built in way of easily turning off this functionality, so writing a custom serialization function specialized for your archives is the right approach.
