### ISSUE TITLE
Lots of problems building

### ISSUE THREAD

**Issue by rix0rrr** [USCiLab/cereal#301]
I'm having lots of trouble building the project (the tests, obviously). Mostly I'm having a variation of the following issues, on various versions of GCC (mostly 4.9.x editions) and various Boosts (1.55, 1.60, 1.61). 

Looks like the same issue but with different error messages depending on the exact combination of compiler and Boost version. First off (very similar error on all Boosts):

    In file included from project/Dev/3rdparty/boost/boost_1_61_0/boost/test/test_tools.hpp:46:0,
                    from project/Dev/3rdparty/boost/boost_1_61_0/boost/test/unit_test.hpp:18,
                    from project/Workspaces/Bogart/src/Cereal/third-party-src/unittests/unordered_set.cpp:28:
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/old/impl.hpp: In instantiation of ‘boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl(const Left&, const Right&) [with Left = long unsigned int; Right = int]’:
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/old/impl.hpp:130:40:   required from ‘boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::call_impl(const Left&, const Right&, mpl_::false_) const [with Left = long unsigned int; Right = int; mpl_::false_ = mpl_::bool_<false>]’
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/old/impl.hpp:145:56:   required from ‘boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_impl_frwd::operator()(const Left&, const Right&) const [with Left = long unsigned int; Right = int]’
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/old/impl.hpp:92:1:   required from ‘bool boost::test_tools::tt_detail::check_frwd(Pred, const boost::unit_test::lazy_ostream&, boost::unit_test::const_string, std::size_t, boost::test_tools::tt_detail::tool_level, boost::test_tools::tt_detail::check_type, const Arg0&, const char*, const Arg1&, const char*) [with Pred = boost::test_tools::tt_detail::equal_impl_frwd; Arg0 = long unsigned int; Arg1 = int; boost::unit_test::const_string = boost::unit_test::basic_cstring<const char>; std::size_t = long unsigned int]’
    project/Workspaces/Bogart/src/Cereal/third-party-src/unittests/unordered_set.cpp:88:7:   required from ‘void test_unordered_set() [with IArchive = cereal::BinaryInputArchive; OArchive = cereal::BinaryOutputArchive]’
    project/Workspaces/Bogart/src/Cereal/third-party-src/unittests/unordered_set.cpp:115:79:   required from here
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/old/impl.hpp:107:17: error: comparison between signed and unsigned integer expressions [-Werror=sign-compare]
        return left == right;

I get around this by adding `-Wno-sign-compare` to CXXFLAGS, feeling dirty doing that. Then, the next error on Boost 1.61:

    In file included from project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/floating_point_comparison.hpp:21:0,
                    from project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/old/impl.hpp:21,
                    from project/Dev/3rdparty/boost/boost_1_61_0/boost/test/test_tools.hpp:46,
                    from project/Dev/3rdparty/boost/boost_1_61_0/boost/test/unit_test.hpp:18,
                    from project/Workspaces/Bogart/src/Cereal/third-party-src/unittests/map.cpp:28:
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/detail/print_helper.hpp: In instantiation of ‘struct boost::test_tools::tt_detail::print_log_value<std::pair<const std::basic_string<char>, int> >’:
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/detail/print_helper.hpp:178:40:   required from ‘std::ostream& boost::test_tools::tt_detail::operator<<(std::ostream&, const boost::test_tools::tt_detail::print_helper_t<T>&) [with T = std::pair<const std::basic_string<char>, int>; std::ostream = std::basic_ostream<char>]’
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/utils/wrap_stringstream.hpp:66:19:   required from ‘boost::basic_wrap_stringstream<CharT>& boost::operator<<(boost::basic_wrap_stringstream<CharT>&, const T&) [with CharT = char; T = boost::test_tools::tt_detail::print_helper_t<std::pair<const std::basic_string<char>, int> >]’
    project/Dev/3rdparty/boost/boost_1_61_0/boost/test/tools/old/impl.hpp:212:19:   required from ‘boost::test_tools::assertion_result boost::test_tools::tt_detail::equal_coll_impl::operator()(Left, Left, Right, Right) [with Left = std::_Rb_tree_iterator<std::pair<const std::basic_string<char>, int> >; Right = std::_Rb_tree_iterator<std::pair<const std::basic_string<char>, int> >]’
    project/Workspaces/Bogart/src/Cereal/third-party-src/unittests/map.cpp:106:5:   required from ‘void test_map() [with IArchive = cereal::BinaryInputArchive; OArchive = cereal::BinaryOutputArchive]’
    project/Workspaces/Bogart/src/Cereal/third-party-src/unittests/map.cpp:170:69:   required from here
    project/Dev/3rdparty/boost/boost_1_61_0/boost/static_assert.hpp:31:45: error: static assertion failed: Type has to implement operator<< to be printable
    #     define BOOST_STATIC_ASSERT_MSG( ... ) static_assert(__VA_ARGS__)

In other Boosts I get roughly the same error, except then it's just about that no correct specialization can be found for `std::ostream << std::pair(std::string, VARIOUS TYPES HERE)`.

This is all on Linux. It does seem to build properly on Clang and whatever Boost I happen to have on my MacBook, probably also a recent one (1.60, 1.61).

Any help would be greatly appreciated.

**Comment by AzothAmmo** [comment]
Have you tried using the develop branch? Your issue sounds like #295.
