### ISSUE TITLE
Boost gregorian date object serialization with cereal

### ISSUE THREAD

**Issue by rcdailey** [USCiLab/cereal#304]
Does cereal not attempt to use `operator<<` and `operator>>` defined by other libraries for their own types? Very simple code I have does not compile:

```
#include <string>
#include <boost/date_time/gregorian/gregorian.hpp> // also includes gregorian_io.hpp

class SubmissionInfo
{
public:
   template<typename Archive>
   void serialize(Archive& ar)
   {
      ar(guid, submission_date);
   }

   std::string guid;
   boost::gregorian::date submission_date;
};

int main()
{
   std::ofstream output_file{"C:\\output.xml"};
   cereal::XMLOutputArchive archive(output_file);
   SubmissionInfo info;
   info.serialize(archive);
}
```

This will not compile because it says there is no serialize() function for it. However, it shouldn't be using that but instead `operator<<` provided by boost.

How am I supposed to get this working?

**Comment by AzothAmmo** [comment]
Your code does not define (and neither would boost) a serialization function for `boost::gregorian::date`. cereal does not use iostream overloads of `operator<<` to perform serialization. Take a look at the documentation on the main website which covers the general way cereal operates.

For your example, you would need to define external serialization functions for `boost::gregorian::date` in a fashion similar to the way we do for types in the standard library, something like:

```cpp
namespace cereal
{
  template <class Archive>
  void serialize( Archive & ar, boost::gregorian::date & date )
  {
    // somehow serialize the date 
  }
}

**Comment by rcdailey** [comment]
I did read the documentation and I understand the different serialization functions I have the option of overloading. However, I was assuming that you also handled iostream operators since they are pretty universal.

Is this a good solid solution?

```

namespace boost { namespace gregorian
{
   template<typename Archive>
   std::string save_minimal(Archive const&, date const& dt)
   {
      return to_iso_string(dt);
   }

   template<typename Archive>
   void load_minimal(Archive const&, date& dt, std::string const& value)
   {
      dt = from_iso_string(value);
   }
}}
```

**Comment by AzothAmmo** [comment]
That looks like a pretty good solution.

**Comment by romanwerpachowski** [comment]
Does it handle special values?
