### ISSUE TITLE
Google groups email address not working

### ISSUE THREAD

**Issue by LumpBloom7** [USCiLab/cereal#305]
I tried to send an email to the email address located on the documentation webpage. But Google gave me a reply saying that the message failed to send. Below are the contents of the email.

From: Mail Delivery Subsystem
Sent: Thursday, June 23, 15:28
Subject: Delivery Status Notification (Failure)
To: derrick.timmermans@outlook.com

Hello derrick.timmermans@outlook.com, We're writing to let you know that the group you tried to contact (cerealcpp) may not exist, or you may not have permission to post messages to the group. A few more details on why you weren't able to post: * You might have spelled or formatted the group name incorrectly. * The owner of the group may have removed this group. * You may need to join the group before receiving permission to post. * This group may not be open to posting. If you have questions related to this or any other Google Group, visit the Help Center at https://groups.google.com/support/. Thanks, Google Groups ----- Original message ----- X-Received: by 10.176.3.144 with SMTP id 16mr35725959uau.12.1466666891599; Thu, 23 Jun 2016 00:28:11 -0700 (PDT) Return-Path: Received: from SNT004-OMC2S8.hotmail.com (snt004-omc2s8.hotmail.com. [65.55.90.83]) by gmr-mx.google.com with ESMTPS id d63si511491ith.0.2016.06.23.00.28.11 for (version=TLS1_2 cipher=ECDHE-RSA-AES128-SHA bits=128/128); Thu, 23 Jun 2016 00:28:11 -0700 (PDT) Received-SPF: pass (google.com: domain of derrick.timmermans@outlook.com designates 65.55.90.83 as permitted sender) client-ip=65.55.90.83; Authentication-Results: gmr-mx.google.com; dkim=pass header.i=@outlook.com; spf=pass (google.com: domain of derrick.timmermans@outlook.com designates 65.55.90.83 as permitted sender) smtp.mailfrom=derrick.timmermans@outlook.com; dmarc=pass (p=NONE dis=NONE) header.from=outlook.com Received: from APC01-SG2-obe.outbound.protection.outlook.com ([65.55.90.71]) by SNT004-OMC2S8.hotmail.com over TLS secured channel with Microsoft SMTPSVC(7.5.7601.23008); 	 Thu, 23 Jun 2016 00:28:10 -0700 DKIM-Signature: v=1; a=rsa-sha256; c=relaxed/relaxed; d=outlook.com; s=selector1; h=From:Date:Subject:Message-ID:Content-Type:MIME-Version; bh=mvQS/LCd1n82sZsOsYIbQt+rQJM/ytmqCDvoO+7nsRw=; b=q1Ee6Ax9CmlP1IZQgn4UTi19+hupGXQ2MSXwHm2ZdeWK/ZHb5WDMKTMsuPbSyn2s3jaIhB1la4+3A9GE3F/bfr0+zig8mmmZ2O73T+pfYTnlzCY5pC5AZKu1EK1N0acJKDGex/XhZTFvD8w/bpxh/3J/z7YeCoICioSTAz64jYCpLS7bQaq4+rbv4EYLtZSa2K6WaSsJFDQ0PYg2muF3L9FSa1l+jGoknG5bLY5UfBRwxbojgDoot3sJwBGSmB2RmajLFy/oZLYkh2a6JuPmN473d064i18ZLP7eKsuER197yqkZ95/+QaMAefL4jx/vT7/GkHcN8HZ7TU5qvR3DNw== Received: from PU1APC01FT114.eop-APC01.prod.protection.outlook.com (10.152.252.57) by PU1APC01HT216.eop-APC01.prod.protection.outlook.com (10.152.253.166) with Microsoft SMTP Server (TLS) id 15.1.511.7; Thu, 23 Jun 2016 07:28:00 +0000 Received: from HK2PR04MB1201.apcprd04.prod.outlook.com (10.152.252.52) by PU1APC01FT114.mail.protection.outlook.com (10.152.252.228) with Microsoft SMTP Server (TLS) id 15.1.511.7 via Frontend Transport; Thu, 23 Jun 2016 07:28:00 +0000 Received: from HK2PR04MB1201.apcprd04.prod.outlook.com ([10.165.60.15]) by HK2PR04MB1201.apcprd04.prod.outlook.com ([10.165.60.15]) with mapi id 15.01.0523.015; Thu, 23 Jun 2016 07:27:59 +0000 From: Derrick Timmermans To: "cerealcpp@googlegroups.com" Subject: Serializing contents of pointers Thread-Topic: Serializing contents of pointers Thread-Index: AQHRzSAln5p4H8FrDUy/5oJ+F0WsKA== Date: Thu, 23 Jun 2016 07:27:59 +0000 Message-ID: Accept-Language: en-US Content-Language: en-US X-MS-Has-Attach: X-MS-TNEF-Correlator: authentication-results: spf=softfail (sender IP is 25.152.252.52) smtp.mailfrom=outlook.com; googlegroups.com; dkim=none (message not signed) header.d=none;googlegroups.com; dmarc=fail action=none header.from=outlook.com; received-spf: SoftFail (protection.outlook.com: domain of transitioning outlook.com discourages use of 25.152.252.52 as permitted sender) x-ms-exchange-messagesentrepresentingtype: 1 x-tmn: [47BHVd4yS8MCG4132OgkrGutQzYjAsUU] x-eopattributedmessage: 0 x-forefront-antispam-report: CIP:25.152.252.52;IPV:NLI;CTRY:GB;EFV:NLI;SFV:NSPM;SFS:(10019020)(98900003);DIR:OUT;SFP:1102;SCL:1;SRVR:PU1APC01HT216;H:HK2PR04MB1201.apcprd04.prod.outlook.com;FPR:;SPF:None;LANG:en; x-ms-office365-filtering-correlation-id: 21d47905-7f18-45a3-3df2-08d39b37e77f x-microsoft-antispam: UriScan:;BCL:0;PCL:0;RULEID:(1601124038)(5061506196)(5061507196)(1603103041)(1601125047);SRVR:PU1APC01HT216; x-exchange-antispam-report-cfa-test: BCL:0;PCL:0;RULEID:(432015012)(82015046);SRVR:PU1APC01HT216;BCL:0;PCL:0;RULEID:;SRVR:PU1APC01HT216; x-forefront-prvs: 098291215C Content-Type: multipart/alternative; 	boundary="_000_HK2PR04MB1201AE8D9A94F40E8C90550D892D0HK2PR04MB1201apcp_" MIME-Version: 1.0 X-OriginatorOrg: outlook.com X-MS-Exchange-CrossTenant-originalarrivaltime: 23 Jun 2016 07:27:59.7863 (UTC) X-MS-Exchange-CrossTenant-fromentityheader: Internet X-MS-Exchange-CrossTenant-id: 84df9e7f-e9f6-40af-b435-aaaaaaaaaaaa X-MS-Exchange-Transport-CrossTenantHeadersStamped: PU1APC01HT216 Return-Path: derrick.timmermans@outlook.com X-OriginalArrivalTime: 23 Jun 2016 07:28:11.0202 (UTC) FILETIME=[CBC88A20:01D1CD20]

**Comment by AzothAmmo** [comment]
You may need to register as a member of the group before you can post to it via email.
