### ISSUE TITLE
Warning in portable_binary.hpp

### ISSUE THREAD

**Issue by M2tM** [USCiLab/cereal#306]
C:\git\external\cereal\include\cereal/archives/portable_binary.hpp(238): warning C4805: '^': unsafe mix of type 'bool' and type 'uint8_t' in operation

I'm getting this on the following line in cereal:

`itsConvertEndianness = options.is_little_endian() ^ streamLittleEndian;`

With Visual Studio 15 preview 2.  Though I believe I was also getting it with VS 2015.

**Comment by AzothAmmo** [comment]
Related to 74da9b6b2aaffe78e980bf06527de4395cb9fcc3

**Comment by M2tM** [comment]
Thanks, this is the only warning in my project so it sticks out like a sore thumb :) :+1:
