### ISSUE TITLE
Deserializing from non-stream types

### ISSUE THREAD

**Issue by sansumbrella** [USCiLab/cereal#316]
I am passing data over a network connection and using Cereal to serialize/deserialize it for transmission. On the receiving end, the data arrives in a contiguous buffer, not a stream. In order to create a stream interface to the data, I need to copy it at least twice: once into a string, then again into the stringstream.

```
auto str = string(dataPtr, dataSize); // copies the data
auto stream = stringstream(str);      // copies the data
cereal::PortableBinaryInputArchive ar(stream);
```

Ideally, I would be able to write something like the following, that doesn't make a copy of the underlying data:
```
auto stream = streamView(dataPtr, dataSize); // wrap memory in a stream interface without copying
cereal::ProtableBinaryInputArchive ar(stream);
```

Are there facilities in Cereal for handling this kind of behavior? If not, can you recommend an approach to writing custom streams to pass into Cereal?

**Comment by erichkeane** [comment]
There isn't really anything built-in from what I can see, and (sadly) the first parameter is of type std::istream rather than being templated.

You'd have to implement a stream type that inherits from istream it seems, but there is only a handful of functions you'd have to implement: http://en.cppreference.com/w/cpp/io/basic_istream

**Comment by sansumbrella** [comment]
Thanks Erich. I did some further searching and found an approach that works well for me.

I [detailed](http://discourse.libcinder.org/t/create-a-stringstream-from-cinder-buffer-avoiding-copying/153/5) my solution on the Cinder forums, since that's where I originally sought help (using the OSC library from there).

Essentially: inherit from streambuf so you can set the buffer's pointers to the memory of your choosing. Then create a stream that points to your custom buffer.

**Comment by AzothAmmo** [comment]
I want to point out that the requirement of a using either an `ostream` or `istream` object is only at the level of the archive - the core parts of cereal are agnostic to what the archive chooses to do with low level data.

Your facade is one solution. Another would be to write your own archive (basically copy `PortableBinaryArchive) and swap out the streams for buffers.

For a future release having a generic option would be pretty cool.

**Comment by erichkeane** [comment]
I was thinking about how we could template it.  it would be a pretty minor change, though I suspect it would be a compiled-breaking change (though we could make it a default parameter, making this not break code before that).

Thoughts?
