### ISSUE TITLE
What happen if I try to serialize raw pointer?

### ISSUE THREAD

**Issue by kwanti** [USCiLab/cereal#33]
In the documentation, it said that raw pointer serialization is not supported because it get complicated tracking raw pointer.  What happen if I try serialize raw pointer?  Will it be compile error or it will still serialize the pointer without tracking?

If you don't mind to answer my ignorant question about the documented rationale, why tracking and not memory management is the main issue in serializing raw pointer since cereal already implemented object tracking for smart pointer?

I would like to try cereal to replace boost serialization in my project but not supporting raw pointer will reduce many of the use cases in my project.

**Comment by daniilsavchenko** [comment]
Ok, but what about pair unique_ptr/raw pointers (like shared_ptr and weak_ptr). Yes, it is always possible exchange unique_ptr/raw, by shared_ptr/weak_ptr, but in some application it’s not reasonable, and do it only for using serialization library is strange. In our case it will be main issue while transition from boost. In this case (raw pointer data always owned by unique_ptr) serialization code wouldn't be more complex than in weak_ptr case.
Yes, it will require attention from user: he has to be sure, that raw pointer points to data, owned by unique_ptr, and doesn’t point to object allocated on the stack and serialized by value. Now, he simply has o compilation error. But it could be organized by global library flag (maybe macros ENABLED_RAW_BROTHERS_FOR_UNIQUE) or by special «keyword» in save/load function ( ar( RAW_PTR( f ) ) or ar( raw_ptr<T>( p ) ) and it’s a guarantee that the user understands what he does and what are the limitations. I think this could make cereal more helpful and simple for using for great number of users.

**Comment by dpservis** [comment]
Bumped onto this playing with cereal. It is a significant limitation because there is no reason for code not to use pointers. It is actually something that can be solved (I have done it in the past): define a shared_ptr with no-op destructor; track like all the other pointers but when deserializing allocate the object with new.
