### ISSUE TITLE
Crash if setting CEREAL_THREAD_SAFE=1 with polymorphic class  

### ISSUE THREAD

**Issue by TalH-Vayyar** [USCiLab/cereal#331]
Run the polymorphic example (from: http://uscilab.github.io/cereal/polymorphism.html)
with `CEREAL_THREAD_SAFE=1`. #320 

The result crash on init at (polymorphic_impl.hpp line 413)
`auto lock = StaticObject<InputBindingMap<Archive>>::lock();`

**Comment by erichkeane** [comment]
What compiler are you running, and which example exactly?  I just ran "Header registration Example" and "Registration Example" on gcc 4.8 with CEREAL_THREAD_SAFE defined, and had no issue.

**Comment by TalH-Vayyar** [comment]
I'm running visual studio 2015 with the "Header registration example".
it also fails without any code in the main() function.
as a workaround I've comment out the call tot he lock function at polymorphic_impl.hpp 
`// auto lock = StaticObject<InputBindingMap<Archive>>::lock();`
at it didn't fail.

**Comment by TalH-Vayyar** [comment]
-

**Comment by TalH-Vayyar** [comment]
I'm running visual studio 2015 with the "Header registration example".
it also fails without any code in the main() function.
as a workaround I've comment out the call tot he lock function at polymorphic_impl.hpp 
`// auto lock = StaticObject<InputBindingMap<Archive>>::lock();`
at it didn't fail.

**Comment by AzothAmmo** [comment]
I'll look into this next time I'm able to run on MSVC2015.

**Comment by AzothAmmo** [comment]
Just to update: my Windows computer is going through some kind of hard drive disk/controller failure so it may be a little while before I get a chance to look at this properly.

**Comment by darioizzo** [comment]
Any news on this? We are planning to use cereal while developing a highly multithreaded library and these bugs would be a showstopper for us ....

**Comment by TalH-Vayyar** [comment]
I see a fix for the issue, yet  I didn’t test ( my workaround is good enough for me).
Please note that in multithreaded environment each thread should work on its own file.

**Comment by darioizzo** [comment]
Ok, thanks. We would prefer a stable solution merged into master as a workaround could reveal to be backfiring in the long run ....

**Comment by TalH-Vayyar** [comment]
Sure
