### ISSUE TITLE
load_and_construct with explicit versioning not documented

### ISSUE THREAD

**Issue by erichkeane** [USCiLab/cereal#334]
See here: https://groups.google.com/forum/?utm_medium=email&utm_source=footer#!msg/cerealcpp/Sj2hBcR-2hM/tjhNBRM3BAAJ

The load_and_construct with versioning isn't documented here: http://uscilab.github.io/cereal/pointers.html

I didn't see where this documentation is, so I wasn't able to figure out how to change that site.

**Comment by AzothAmmo** [comment]
I originally forgot to do versioning for load_and_construct so it was patched in later (#216). I'll add it to the docs (the public facing docs are on the gh-pages branch, WIP docs on the gh-pages-develop branch).

**Comment by AzothAmmo** [comment]
Added, also note that the doxygen covers this as well.
