### ISSUE TITLE
test_portable_binary_archive fails on Fedora i686

### ISSUE THREAD

**Issue by junghans** [USCiLab/cereal#338]
On Fedora i686, test_portable_binary_archive is broken in v1.2.1:
http://koji.fedoraproject.org/koji/taskinfo?taskID=15459296

**Comment by AzothAmmo** [comment]
I don't have any easy way to reproduce this at the moment, are you able to debug this a bit more? Even just running that test in isolation could be helpful. My guess is that this related to using a 32 bit architecture.

**Comment by junghans** [comment]
The `test_portable_binary_archive` is still unstable.
This time on OpenSuse: [log](https://github.com/USCiLab/cereal/files/778333/_log.txt)

**Comment by AzothAmmo** [comment]
Can you see if the latest develop branch resolves this? It looks like it was just due to a copy/paste typo in the unit test.

**Comment by junghans** [comment]
Ok, I will patch 8b8f5814e292e03bb5b07333a0e634ef0481c85b in!

**Comment by junghans** [comment]
Seems to be fixed in v1.3.0.
