### ISSUE TITLE
macOS <= 10.9: error: chosen constructor is explicit in copy-initialization

### ISSUE THREAD

**Issue by ilovezfs** [USCiLab/cereal#339]
The following is a regression from cereal 1.1.2, which does not have this problem.

Full build log: https://gist.github.com/ilovezfs/43068bcbd2aaf678017fbf88f7f62d5c

When trying to build cereal 1.2.1 or the develop branch @ 1e5e6489189c52153f3a197f8bf7c7693ea30902 on macOS <= 10.9 the build fails with

```
/tmp/cereal-20160903-81215-l0wzgn/./include/cereal/details/polymorphic_impl.hpp:227:61: error: chosen constructor is explicit in copy-initialization
          auto & derivedMap = baseMap.insert( lb, {baseKey, {}} )->second;
                                                            ^~
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/map:838:14: note: constructor declared here
    explicit map(const key_compare& __comp = key_compare())
             ^
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/../lib/c++/v1/utility:262:37: note: passing argument to parameter '__y' here
    pair(const _T1& __x, const _T2& __y)

```

This does not affect macOS 10.10 or 10.11.

**Comment by AzothAmmo** [comment]
Sounds like whatever version of clang Apple is using there has an explicit default constructor for `map`. Try this and see if it fixes the problem:

Replace line 227 with:

```cpp
auto & derivedMap = baseMap.insert( lb, {baseKey, std::map<std::type_index, std::vector<PolymorphicCaster const*>>{}} )->second;
```

I don't have any way of easily testing this myself so if you have to play around to get this to work let me know what had to change.

**Comment by jasperges** [comment]
Today I also encountered this issue and after replacing the line like you suggested it worked fine. Thanks.

**Comment by headupinclouds** [comment]
I encountered the same issue with with a clang-3.8 + libc++ build on an Ubuntu Trusty machine.  Are there any objections to a PR with the above fix https://github.com/USCiLab/cereal/issues/339#issuecomment-246166717 

```
auto & derivedMap = baseMap.insert( lb, {baseKey, std::map<std::type_index, std::vector<PolymorphicCaster const*>>{}} )->second;
```

**Comment by headupinclouds** [comment]
I believe this was addressed here: https://github.com/USCiLab/cereal/commit/fcef0da01a07cca054caf25a2eeddeb5114a7b52#commitcomment-23652411

**Comment by headupinclouds** [comment]
I've tested the fix from develop and it works fine.  I believe this issue can be closed.

**Comment by ilovezfs** [comment]
Thanks!
