### ISSUE TITLE
How to use string for serializing/deserializing enum classes

### ISSUE THREAD

**Issue by Shelim** [USCiLab/cereal#344]
Hello,

Is there any way to serialize enum class values as strings (even with overhead on speed/space) with text based output? I am actually outputting XML which should be human-readable, and values like "42" all over the place are not...

Regards

**Comment by erichkeane** [comment]
Implement a serialize function for the enum.

**Comment by Shelim** [comment]
Thanks, it works this way!

If you come here from google, here is the code:

`enum class log_level_t
{
	message,
	warning,
	error
};
template <class Archive> std::string save_minimal(Archive const &, log_level_t const & obj)
{
	switch (obj)
	{
		case log_level_t::message: return "message";
		case log_level_t::warning: return "warning";
		case log_level_t::error: return "error";
	}
	return "message"; // Default value
}

template <class Archive> void load_minimal(Archive const &, log_level_t & obj, std::string const & value)
	{
		if (value == "message") obj = log_level_t::message;
		else if (value == "warning") obj = log_level_t::warning;
		else if (value == "error") obj = log_level_t::error;
		else obj = log_level_t::message; // Default value
	}
`
