### ISSUE TITLE
Compile error in test_polymorphic

### ISSUE THREAD

**Issue by hide-ikeno** [USCiLab/cereal#349]
Hi,

I met an error when compiling the `test_polymorphic`. 
I used clang++ on Mac OSX as shown below:

- OS: Mac OS X El-Capitan
- Compiler: Apple LLVM version 8.0.0 (clang-800.0.38)
- Target: x86_64-apple-darwin15.6.0
- Thread model: posix

The corresponding error message is as follows: 

```
${BUILD_DIR}/include/cereal/types/memory.hpp:304:15: error: destructor called on
     non-final 'PolyDerivedLA' that has virtual functions but non-virtual destructor [-Werror,-Wdelete-non-virtual-dtor]
              t->~T();
              ^
```

Could you fix it?

**Comment by AzothAmmo** [comment]
Should be fixed on develop, let me know if it persists.
