### ISSUE TITLE
Clearing Archives

### ISSUE THREAD

**Issue by kklouzal** [USCiLab/cereal#350]
How can an input/output archive be cleared so it can be reused?

In a network environment where Cereal is serializing packets lots of input/archives may be getting created and subsequently destroyed many times over during short periods of time.

Is there a way to clear an archive so they can effectively be cached and reused?

**Comment by AzothAmmo** [comment]
None of the current cereal archives are designed to be used in that manner. They all operate with an assumption that they are created prior to serialization and destroyed afterwards. Even though, for example, the binary archives immediately serialize data, they still maintain state relevant to serialization (e.g. shared pointer addresses, polymorphic type information) that is specific for the data being serialized.

You could modify the behavior of archives to achieve what you want, but you'd have to do it at your own discretion and ensure that everything still worked properly. A starting point would be the base archives, defined in cereal.hpp.

**Comment by kklouzal** [comment]
Okay and I apologize if I've asked this similar type of question before.
I was looking at different places to shave small bits of processing time, I'll cross this one off my list.
Thank you for the answer though! 👍
