### ISSUE TITLE
Fixed number of digits after the decimal point

### ISSUE THREAD

**Issue by gncs** [USCiLab/cereal#358]
How can I ensure that doubles have a certain number of digits after the decimal point.

When I run the following code,
```
std::stringstream ss;
{
  double d = 1.0;

  ss.setf(std::ios::fixed, std::ios::floatfield);
  ss << "Manual: " << d << std::endl;

  ss << "Cereal: ";
  cereal::JSONOutputArchive archive(ss);
  archive(cereal::make_nvp("d", d));
}
std::cout << ss.str();
```
I get:
```
Manual: 1.000000
Cereal: {
    "d": 1
}
```

The reason why I am asking is that I want to save this JSON to a MongoDB database, which interprets `"d": 1` as an integer, which is not what I want.

Thank you very much! :)

**Comment by AzothAmmo** [comment]
Sorry for the late response, but which compiler/OS are you using? This is the output I get on Ubuntu/g++5.3:

```
Manual: 1.000000
Cereal: {
    "d": 1.0
}
```

**Comment by gncs** [comment]
Thank  you for your reply. I have had another look at it and identified the problem. The problem was caused by the inclusion of headers from another project (mangrove) which uses cereal, too, but has its own copy.
Thank you for your help!
