### ISSUE TITLE
SIGSEGV in JSONInputArchive::operator() for "{}" stream

### ISSUE THREAD

**Issue by hlohse** [USCiLab/cereal#359]
The following example leads to a SIGSEGV when calling `iarchive(*this);` in line 14. This occurs in v1.2.1, but did not in v1.1.2, where an exception got thrown.

<pre>
#include <cereal/archives/json.hpp>
#include <cereal/cereal.hpp>
#include <string>
#include <sstream>

struct Example {
  int member{0};

  void parseFrom(const std::string& json) {
    std::stringstream ss;
    ss.str(json);
    {
      cereal::JSONInputArchive iarchive(ss);
      iarchive(*this);
    }
  }
};

template <class Archive>
void serialize(Archive& archive, Example& example) {
  archive(cereal::make_nvp("member", example.member));
}

int main(int argc, char* argv[]) {
  Example example;
  example.parseFrom("{}");
  return 0;
}
</pre>

Stack trace:

<pre>
Program received signal SIGSEGV, Segmentation fault.
0x0007c262 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::IsArray (this=0x10)
    at /opt/x-tools/arm-socfpga-linux-gnueabi/arm-socfpga-linux-gnueabi/sysroot/usr/include/cereal/external/rapidjson/document.h:942
942     /opt/x-tools/arm-socfpga-linux-gnueabi/arm-socfpga-linux-gnueabi/sysroot/usr/include/cereal/external/rapidjson/document.h: No such file or directory.
(gdb) bt
#0  0x0007c262 in rapidjson::GenericValue<rapidjson::UTF8<char>, rapidjson::MemoryPoolAllocator<rapidjson::CrtAllocator> >::IsArray (this=0x10)
    at /opt/x-tools/arm-socfpga-linux-gnueabi/arm-socfpga-linux-gnueabi/sysroot/usr/include/cereal/external/rapidjson/document.h:942
#1  0x0009485c in cereal::JSONInputArchive::startNode (this=0x7efff768) at /opt/x-tools/arm-socfpga-linux-gnueabi/arm-socfpga-linux-gnueabi/sysroot/usr/include/cereal/archives/json.hpp:574
#2  0x000bd730 in cereal::prologue<cdk::hmi::Request, (cereal::traits::detail::sfinae)0> (ar=...)
    at /opt/x-tools/arm-socfpga-linux-gnueabi/arm-socfpga-linux-gnueabi/sysroot/usr/include/cereal/archives/json.hpp:795
#3  0x000bcfae in cereal::InputArchive<cereal::JSONInputArchive, 0u>::process<cdk::hmi::Request&> (this=0x7efff768, head=...)
    at /opt/x-tools/arm-socfpga-linux-gnueabi/arm-socfpga-linux-gnueabi/sysroot/usr/include/cereal/cereal.hpp:701
#4  0x000bc54a in cereal::InputArchive<cereal::JSONInputArchive, 0u>::operator()<cdk::hmi::Request&> (this=0x7efff768)
    at /opt/x-tools/arm-socfpga-linux-gnueabi/arm-socfpga-linux-gnueabi/sysroot/usr/include/cereal/cereal.hpp:605
</pre>

**Comment by AzothAmmo** [comment]
You are getting a segfault because the input JSON you are providing is not what cereal is expecting - we should probably be catching this and giving you a better error, however. 

cereal is expecting input like this for your example class:

```json
{
    "value0": {
        "member": 0
    }
}
```

**Comment by AzothAmmo** [comment]
With the latest develop we'll now throw an exception that looks like this:

```
terminate called after throwing an instance of 'cereal::Exception'
  what():  JSONInputArchive internal error: null or empty iterator to object or array!
Aborted (core dumped)
```

**Comment by hlohse** [comment]
Thanks for your quick reaction!
