### ISSUE TITLE
Archive::{is_loading,is_saving}::value

### ISSUE THREAD

**Issue by headupinclouds** [USCiLab/cereal#360]
Is the following {`is_loading`,`is_saving`} type addition compatible with the cereal library?  This would greatly improve compatibility with existing boost serialization code and is seemingly unobtrusive.

```
template<class ArchiveType, std::uint32_t Flags = 0>
  class OutputArchive : public detail::OutputArchiveBase
{
  public:
    typedef bool_<false> is_loading;  // <- proposal
    typedef bool_<true> is_saving;     // <- proposal
   // ...
};
```

This supports the following serialization pattern:

```
struct Bar
{
    template <typename Archive> void serialize(Archive &ar, const std::uint32_t version)
    {
        std::int16_t tmp = foo;
        if(Archive::is_loading::value)
        {
            ar & tmp;
            foo = tmp; // For illustration only
        }
        else
        {
            tmp = foo; // For illustration only
            ar & tmp;
        }
        ar & foo;
    }
    std::int32_t foo;
};
```

**Comment by AzothAmmo** [comment]
You can actually already get this information by simply using `std::is_base_of` with the archive and either `cereal::detail::InputArchiveBase` or `cereal::detail::OutputArchiveBase`, though I suspect what you are after is identical syntax to boost.

The best place to add this to cereal would be in `cereal.hpp` to the `InputArchive` and `OutputArchive` classes, something along the lines of

```cpp
using is_loading = std::true_type;
using is_saving  = std::false_type;
```

as appropriate, defined within the doxygen block for the `Boost Transition Layer`

If you choose to do a pull request adding this to cereal, please do so against the current develop branch and also include appropriate doxygen comments for the new values.

**Comment by headupinclouds** [comment]
Thanks for the quick feedback (and a great library).  I will put together a PR over the holiday.  Having this change upstream will greatly simplify a boost -> cereal transition.

**Comment by AzothAmmo** [comment]
PR merged.
