### ISSUE TITLE
stdint.h nested deep in the "external" folder in the cereal package if for MSVC only

### ISSUE THREAD

**Issue by astoeckley** [USCiLab/cereal#362]
I'm compiling on a Mac for iOS, and per the instructions I dropped the entire cereal directory into my header path, but the stdint.h file in that external directory won't compile because of this:

```
#ifndef _MSC_VER // [
#error "Use this header only with Microsoft Visual C++ compilers!"
#endif // _MSC_VER ]
```

I have used cereal on Mac Desktop without problem, so it can apparently circumvent this somehow. Is it possible iOS is not supported, or do you have a recommendation?

**Comment by astoeckley** [comment]
For what it's worth, I simply deleted the msinttypes directory (2 files, including stdint.h) from the cereal package and now I can compile. I don't use its parent, rapidJSON (I don't think, since I'm not doing any JSON serialization) so I don't know if removing these is a problem. But I googled this problem and it seemed that it is widely recommended never to include platform-specific implementations of the C or C++ standard library files, which is what these are. Just point that out, perhaps cereal should remove them completely.

**Comment by erichkeane** [comment]
The only usage of of this version of stdint.h is protected with:

    #if defined(_MSC_VER) && (_MSC_VER < 1800)	// Visual Studio 2013
    #include "msinttypes/stdint.h"
    #include "msinttypes/inttypes.h"
    #else
    // Other compilers should have this.
    #include <stdint.h>
    #include <inttypes.h>
    #endif

I'm not sure how you would get the msinttypes version unless your build system is being pretty stupid and picking up the msinttypes directory for "<stdint.h>" instead of the base directory.

**Comment by lichardlouis** [comment]
So have this issue been solved yet?  I just happen to meet the same error in my ios project. I dont understand why the Xcode would use Microsoft VC++ complier. It works just fine in my Android project, while not ok in ios project.
