### ISSUE TITLE
Using static/dynamic_cast instead of C-like cast

### ISSUE THREAD

**Issue by ntimeu** [USCiLab/cereal#368]
This is mostly an observation and a question, but would it be possible to use only static_cast and dynamic_cast instead of the C-like "(type)" casting in Cereal ? We personally compile with the "-Wold-style-cast" flag, which with the "-Werror" flag gives us multiple errors.

Is it a good idea to use this new cast-style or not ?

**Comment by erichkeane** [comment]
Already done in develop branch as of yesterday

**Comment by AzothAmmo** [comment]
Will be included in the next release.
