### ISSUE TITLE
Add support for std::optional serialization

### ISSUE THREAD

**Issue by runarundheim** [USCiLab/cereal#375]
I see that boost::optional is going to be added, but what about std::optional?
I think that std::optional should be serialized like the boost::optional. Then it will be possible to change a member from boost::optional to std::optional and still be able to load a previous serialized file.

**Comment by AzothAmmo** [comment]
We don't have any C++17 stuff in yet. We'll have to see how we want to handle splitting functionality across different C++ versions.

**Comment by patrikhuber** [comment]
A big +1 from me to include `std::optional` - the sooner the better ;-) VS2017 will come out on 7th March, and then all 3 major compilers are supporting it.

**Comment by erichkeane** [comment]
Azoth: Perhaps toss them into their own include files, then static-assert the SG10 Feature Test Macros?  I'd say based on __cplusplus, but MSVC still shows 1997 due to their lack of 2 phase lookup.

**Comment by AzothAmmo** [comment]
We could just use our own macro, let's say something like CEREAL_CXX17.

**Comment by M2tM** [comment]
I'd like this!

**Comment by bkeys** [comment]
Would also like to see C++17 support for Cereal, with the ```std::any``` type

**Comment by patrikhuber** [comment]
VS2017 with `<optional>` has been out for more than 8 months now and `<optional>` (as well as e.g. `std::variant`) are being supported well by all mainstream compilers (e.g. gcc-7, clang-5). It would be really awesome to have `std::optional` (and `std::variant`, `std::any`) now. I don't feel versed enough to contribute a PR myself, but is there a chance that progress can be made on that? :-)

**Comment by patrikhuber** [comment]
Oh, I just saw #448! It looks promising!

**Comment by anoopradhika** [comment]
Is there is chance for std::any?

**Comment by AzothAmmo** [comment]
resolved by #448
