### ISSUE TITLE
[Question] Serialize inside of a template function

### ISSUE THREAD

**Issue by progsource** [USCiLab/cereal#376]
So - I have a template function like

```
  template<typename T, typename T2>
  T2*
  Load(const std::string& filename)
  {
    std::string fullFilename = filename + ".json";
    std::ifstream is(fullFilename);
    ::cereal::JSONInputArchive archive(is);

    T vo;
    archive(vo);

    T2* voc = new T2();
    voc->vo = vo;

    return voc;
  }
```

and cereal is throwing me errors, like it cannot find the serialize functions, which are defined in the related classes.

> Types must either have a serialize function, load/save pair, or load_minimal/save_minimal pair

I saw http://uscilab.github.io/cereal/polymorphism.html , but that probably can't be used in this case, because the classes don't inherit from the template.
So what can I do in this situation?

My quick fix is to wrap the static asserts in `cereal.hpp` in an `#if 0 ... #endif` manner, but that can't be a real solution...

**Comment by AzothAmmo** [comment]
What are you instantiating `Load` with? Does `<T>` have a properly defined serialization function? You say they are defined, but likely there is something wrong with the way you have them set up, or potentially you are missing an include to the appropriate cereal serialization code (`<cereal/types/xxx.hpp>`).

**Comment by progsource** [comment]
Thank you for your fast response!

You were right, there were some type-header missing. Now it all works as intended. :smile:
