### ISSUE TITLE
JSON/XML output over fstream is failing in 

### ISSUE THREAD

**Issue by puentev** [USCiLab/cereal#381]
Release 1.2.2 (change set 51cbda5)

In JSON the clossing brace is missing. Sample code:

```
#include <cereal/archives/json.hpp>
#include <cereal/types/vector.hpp>
#include <fstream>

int main()
{
  std::ofstream out("pru");
  cereal::JSONOutputArchive archive( out );
  bool arr[] = {true, false};
  std::vector<int> vec = {1, 2, 3, 4, 5};
  archive(vec,arr);
  out.close();
}
```

This gives:

```
{
    "value0": [
        1,
        2,
        3,
        4,
        5
    ],
    "value1": {
        "value0": true,
        "value1": false
    }
```

XML does not work at all (produces an empty file).

Binary works just fine.

Thanks

**Comment by erichkeane** [comment]
The JSON archive works like a RAII container.  It doesn't apply the closing brace until its destructor.  Change your test to:
```
int main()
{
  std::ofstream out("pru");
  {
    cereal::JSONOutputArchive archive( out );
    bool arr[] = {true, false};
    std::vector<int> vec = {1, 2, 3, 4, 5};
    archive(vec,arr);
  }
  out.close();
}
```

**Comment by puentev** [comment]
ok... thanks. Perhaps a little change in QuickStart might be useful :)

**Comment by AzothAmmo** [comment]
> Create a cereal archive and send the data you want to serialize to it. Archives are designed to be used in an RAII manner and are guaranteed to flush their contents only on destruction (though it may happen earlier). Archives generally take either an std::istream or an std::ostream object in their constructor:

> Important! If you didn’t read that paragraph about cereal using RAII, read it again! Some archives in cereal can only safely finish flushing their contents upon their destruction. Make sure, especially for output serialization, that your archive is automatically destroyed when you are finished with it.

from http://uscilab.github.io/cereal/quickstart.html

Perhaps if we had some blinking text...

**Comment by puentev** [comment]
you are right! I was looking to the wrong examples.
Too much info for a slow brain like mine

**Comment by erichkeane** [comment]
You're not nearly the 1st, and definitely not the last.   Perhaps we just need to change the error message of "unexpected end of object" to "you didn't put this into its own scope, did you?"

**Comment by puentev** [comment]
I think the problem is when you try binary and all work perfect. Then, changing to JSON, whenunserialization fails... makes you think that the problem is no yours.

Clearly the Quickstart is perfect...
