### ISSUE TITLE
JSONInputArchive: value to string

### ISSUE THREAD

**Issue by gncs** [USCiLab/cereal#382]
Let's say I wanted to load the following JSON:
```
{
"a": { "b" : 2 }
}
```
Specifically, I want to save the value of `"a"` into a string variable (without knowing the exact structure of the value), so that the content of the variable would read `{"b": 2}` in this case. Is that possible?

**Comment by AzothAmmo** [comment]
Currently not possible unless that data was formatted as a string. It might technically be possible with RapidJSON (the parser we use), which would make it possible in cereal, but you'll have to do the digging to find out.

**Comment by gncs** [comment]
OK, thank you! :)
