### ISSUE TITLE
Issue serializing floats on Windows

### ISSUE THREAD

**Issue by AtolmDragon** [USCiLab/cereal#385]
I'm having trouble serializing floats with specific values on Windows. I built this small test to show the issue:
```c++
#include "stdafx.h"
#include "cereal\cereal.hpp"
#include "cereal\archives\portable_binary.hpp"
#include <fstream>

struct MyClass
{
    float x;

    template<class Archive>
    void serialize(Archive & archive)
    {
        archive(x);
    }
};

int main()
{
    {
        std::ofstream output("file");
        cereal::PortableBinaryOutputArchive archive(output);

        MyClass test;
        test.x = 0.604524374;
        archive(test);
    }
    
    {
        std::ifstream input("file");
        cereal::PortableBinaryInputArchive archive(input);

        MyClass lTest;
        archive(lTest);
    }

    return 0;
}
```

I tested it on MVSC 15 (target x64) and MVSC 13 (target x64) with cereal 1.2.2 and 1.2.1. It always throws the same exception when I'm loading the file

```c++
if(readSize != size)
          throw Exception("Failed to read " + std::to_string(size) + " bytes from input stream! Read " + std::to_string(readSize));
```

This works fine on Linux. If I change the type of the archive to JSON, it works with no problems at all on Windows. If I change the type to double, it also works on Windows but I can't make it works with floats. 

I'm sorry if there is something completely obvious I'm not seeing. I don't have that much experience with cereal.

**Comment by AzothAmmo** [comment]
Can you try using the `std::ios::binary` flag and see if that fixes it?

```cpp
std::ofstream output("file", std::ios::binary);
std::ifstream input("file", std::ios::binary);
```

**Comment by AtolmDragon** [comment]
I don't know how I missed that. Thanks! Everything is working properly now.
