### ISSUE TITLE
Error serializing std::array in binary mode

### ISSUE THREAD

**Issue by maylermartins** [USCiLab/cereal#405]
I had "non-deterministic" errors serializing std::array.

I have a type that store an index array (uint_fast32_t) and another data that does not matter to this problem.

I am using save/load methods in this class as shown below.

```
class MyData
{
private:
    using my_type = uint_fast32_t;
    std::array<my_type, 5> myarray;
public:
           template<class Archive>
        void save(Archive & archive) const
        {
              archive(myarray);
        }

           template<class Archive>
        void load(Archive & archive) const
        {
              archive(myarray);
        }
     //...
     // implemented also == and hash
}

```

I have a unordered_set with more than 2 million MyData instances. I use this set as part of a database trying to reduce the number of elements in memory. When I am saving the database in the file, I was using the default unordered_set save/load. However, I noticed that it was saving X elements and loading X - Y elements. The Y value every single time changed. Long short story, it was not the unordered_set (I dumped the contents in a vector, saved the vector in a file and problem still continued). After days investigating, I noticed that the value in myarray[0] was sometimes 0 instead of the correct value. Debugging the method, I noticed the method saveBinary receives void* data and size as arguments and when it was saving the myarray[0],  the size was 8 instead of 4. In this case, the method before is getting the size of the pointer instead of the size of the content, creating a bug.

My temporary solution was: 

```
           template<class Archive>
        void save(Archive & archive) const
        {
              for(size_t i = 0; i < myarray.size(); ++i)
              {
                   my_type m = myarray[i];
                   archive(m);
              }
        }
```

This solution can be easily added to array.hpp file.

**Comment by AzothAmmo** [comment]
I'm a little confused by your problem. You mention `saveBinary`, so I assume you are using a binary archive to serialize your data. If this is the case, the serialization code for `array` will not serialize elements individually - it does them all as one chunk of memory by taking the size of the entire array.

If you are using a different archive type, I can't reproduce your error. The `addressof` operation is applied to a reference, which gives the address of the underlying object. The same is true for `sizeof`. I used your code for serialization (after making load non-const).

Are you performing loading and saving on different machines? Could your problem be related to `uint_fast32_t`, which is not guaranteed to be the same size across computers?

**Comment by maylermartins** [comment]
Hi,

Thanks for the answer. Yes, I am using the binary archive that comes with cereal. About different machines: no, I am using the same for saving and loading. For debug purposes, I was exporting, and after closing the ofstream, I was importing the same file and comparing with my original database.

>  The addressof operation is applied to a reference, which gives the address of the underlying object. The same is true for sizeof.

You are right. I did so many attempts on the save/load pair that I lost my track. 

I did more debugging and saw that the size of the uint_fast32_t is also 8 bytes in my machine. This made this problem more unclear to me.

>  I used your code for serialization (after making load non-const).
My bad. In my code it was correct :)

I must confess that this is a very hard problem to reproduce. I spent 2 days just to figure out what was happening. From a database of 2 million elements, it happens 4-5 times and all cases that I saw are related to the 0th position of the array that is saved 0 instead of the correct number. In another database with 50000 elements, this does not happen. 

What I can try to dump a file that uses the default way to serialize the array and one with my solution and give you the link to a test code + the two serialized files. I will archive them using portable_binary to avoid endianess problems.

**Comment by maylermartins** [comment]
Hi,

I have some interesting news. It seems that the problem is related to the filesystem used in the servers (AFS). I saved the same file in the /tmp (which is local->ext4 and does not belong to the AFS) and for all tests that I performed, everything is fine.
