### ISSUE TITLE
Compile failed

### ISSUE THREAD

**Issue by acipolletti** [USCiLab/cereal#407]
Hi, i'm try to add serialization add to my class named TableInMem using vs2017, but when start the build process following error is writen :
Error	C2338	cereal could not find any output serialization functions for the provided type and archive combination.ConsoleApplication4 D:\LIBS\cereal-1.2.2\cereal-1.2.2\include\cereal\cereal.hpp 470	
Can you help me?

Following my c++ code, i omitted some part of code not important for this question.

#define _CRT_SECURE_NO_WARNINGS

#pragma once

#include <stdio.h>
#include <stdlib.h>
#include <tchar.h>

#include <iostream>
#include <string>
#include <sstream>

#include <vector>
#include <set>
#include <algorithm>
#include <thread>
#include <shared_mutex>
#include <chrono>
#include <map>

#include <boost/iostreams/code_converter.hpp>
#include <boost/iostreams/device/mapped_file.hpp>
#include <boost/algorithm/string.hpp>

#include <cereal/archives/binary.hpp>
#include <cereal/archives/portable_binary.hpp>
#include <cereal/archives/xml.hpp>
#include <cereal/archives/json.hpp>

typedef std::vector<std::string> record;
typedef std::map<int, record> grid;

typedef std::set<int> posizioni;
typedef std::map<std::string, posizioni> idx;

class TableInMem
{

private:
	grid griglia;
	idx MainIDX; //a special index created when file is loaded
	std::map<std::string, idx> Indexs; //where indexs are stored
	int PK_column;//primary key column

public:
	TableInMem();
	~TableInMem();
	
	template<class Archive>
	void serialize(Archive &  archive)
	{
		archive(griglia,MainIDX,Indexs,PK_column);
	}

	
	void ReadDSV(const std::string& file_name, FILE *log,
		std::string delimiters, int PrimaryKeyColumn,
		int col_index);

	std::vector<record> QueryMainIndex(std::string);
	void CreateIndex(std::string idx_name, int column);
	std::vector<record> QueryIndex(std::string idx_name, std::string key);

};

TableInMem::TableInMem()
{
	;;
}

TableInMem::~TableInMem()
{
	;;
}

int main()
{
	TableInMem tabella;

	FILE *txt = fopen("MyLog.txt", "w+t");
	
	tabella.ReadDSV("h:\\TLX\\MIT50202.mld", txt, "\t", 0, 98);
	
	tabella.CreateIndex("isin", 98);
	tabella.CreateIndex("pdn", 96);
	

	std::stringstream ss(std::ios_base::in | std::ios_base::out | std::ios_base::binary);

	{
		cereal::BinaryOutputArchive oarchive(ss); // Create an output archive

		
		oarchive(tabella); // Write the data to the archive
	} // archive goes out of scope, ensuring all contents are flushed
	
	fclose(txt);
	return 0;
}

**Comment by erichkeane** [comment]
You need to include the cereal 'types' for std::string, std::map, std::set, and std::vector.
See: http://uscilab.github.io/cereal/stl_support.html

**Comment by acipolletti** [comment]
Fixed, thanks a lot
