### ISSUE TITLE
"max" macro conflicting on Windows

### ISSUE THREAD

**Issue by turbofandude** [USCiLab/cereal#408]
In polymorphic_impl.hpp, line 265, `return {std::numeric_limits<size_t>::max(), {}};` conflicts with the macro definition of `max `in minwindef.h.

The following code fixes it (as a band-aid of course):

```
#ifdef min
#undef min
#endif
#ifdef max
#undef max
#endif
```

**Comment by erichkeane** [comment]
There are 2 common fixes to this:
First, disable the min/max macros before including windows.h as they are fairly worthless:

    #define NOMINMAX
    
If you're sure you NEED these macros for some insane reason, change the line in polymorphic_impl.hpp to:

    return {(std::numeric_limits<size_t>::max)(), {}};

**Comment by AzothAmmo** [comment]
I think the solutions that @erichkeane offers are perfectly acceptable for this (i.e. the onus is on the user). If a macro conflicts with the standard library, that's not our problem.
