### ISSUE TITLE
Install of cerealConfig.cmake and cereal-config.cmake via Homebrew

### ISSUE THREAD

**Issue by tvatter** [USCiLab/cereal#410]
Hi,

I "installed" cereal via homebrew, and it looks like the brew formula does not export cerealConfig.cmake and cereal-config.cmake (e.g., in order to be able to use find_package(cereal)).

Am I missing something?

**Comment by tvatter** [comment]
See https://github.com/Homebrew/homebrew-core/pull/14427

**Comment by AzothAmmo** [comment]
Looks like this was resolved on their end; closing.
