### ISSUE TITLE
Question about registerSharedPointer return value when addr not exists

### ISSUE THREAD

**Issue by yuqian90** [USCiLab/cereal#419]
I don't know if this is an issue or a question. This block of code looks bizarre to me.

When addr exists in itsSharedPointerMap, the method returns the value from the map. But when addr does not exist in itsSharedPointerMap, it inserts {addr, ptrId} but return the value after masking it with msb_32bit.

So if someone just call registerSharedPointer twice passing the same addr, the return value will not be the same. (the first call is ptrId masked by msb_32bit, the second call is just ptrId)

i.e. something like this is bound to fail the assert:
```
...
auto ret = oarc.registerSharedPointer(ptr);
auto ret2 = oarc.registerSharedPointer(ptr);
assert ret == ret2; // This is not true.
```
What's the whole reason behind this?

This is from class OutputArchive defined in cereal.hpp:
```
      inline std::uint32_t registerSharedPointer( void const * addr )
      {
        // Handle null pointers by just returning 0
        if(addr == 0) return 0;

        auto id = itsSharedPointerMap.find( addr );
        if( id == itsSharedPointerMap.end() )
        {
          auto ptrId = itsCurrentPointerId++;
          itsSharedPointerMap.insert( {addr, ptrId} );
          return ptrId | detail::msb_32bit; // mask MSB to be 1
        }
        else
          return id->second;
      }
```

**Comment by erichkeane** [comment]
Is the difference the MSB?  The function inserts ptrId, then returns ptrId | msb_32bit.  The other path simply returns what was previously 'ptrId'.

Either the insert and the mask need to be reversed, OR the 'else' needs to have an | detail::msb_32bit on it?

**Comment by yuqian90** [comment]
Yes it does look like a mistake to me. But I would like to confirm if that's the case or if it's something intentional.

**Comment by AzothAmmo** [comment]
The MSB is masked to one on only the first serialization of a shared pointer, such that for

```cpp
auto ret = oarc.registerSharedPointer(ptr);
auto ret2 = oarc.registerSharedPointer(ptr);
```


`ret == (ret2 | detail::msb_32bit)` would be true.

The MSB is used to signify the first instance of serializing a particular address such that it does not get saved (or loaded) twice. If you look at, for example, the code for saving a `shared_ptr`, you'll see:

```cpp
  template <class Archive, class T> inline
  void CEREAL_SAVE_FUNCTION_NAME( Archive & ar, memory_detail::PtrWrapper<std::shared_ptr<T> const &> const & wrapper )
  {
    auto & ptr = wrapper.ptr;

    uint32_t id = ar.registerSharedPointer( ptr.get() );
    ar( CEREAL_NVP_("id", id) );

    if( id & detail::msb_32bit )
    {
      ar( CEREAL_NVP_("data", *ptr) );
    }
  }
```

Note that only if register returned a value that has had its MSB tagged do we serialize the actual contents of the pointer.

Similarly, when loading:

```cpp
  template <class Archive, class T> inline
  typename std::enable_if<traits::has_load_and_construct<T, Archive>::value, void>::type
  CEREAL_LOAD_FUNCTION_NAME( Archive & ar, memory_detail::PtrWrapper<std::shared_ptr<T> &> & wrapper )
  {
    auto & ptr = wrapper.ptr;

    uint32_t id;

    ar( CEREAL_NVP_("id", id) );

    if( id & detail::msb_32bit )
    {
      // a whole bunch of stuff
    }
    else
      ptr = std::static_pointer_cast<T>(ar.getSharedPointer(id));
  }
```

If the MSB has been set, we know this is the first instance of this type to be saved, so we have to go ahead and load its actual data and set up some other metadata for loading. When we get to the type for the second time, the MSB is no longer set, and we can skip doing all of that work.

**Comment by yuqian90** [comment]
Thanks for explaining how it works. This all makes sense now. I'm hoping someone can add these explanation as the documentation about the  return value of  registerSharedPointer() in cereal.hpp. It'll help more people.
