### ISSUE TITLE
cereal conflicts with rapidjson externally

### ISSUE THREAD

**Issue by rcdailey** [USCiLab/cereal#424]
I include both rapidjson and cereal headers in my code (I have legacy code still using rapidjson, so it cannot be easily removed).

I run into conflicts like so:

```
In file included from E:/code/frontend/source/Core/ThirdParty/rapidjson/include\rapidjson/document.h:20:

In file included from E:/code/frontend/source/Core/ThirdParty/rapidjson/include\rapidjson/reader.h:20:

In file included from E:/code/frontend/source/Core/ThirdParty/rapidjson/include\rapidjson/allocators.h:18:

E:/code/frontend/source/Core/ThirdParty/rapidjson/include\rapidjson/rapidjson.h:616:6: error: redefinition of 'Type'

enum Type {

     ^

E:/code/frontend/source/Core/ThirdParty/cereal/include\cereal/external/rapidjson/error/../rapidjson.h:603:6: note: previous definition is here

enum Type {

     ^
```

Is there a fix for this?

**Comment by AzothAmmo** [comment]
You can define a custom namespace for all cereal rapidjson code, see [rapidjson.h](https://github.com/USCiLab/cereal/blob/master/include/cereal/external/rapidjson/rapidjson.h) at line 77 (CEREAL_RAPIDJSON_NAMESPACE_(BEGIN|END)).

The macro `CEREAL_RAPIDJSON_NAMESPACE` can be a name of your choosing. By default it is `rapidjson`, so you get the conflicts you have.

**Comment by rcdailey** [comment]
Thanks. I went with `CEREAL_RAPIDJSON_NAMESPACE=cereal_rapidjson` and this seems to work.
