### ISSUE TITLE
Cereal can't read my GameMaker .yyp JSON file?

### ISSUE THREAD

**Issue by Sixmorphugus** [USCiLab/cereal#428]
Since it's a long JSON file that GameMaker generated, I pasted it here: https://pastebin.com/fGMGXHFE

The error is that RapidJSON's assertion failed because IsObject() returned false. However, I've tested the JSON in multiple validators and all of them have told me that it's valid. The issue seems to be coming from the RapidJSON library - however I don't know what else is being done by cereal that causes the error.

**Comment by AzothAmmo** [comment]
cereal is not a general purpose JSON parser - it can only read JSON that it generates (or JSON that is in an identical structure to what it would output). I'm assuming that GameMaker is not using cereal to generate its output.

**Comment by Sixmorphugus** [comment]
Ah.
So it can't read JSON generated by other programs, even if I use name-value pairs?

**Comment by AzothAmmo** [comment]
It would only be able to read it if it coincidentally matched the format cereal would generate.
