### ISSUE TITLE
Portable binary archives seems to be not so portable

### ISSUE THREAD

**Issue by zhuebok** [USCiLab/cereal#433]
Serialization method for `SizeTag` type declared in `portable_binary.hpp` file seems to be not so portable cause it depends on type of `t.size` value that often has `size_t` type. This type depends on target machine compiler and so can be not same between different machines.

**Comment by AzothAmmo** [comment]
`SizeTag` are created by `make_size_tag`, which in every instance I can see we initialize with a cast to `cereal::size_type` which is a fixed size type. For loading we always load into `size_type` before casting to `size_t`.

We could potentially do this cast automatically to be safer. Are you aware of any specific instance where `size_t` is the type being saved or loaded?

**Comment by zhuebok** [comment]
Oh, I see. Each container `size` is casted explicitly to the `size_type` type before serializing it. I overlooked it when creating save/load methods for my containers.
