### ISSUE TITLE
errors in vs2017 build

### ISSUE THREAD

**Issue by vonders** [USCiLab/cereal#441]
base_class.hpp in vs2017 gives the following compile error:
C2027 use of undefined type 'cereal::detail::RegisterPolymorphicCaster<Base,Derived>

**Comment by resul4e** [comment]
I've got the same error.

**Comment by resul4e** [comment]
So if you call CEREAL_REGISTER_POLYMORPHIC_RELATION(Base, Derived) the error disappears and you can use cereal::base_class<Base>(this). Hope this helps, no idea if this is an intended solution, but it seems to work for me.

**Comment by resul4e** [comment]
Nope nvm,

It's not the call to CEREAL_REGISTER_POLYMORPHIC_RELATION(Base, Derived) that fixed it, but the inclusion of types/polymorphic.hpp. So #include "types/polymorphic.hpp" and you can call base_class(this).

**Comment by AzothAmmo** [comment]
@resul4e You are correct, the `polymorphic.hpp` include needs to precede `base_class`. I guess this just happens by chance in our unit tests.

**Comment by AzothAmmo** [comment]
Addressing this with documentation only - you will still need to be sure to include `cereal/types/polymorphic.hpp` if using `base_class` with a polymorphic type.
