### ISSUE TITLE
Cereal Access Violation error when used with singleton/Shared pointer

### ISSUE THREAD

**Issue by PixelClear** [USCiLab/cereal#443]
I have code like following 

```
    class XY
   {
     static std::share_ptr<XY> GetInstance()
      {
         static std::shared_ptr<XY> data = std::make_shared<XY>();
         return data;
      }
   }
```

Then I have two files containing two functions which access shared instance of class XY.
A.cpp

```
     void f1()
      {
         std::shared_ptr serData = XY::GetInstance();
         
         //Fill some data in shared_ptr serData
      
        std::stringstream debugData(std::stringstream::in | std::stringstream::out | std::stringstream::binary);
         {
            cereal::PortableBinaryOutputArchive archive(debugData);
            archive(*serData);
         }
             
       }
```

Similarly I have 

b.cpp

```
     void f2()
      {
         std::shared_ptr serData = XY::GetInstance();
         
         //Fill some data in shared_ptr serData
      
        std::stringstream debugData(std::stringstream::in | std::stringstream::out | std::stringstream::binary);
         {
            cereal::PortableBinaryOutputArchive archive(debugData);
            archive(*serData);   **//Crashesh to this call** 
         }
             
       }
```

In function f2 call to archive function crashes and it give access violation error in file **portable_binary.cpp**in **saveBinary()** function.
If I dont used shared instance of class this works fine but I want f1 and f2 to share same instance of class.

Can any body tell me what I am doing wrong?

PixelClear

**Comment by erichkeane** [comment]
I'm guessing the 'GetInstance' function is in a header file that both include?  If so, thats your problem.  There ends up being two seprate versions of the same static value and two versions of the same function. 

Toss a function declaration of GetInstance in the header, and pull the implementation out to a C++ file somewhere.

**Comment by PixelClear** [comment]
No the function GetInstance() is in separate cpp file.

**Comment by PixelClear** [comment]
You may close the issue. I have found the problem It has nothing to do with cereal. one of the members in my shared pointer was getting corrupted when it used to come to second module and cereal archive function used to throw exception.

Thanks for help.
