### ISSUE TITLE
detect cereal version at compile time / version.hpp

### ISSUE THREAD

**Issue by h-2** [USCiLab/cereal#444]
Is there a way (through macro or static assertion) to test for the currently installed cereal version? Something like
https://github.com/ericniebler/range-v3/blob/master/include/range/v3/version.hpp
https://github.com/seqan/seqan3/blob/master/include/seqan3/version.hpp 
https://github.com/boostorg/hana/blob/master/include/boost/hana/version.hpp

Since cereal is a header-only library, other libraries or apps may want to use it without relying on a build system... detection already works via `#if __has_include(<cereal/cereal.hpp>)`, but it is important to also know the version for compatibility checks!

Thank you!

**Comment by AzothAmmo** [comment]
I think this is reasonable and something we should include starting with the next version. There is currently no way to do this with cereal.
