### ISSUE TITLE
Some compiler warnings on ICC

### ISSUE THREAD

**Issue by pvleuven** [USCiLab/cereal#445]
Hi,

The ICC emits several warnings:

1: **Implicit type casting** (multiple warnings)
****/cereal.hpp(314): warning #68: integer conversion resulted in a change of sign
            return ptrId | detail::msb_32bit; 

proposed fix:
I think msb_32bit should be declared as std::uint32_t and not std::int32_t as is the case currently.

2: **Hiding member variable**
****/cereal/details/polymorphic_impl.hpp(179): warning #3280: declaration hides member "cereal::detail::PolymorphicCasters::map" (declared at line 119)

          for( auto const * map : mapping )

proposed fix:
A rename would do.

3: **Missing return statements in rapidjson.** 

****/cereal/external/rapidjson/document.h(319): warning #1011: missing return statement at end of non-void function "rapidjson::GenericStringRef<CharType>::operator="
      GenericStringRef& operator=(const GenericStringRef& rhs) { s = rhs.s; length = rhs.length; }
                                                                                                 ^
****/cereal/external/rapidjson/document.h(510): warning #1011: missing return statement at end of non-void function "rapidjson::internal::TypeHelper<ValueType, ValueType::Object>::Set(ValueType &, rapidjson::internal::TypeHelper<ValueType, ValueType::Object>::ObjectType, ValueType::AllocatorType &)"
      static ValueType& Set(ValueType& v, ObjectType data, typename ValueType::AllocatorType&) { v = data; }

**Comment by AzothAmmo** [comment]
I think we have a fix for (1) staged in a PR I need to merge, #423. 

(2) I'm surprised isn't caught by -wshadow, but it indeed should be renamed.

(3) There are a few other issues related to rapidjson warnings and this will have to be handled along with those.

**Comment by AzothAmmo** [comment]
(1) and (2) are both resolved (on develop, soon to be next version).

**Comment by AzothAmmo** [comment]
Hoping (3) is resolved by #579
