### ISSUE TITLE
Serialization to a vector results in "failed to read from input stream"

### ISSUE THREAD

**Issue by Hi-Angel** [USCiLab/cereal#452]
The code is:

	#include <cereal/archives/binary.hpp>
	#include <cereal/types/vector.hpp>
	#include <vector>
	#include <sstream>
	#include <cstdint>
	
	struct MyClass {
	    uint8_t a, b, c;
	
	    template<class Archive>
	    void serialize(Archive & archive) {
	        archive(a, b, c);
	    }
	};
	
	int main() {
	    MyClass myclass = {1, 2, 3};
	    std::stringstream ss(std::ios::binary | std::ios::out | std::ios::in);
	    cereal::BinaryOutputArchive class_to_ss(ss);
	    class_to_ss(myclass);
	
	    cereal::BinaryInputArchive ss_to_vec(ss);
	    std::vector<uint8_t> v;
	    ss_to_vec(v);
	}

It throws:

```
terminate called after throwing an instance of 'cereal::Exception'
  what():  Failed to read 8 bytes from input stream! Read 3
```

**P.S.**: it might be a mistake. It boils down to the fact that I haven't found any examples of serializing a struct into a vector or array, I made up this sample code myself. [However a short discussion on ML](https://groups.google.com/forum/#!topic/cerealcpp/eMG4lEnto4U) made me suspicious it is a bug.

Either way I decided it'd be good to report, might save someone's time in the future.

**Comment by randvoorhies** [comment]
Throwing an error is the appropriate thing for cereal to do here. You should never serialize `ClassA`, and then try to deserialize it into `ClassB`.

If you're just trying to get `MyClass` as a flat binary representation, then you've already put it in `ss` with `class_to_ss(myclass)`.  If you need it as a vector, then you can just `std::copy` the data from `class_to_ss` to `v`.  Alternatively, you could write your own child of `std::ostream` that dumps directly into an `std::vector` and use it instead of `ss`.

**Comment by Hi-Angel** [comment]
@randvoorhies copy from `class_to_ss`? How do I get the pointer and the size?

**Comment by Hi-Angel** [comment]
In case you rather meant a copy of `ss`, acc. [to this answer](https://stackoverflow.com/a/6010930/2388257), quoting, `Copying of stream is disabled because it doesn't make sense`.

**Comment by randvoorhies** [comment]
```cpp
#include <cereal/archives/binary.hpp>
#include <cereal/types/vector.hpp>
#include <vector>
#include <sstream>
#include <cstdint>

struct MyClass {
    uint8_t a, b, c;

    template<class Archive>
    void serialize(Archive & archive) {
        archive(a, b, c);
    }
};

int main() {
    MyClass myclass = {1, 2, 3};
    std::stringstream ss(std::ios::binary | std::ios::out | std::ios::in);
    cereal::BinaryOutputArchive class_to_ss(ss);
    class_to_ss(myclass);

    // Copy the contents of the stringstream to a vector of bytes
    std::string s = ss.str();
    std::vector<uint8_t> v(s.begin(), s.end());

    std::cout << v.size() << " bytes in vector: ";
    for(auto b : v) std::cout << int(b) << " ";
    std::cout << std::endl;
}
```
```
rand@rocinante:~$ ./test-452
3 bytes in vector: 1 2 3
```

**Comment by Hi-Angel** [comment]
Thank you very much!

**Comment by Hi-Angel** [comment]
To future readers: I find creating an intermediate `std::string` variable that just hangs there for no reason not really elegant, and turned out it's possible to convert stringstream to a vector through `isteam_iterator`, e.g.:


	#include <cereal/archives/binary.hpp>
	#include <cereal/types/vector.hpp>
	#include <vector>
	#include <sstream>
	#include <cstdint>
	#include <iterator>
	
	struct MyClass {
	    uint8_t a, b, c;
	
	    template<class Archive>
	    void serialize(Archive & archive) {
	        archive(a, b, c);
	    }
	};
	
	template<typename T>
	std::stringstream serialize(T& myclass) {
	    std::stringstream ss(std::ios::binary | std::ios::out | std::ios::in);
	    cereal::BinaryOutputArchive class_to_ss = {ss};
	    class_to_ss(myclass);
	    return ss;
	};
	
	int main() {
	    MyClass myclass = {1, 2, 3};
	    auto ss = serialize(myclass);
	
	    // Copy the contents of the stringstream to a vector of bytes
	    std::vector<uint8_t> v = { std::istream_iterator<uint8_t>(ss),
	                               std::istream_iterator<uint8_t>() };
	
	    std::cout << v.size() << " bytes in vector: ";
	    for(auto b : v)
	        std::cout << int(b) << " ";
	    std::cout << std::endl;
	}

```
$ ./a
3 bytes in vector: 1 2 3
```
