### ISSUE TITLE
Extracting following α bytes as a byte-array?

### ISSUE THREAD

**Issue by Hi-Angel** [USCiLab/cereal#454]
I couldn't find docs or questions about it.

I'm getting arrays of data in a form similar to the following *(except that flexible-array is invalid in standard, and real situation is more complicated because of multiple types of structs with distinct sizes of fields)*:

```c++
struct TLV {
	uint32_t sz_arr;
	uint8_t arr[];
};
```

How do I, for deserialization, "extract" `sz_arr` amount of the following data, and assign it to a pointer *(I mean, `arr` would have to be a pointer then)*. E.g. incomplete illustration:

```c++
#include <cereal/archives/binary.hpp>
#include <memory>

struct TLV {
    uint32_t arr_sz;
    std::unique_ptr<uint8_t> arr;

    template<class Archive>
    void load(Archive& archive) {
        archive(arr_sz);
        // ISSUE: how to extract "arr_sz" amount to the arr?
    }
};

template<typename T>
T deserialize(uint8_t dat[], uint sz_dat) {
    std::stringstream ss(std::ios::binary | std::ios::out | std::ios::in);
    cereal::BinaryOutputArchive arr_to_ss = {ss};
    arr_to_ss(cereal::binary_data(dat, sz_dat));

    cereal::BinaryInputArchive ss_to_MyClass(ss);
    T t;
    ss_to_MyClass(t);
    return t;
}

int main()
{
    uint8_t arr[] = {1, 0, 0, 0, 9};
    TLV myclass = deserialize<TLV>(arr, sizeof(arr));
}
```

**Comment by Hi-Angel** [comment]
As it happens, after posting it I suddenly realized I could've used a vector. So I scratched the following code, works for me:

```c++
#include <cereal/archives/binary.hpp>
#include <vector>

struct TLV {
    uint32_t arr_sz;
    std::vector<uint8_t> arr;

    template<class Archive>
    void load(Archive& archive) {
        archive(arr_sz);
        arr = std::vector<uint8_t>(9);
        for(unsigned i = 0; i < arr_sz; ++i)
            archive(arr[i]);
    }
};

template<typename T>
T deserialize(uint8_t dat[], uint sz_dat) {
    std::stringstream ss(std::ios::binary | std::ios::out | std::ios::in);
    cereal::BinaryOutputArchive arr_to_ss = {ss};
    arr_to_ss(cereal::binary_data(dat, sz_dat));

    cereal::BinaryInputArchive ss_to_MyClass(ss);
    T t;
    ss_to_MyClass(t);
    return t;
}

int main()
{
    uint8_t arr[] = {1, 0, 0, 0, 9};
    TLV myclass = deserialize<TLV>(arr, sizeof(arr));
}
```

**Comment by Hi-Angel** [comment]
By the way, this is another usecase for [issue 453](https://github.com/USCiLab/cereal/issues/453) — the problem with the code is that it is easy to make DOS attack by sending a packet with `sz_arr=0xffffffffffffffff`. The code needs to check amount of bytes left, and not blindly trust to the field.

There should be a documented way of doing this.

**Comment by AzothAmmo** [comment]
I'm a bit confused on the way you are choosing to interface with cereal - though perhaps this is just because you are creating an reduced example.

```cpp
struct TLV {
    uint32_t arr_sz;
    std::vector<uint8_t> arr;

    template<class Archive>
    void load(Archive& archive) {
        archive(arr_sz);
        arr = std::vector<uint8_t>(arr_sz);
        for(unsigned i = 0; i < arr_sz; ++i)
            archive(arr[i]);
    }
};
```

For example, the above snippet is a very odd way of serializing a vector, because cereal ships with code to do this for you in a more optimized way than you are doing here. You just have to include support via `<cereal/types/vector.hpp>` and you can then serialize the vector directly, i.e.:

```cpp
struct TLV {
    uint32_t arr_sz; // this is not needed for serialization, vector already maintains a size
    std::vector<uint8_t> arr;

    template<class Archive>
    void load(Archive& archive) {
        archive(arr); // cereal will do all of the work for you
    }
};
```

Your deserialize function is also very confusing since just passing your type to an input archive does the deserialization for you by calling the appropriate function (e.g., load, serialize, etc). If you need to work directly on a raw stream of data you may want to try creating your own "memory stream" class, take a look at these examples: [one](https://stackoverflow.com/a/1449527/710791), [two](https://stackoverflow.com/a/1495582/710791). You could then have cereal directly operate on this stream.

**Comment by Hi-Angel** [comment]
> For example, the above snippet is a very odd way of serializing a vector, because cereal ships with code to do this for you in a more optimized way than you are doing here. You just have to include support via <cereal/types/vector.hpp> and you can then serialize the vector directly, i.e.:
>
>```c++
>struct TLV {
>    uint32_t arr_sz; // this is not needed for serialization, vector already maintains a size
>    std::vector<uint8_t> arr;
>
>    template<class Archive>
>    void load(Archive& archive) {
>        archive(arr); // cereal will do all of the work for you
>    }
>};
>```

But this would deserialize **all of the bytes** into the vector, right? This won't work for me. Imagine there's an array of the following data: `{TLV{3, {1,2,3}}, TLV{1, {1}}, TLV{2, {1,2}}}`, except that this is a byte-array, e.g. because I received it from the network. If I do `archive(arr)`, this means I gonna get the second and third TLVs as a vector instead of deserializing them into actual structs.

What I do instead, is serialize into the vector only `arr_sz` amount of data, then somewhere on the outside code I'm shifting a pointer by the size of the struct + vector, then deserialize the second strct, and so on.

> If you need to work directly on a raw stream of data you may want to try creating your own "memory stream" class, take a look at these examples: one, two. You could then have cereal directly operate on this stream.

Thank you so far I'm fine with the code, but I'll look at it if it get more complicated.

**Comment by Hi-Angel** [comment]
@AzothAmmo you might ask me "why not to apply stringstream only to certain subset of the data in the first place, and thus use later `archive(arr)` as all normal people?". Anyways, at least this question popped up on me a few seconds ago, and I got scary for a moment that I've done something silly :Ь But it's all correct — I simply cannot know where the structures starts and ends, it can be only found by deserialization code. In my case with IMPP It's even more complicated: I don't even know where the size of the data resides, because depending on some other field it can be `uint_16` or `uint32_t`.

**Comment by Hi-Angel** [comment]
> For example, the above snippet is a very odd way of serializing a vector, because cereal ships with code to do this for you in a more optimized way than you are doing here. You just have to include support via `<cereal/types/vector.hpp>` and you can then serialize the vector directly, i.e.:

@AzothAmmo unfortunately it doesn't work :( I do have one place where Cereal's ability to *(de)* serialize a vector could have been neat — but it produces unexpectedly big size. Here's an illustration *(I didn't do a minimal test for `load()` counterpart, but it would be rational to assume it behaves the same)*:

```c++
#include <cereal/archives/binary.hpp>
#include <cereal/types/vector.hpp>
#include <vector>
#include <iterator>

struct MyStruct {
    std::vector<uint8_t> vec;

    template<typename Archive>
    void save(Archive& archive) const {
        archive(vec);
    }
};

template<typename T>
const std::vector<uint8_t> serialize(const T& t) {
    std::stringstream ss(std::ios::binary | std::ios::out | std::ios::in);
    cereal::BinaryOutputArchive class_to_ss = {ss};
    class_to_ss(t);

    return { std::istream_iterator<uint8_t>(ss),
             std::istream_iterator<uint8_t>() };
}

int main() {
    MyStruct s = {{1, 2, 4}};
    std::vector<uint8_t> serialized = serialize(s);
    printf("size of serialized is %lu, should be %lu\n", serialized.size(), sizeof(uint8_t)*3);
}
```

```
$ g++ test2.cpp -o a
$ ./a
size of serialized is 11, should be 3
```

I suspect Cereal for some reason serializes some additional info besides the data.
