### ISSUE TITLE
Cereal reports the wrong error message for the wrong problem

### ISSUE THREAD

**Issue by shahril96** [USCiLab/cereal#458]
I found one problem that has been bugging me.

Instead of reporting the right warning, Cereal reports `error: static assertion failed: cereal could not find any output serialization functions...` all the time.

For example, for my code that uses `std::shared_ptr`, if I'm suddenly forgot to include `memory.hpp` header, for example:
```
#include <cereal/types/vector.hpp>
//#include <cereal/types/memory.hpp>
#include <cereal/archives/json.hpp>
```

Compiling the code with above header will show the **_could not find any output serialization functions_**, which is very confusing IMHO. This really wasted my time because I kept looking for errors in my code while the real culprit is because I forgot to include the right header to the project. :(

My simplified code for this problem : https://pastebin.com/6cfXG5yy
Cereal version: 1.2.2

**Comment by AzothAmmo** [comment]
I wouldn't consider this to be the wrong message for the wrong problem. As far as cereal is concerned, it looked for a serialization function for `std:;shared_ptr`, and could not find one. Thus it gives you the `could not find any output serialization functions...` static assertion. Usually you'll have to look at the traceback to see the offending type or line as well.
