### ISSUE TITLE
Inheritance and external load/save functions

### ISSUE THREAD

**Issue by xoac** [USCiLab/cereal#460]
Hi,
I am trying to resolve #459. I use 3part library and want to add some serialize functions. So it's obviously I want place then in my code as external. 

Let's say I use `struct X` that is from external library. So I do:

```cpp
struct X {
    int x;
};

template<class Archive>
void load(Archive & archive, X& x)
{
    archive(
        x.x
    );
}

template<class Archive>
void save(Archive & archive, const X & x)
{
    archive(
        x.x
    );
}
```

Now I want to create my own `struct Y` that will inherit from `X`:  
**Code is not important, just example. It's just meter it use `cereal::base_class<T>`**  

```cpp
struct Y: X {

    Y()
    {
        force = std::make_optional<bool>(true);
    }

    std::optional<bool> force;

    template<class Archive>
    void save(Archive & archive) const
    {
        archive(
            cereal::base_class<X>(this)
        );

        if(force)
            archive(
                cereal::make_nvp("force", *force)
            );
    }

    template<class Archive>
    void load(Archive & archive)
    {
        archive(cereal::base_class<X>(this));

        bool tmp_val;
        try {
            archive(cereal::make_nvp("force", tmp_val));
            force = std::make_optional(tmp_val);
        }
        catch(cereal::Exception &e)
        {
            archive.setNextName(nullptr);
        }
    }
};
```

And the problem is the Y class can also by serialized by X load / save funtions... So cereal give me static asscertion 
>../cereal/include/cereal/cereal.hpp:472:9: error: static assertion failed: cereal found more than one compatible output serialization function for the provided type and archive combination. 

How can I go around this problem?

**Comment by AzothAmmo** [comment]
We have a way to deal with this in cereal, take a look at the [inheritance](http://uscilab.github.io/cereal/serialization_functions.html#inheritance) section of the documentation, or this doxygen page: http://uscilab.github.io/cereal/assets/doxygen/structcereal_1_1specialize.html

**Comment by xoac** [comment]
Thx that works. I thought this was just for `serialized` `load/save`.
