### ISSUE TITLE
Runtime when compiling with gcc and sanitizers

### ISSUE THREAD

**Issue by msporyshev** [USCiLab/cereal#467]
I've compiled my program with g++ using CMAKE_BUILD_TYPE=Asan (with sanitizers)
When I run the program, I get runtime exception right after start
"runtime error: reference binding to null pointer of type 'const struct PolymorphicCasters'"

Deleting [this row](https://github.com/USCiLab/cereal/blob/master/include/cereal/details/static_object.hpp#L76) from static_object.hpp solves this problem. Why do you need it?

**Comment by msporyshev** [comment]
Hm, i've run tests without that function the following tests failed:
	 16 - test_polymorphic (Failed)
	 17 - test_polymorphic_32 (Failed)
	 58 - test_structs_specialized (Failed)
	 59 - test_structs_specialized_32 (Failed)
So, it seems that it is needed =) But I don't understand right now, why local static object is not enough

**Comment by AzothAmmo** [comment]
That line is performing some dark hacky black magic to support polymorphic serialization. There's a potential fix for this slated in #470 to calm the sanitizers.
