### ISSUE TITLE
Cereal PortableBinary exception running

### ISSUE THREAD

**Issue by nguoithichkhampha** [USCiLab/cereal#468]
cereal version 1.2.2
Hi,
I'm using cereal portable binary to serialize data. When I save a file with cereal::PortableBinaryOutputArchive and load again, cereal works well if run on same OS.
But if I create that file on Windows system 32 bit and load on Mac OS (64 bit architecture), I got exception std::bad_alloc.
Someone can help me figure out the problem ?

**Comment by johnwbyrd** [comment]
The last time I checked, the only thing the PortableBinary serializers try to do, is handle endianness differences on the same platform.  But they cannot handle 32-bit vs 64-bit platforms, nor can they handle debug vs. release build differences.  Which, of course, means that the PortableBinary functions are not at all portable.  At some point I may dig into this code and fix this nonsense once and for all.

**Comment by nguoithichkhampha** [comment]
I found my problem. In the data for serialize , I used a value type long. long value is 4 bytes on 32 bits system but 8 bytes on 64 bits system. Just change long to std:: int32_t to fix it.
