### ISSUE TITLE
"cereal could not find any input serialization functions" with custom type

### ISSUE THREAD

**Issue by bperel** [USCiLab/cereal#472]
Hi,

I would like to serialize `OpenCV:Mat`-typed objects.

I found a [blog article](http://www.patrikhuber.ch/blog/6-serialising-opencv-matrices-using-boost-and-cereal) with the load/save methods that would allow to do that, and adapted them a little bit :
```c++
#include "cereal/cereal.hpp"
#include <memory>
#include <fstream>
#include <cstring>

#ifndef CEREAL_TYPES_MAT_HPP_
#define CEREAL_TYPES_MAT_HPP_

namespace cereal {
    template<class Archive>
    void CEREAL_SAVE_FUNCTION_NAME(Archive & ar, const cv::Mat &mat) {
        int rows, cols, type;
        bool continuous;

        rows = mat.rows;
        cols = mat.cols;
        type = mat.type();
        continuous = mat.isContinuous();

        ar & rows & cols & type & continuous;

        if (continuous) {
            const int data_size = rows * cols * static_cast<int>(mat.elemSize());
            auto mat_data = cereal::binary_data(mat.ptr(), data_size);
            ar & mat_data;
        } else {
            const int row_size = cols * static_cast<int>(mat.elemSize());
            for (int i = 0; i < rows; i++) {
                auto row_data = cereal::binary_data(mat.ptr(i), row_size);
                ar & row_data;
            }
        }
    };

    template<class Archive>
    void CEREAL_LOAD_FUNCTION_NAME(Archive &ar, cv::Mat &mat) {
        int rows, cols, type;
        bool continuous;

        ar & rows & cols & type & continuous;

        if (continuous) {
            mat.create(rows, cols, type);
            const int data_size = rows * cols * static_cast<int>(mat.elemSize());
            auto mat_data = cereal::binary_data(mat.ptr(), data_size);
            ar & mat_data;
        } else {
            mat.create(rows, cols, type);
            const int row_size = cols * static_cast<int>(mat.elemSize());
            for (int i = 0; i < rows; i++) {
                auto row_data = cereal::binary_data(mat.ptr(i), row_size);
                ar & row_data;
            }
        }
    }
}

#endif // CEREAL_TYPES_MAT_HPP_
```

Unfortunately the compilation fails with the following error:
`error: static assertion failed: cereal could not find any input serialization functions for the provided type and archive combination.`

I checked issues #302 and #398 which produced the same kind of error, but didn't find a solution for my problem. If I comment the lines with `ar & mat_data;` and `ar & row_data;` in `CEREAL_LOAD_FUNCTION_NAME`, the compilation succeeds, but then my `Mat` objects won't be properly serialized.
I also tried to add `#include <cereal/types/polymorphic.hpp>` or `#include "cereal/types/memory.hpp"` like some forum threads succeeded, but no more luck.

I'm using version 1.2.2. I'm a C++ beginner, so maybe I just did something very dumb :-P

Thanks in advance for your help!

**Comment by furkanusta** [comment]
I've copy pasted your code and tried with Binary Archive Serializer and it worked without any change, maybe it depends on how you are trying to use?


```C++
#include <cereal/archives/binary.hpp>
int main() {
    cv::Mat data;
    {
        std::ofstream file("file.bin", std::ios::binary);
        cereal::BinaryOutputArchive ar(file);
        ar(data);
    }

    cv::Mat loaded_data;
    {
        std::ifstream file("file.bin", std::ios::binary);
        cereal::BinaryInputArchive ar(file);
        ar(loaded_data);
    }
}

```

**Comment by bperel** [comment]
Thanks for your response. Here is how I call the class : 
```c++
string descriptorsInput = "{}";
std::stringstream is(keyPointsInput);
Mat descriptors;
{
    cereal::JSONInputArchive ar(is);
    ar(descriptors);
}
```

Indeed, my code compiles if I replace the JSON archive with a Binary archive. How come?

**Comment by furkanusta** [comment]
When you say 
```C++
auto row_data = cereal::binary_data(mat.ptr(i), row_size);
ar & row_data;
```
You are trying to serialize binary_data into JSON Archive, which is not possible. That is also why it works when you use Binary Archive. 

If you **must** use JSON Archive there is a loadBinary function in it but I am not sure if it fits your needs.

**Comment by bperel** [comment]
So should I use `loadBinary` instead of `cereal::binary_data`? My needs in this case are simply to get a `Mat` object as a parsable string (I had imagined JSON but it can be XML as well) so that I can send it through a WebService. What is the best way?

This starts to look more like support than issue reporting, so thanks a lot for your help :-)

**Comment by furkanusta** [comment]
It looks like I've wrote the function name wrong it should be loadBinaryValue, here is the documentation: http://uscilab.github.io/cereal/assets/doxygen/classcereal_1_1JSONInputArchive.html#a618425a8a54490a0f1d16f464dd7717e

It seems like it should work. 

As for the best way, if all you do is convert cv::Mat -> pass to service -> convert back. I think BinaryArchive will be faster.

**Comment by patrikhuber** [comment]
Hi,
I wrote that blog post ;-)
Indeed you can only serialise to archives that support `cereal::binary_data` with that code, which excludes text archives.

What I've done a while ago is added a template specialisation to the file, you can find the latest version here: https://github.com/patrikhuber/eos/blob/2d531ff0eb0263015b51f3ac5f053cd8f51949af/include/eos/morphablemodel/io/mat_cerealisation.hpp
If you're serialising into a binary archive, it'll write binary data, and if you're serialising into a text archive (JSON or possibly XML), it'll save the values in plain text. Note that this is really only useful for small matrices, you don't really want to save big matrices in text format.

I haven't used `loadBinary`, that might be another option.

**Comment by bperel** [comment]
Thanks for your advices @furkanusta and @patrikhuber !
The only issues that I have left now are:
- I have no idea about how the code in @patrikhuber 's (de)serialization functions work (but they seem to do what I want)
- The serialized output is quite ugly to read by a human, but I guess that's the price to pay for data conciseness.

Thanks again!

**Comment by patrikhuber** [comment]
@bperel Glad I could help. If it's the template specialisations you're having trouble understanding, you could read [this documentation](http://uscilab.github.io/cereal/archive_specialization.html) as a starting point.

Yes, the serialised output is a bit ugly. I think there are ways to make it more pretty, #288 might be a good starting point for that, but I unfortunately didn't have time for that so far.

**Comment by bperel** [comment]
Thanks a lot @patrikhuber. The ticket that you linked to is definitely a good option to make the output more readable.

I'll close the issue since the behavior, according to you 2, is the correct one.
