### ISSUE TITLE
Cereal breaks with multiple definitions if you include a header with a registered type in different TUs

### ISSUE THREAD

**Issue by sithhell** [USCiLab/cereal#5]
Cereal breaks with multiple definitions if you include a header with a registered type in different TUs.
The problem is CEREAL_BIND_TO_ARCHIVES which leads to multiple definitions in the object files.
A testcase can be seen here: https://gist.github.com/sithhell/5984469
It also contains a patch and a possible solution (uncomment the lines in b.cpp and c.cpp after you applied the patch).

**Comment by chenghuige** [comment]
this might fix the problem 


#define CEREAL_BIND_TO_ARCHIVES(T)                   \
    namespace cereal {                               \
    namespace detail {                               \
    template<>                                       \
    struct init_binding<T> {                         \
        static bind_to_archives<T> const & b()        \
				{ \
				const static bind_to_archives<T> _b = ::cereal::detail::StaticObject<bind_to_archives<T> >::getInstance().bind(); \  
				return _b; \
				} \
        static void unused() { (void)b(); }            \
    };                                           \    
    }} /* end namespaces */

**Comment by chenghuige** [comment]
Below might fix this problem

#define CEREAL_BIND_TO_ARCHIVES(T)                   \
    namespace cereal {                               \
    namespace detail {                               \
    template<>                                       \
    struct init_binding<T> {                         \
        static bind_to_archives<T> const & b()        \
				{ \
				const static bind_to_archives<T> _b = ::cereal::detail::StaticObject<bind_to_archives<T> >::getInstance().bind(); \  
				return _b; \
				} \
        static void unused() { (void)b(); }            \
    };                                           \    
    }} /* end namespaces */
