### ISSUE TITLE
Polymorphic de/serialization of non-pointer objects

### ISSUE THREAD

**Issue by sandlerb** [USCiLab/cereal#510]
Hello,
I'm wondering if it is possible, and if so, what the work involved would be to implement polymorphic de/serialization of non-pointer objects. The desired functionality is that an object could be added into an archive via a reference and then deserialized into either an object of that type or a shared pointer to the base class of that type.  Could this be implemented as perhaps a new type or would it require a significant rewrite of cereal?

Thank you in advance!

**Comment by AzothAmmo** [comment]
The challenge with serializing references or pointers, regardless of whether they are polymorphic, is that it requires tracking the addresses of everything the serialization framework ever sees. I've gone into this in detail in past posts, but consider that your reference could be to another item you serialize - we need to make sure that we don't double save and that we properly load things in the correct order.

So this can be done (boost serialization does it) but it comes with drawbacks that we purposefully chose not to include with cereal. Implementing this would require significant work and could not be done with a simple type.

**Comment by sandlerb** [comment]
Thanks @AzothAmmo, I'll look into your previous posts.  Are those posts all in issues or PRs as well?

**Comment by AzothAmmo** [comment]
There's some discussion here: https://github.com/USCiLab/cereal/issues/33, likely on the mailing list or other places too.

**Comment by sandlerb** [comment]
Thanks again, much appreciated.
