### ISSUE TITLE
Polymorphic serialization fails in clang with -fvisibility-inlines-hidden

### ISSUE THREAD

**Issue by jcai1** [USCiLab/cereal#531]
I have encountered a strange issue where polymorphic serialization fails when using shared linking with clang 3.8.0. The following is a minimal working example:

File `FooBar.h`:

    #pragma once

    #include <cereal/archives/binary.hpp>
    #include <cereal/types/base_class.hpp>
    #include <cereal/types/polymorphic.hpp>

    class Foo {
     public:
      virtual ~Foo() = default;

      template <class Archive>
      void serialize(Archive& ar) {}
    };

    class Bar : public Foo {
     public:
      template <class Archive>
      void serialize(Archive& ar) {
        ar(cereal::base_class<Foo>(this));
      }
    };

    CEREAL_REGISTER_TYPE(Bar);

File `FooBar.cpp`:

    #include "FooBar.h"

File `main.cpp`:

    #include <fstream>
    #include <memory>

    #include "FooBar.h"

    int main() {
      std::shared_ptr<Foo> obj;
      obj = std::make_shared<Bar>();
      std::ofstream file("/tmp/foobar.bin", std::ios::binary);
      cereal::BinaryOutputArchive ar(file);
      ar(obj);
    }

Compile and run with:

    clang -O0 -std=c++11 FooBar.cpp -I./cereal/include -shared -o libfoobar.so -fPIC -fvisibility-inlines-hidden
    clang -O0 -std=c++11 main.cpp -I./cereal/include -lstdc++ -L. -lfoobar -ocereal_test
    LD_LIBRARY_PATH=. ./cereal_test

The following error is outputted:

    terminate called after throwing an instance of 'cereal::Exception'
      what():  Trying to save an unregistered polymorphic type (Bar).
    Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE.
    If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT.
    Aborted (core dumped)

Note that the issue still occurs if:
- `CEREAL_REGISTER_POLYMORPHIC_RELATION` is used
- and/or `CEREAL_FORCE_DYNAMIC_INIT` / `CEREAL_REGISTER_DYNAMIC_INIT` are used.

And the issue does not occur if:
- the flag `-fvisibility-inlines-hidden` is not specified
- or gcc 5.4.0 is used instead of clang.

**Comment by jcai1** [comment]
The issue goes away if in the file `include/cereal/details/static_object.hpp` the method `StaticObject::create()` is annotated with `__attribute__ ((visibility("default")))`.

**Comment by uentity** [comment]
@jcai1 switch to develop branch, it already has fix for that.
