### ISSUE TITLE
Visibility hidden and polymorphism

### ISSUE THREAD

**Issue by BotellaA** [USCiLab/cereal#541]
I am using Cereal (latest commit on the develop branch) and I am trying to add the visibility flag (using `set(CMAKE_CXX_VISIBILITY_PRESET hidden)`). I have a library and a test executable dynamically linked to the library. The test exports some custom polymorphic classes. Everything works without the visibility flag but with it I have this error:

```
Trying to save an unregistered polymorphic type (XXXX).
Make sure your type is registered with CEREAL_REGISTER_TYPE and that the archive you are using was included (and registered with CEREAL_REGISTER_ARCHIVE) prior to calling CEREAL_REGISTER_TYPE.
If your type is already registered and you still see this error, you may need to use CEREAL_REGISTER_DYNAMIC_INIT.
```

The register is correctly done because it was working without the flag and if I try to register once more in the test executable, I got a message saying that the class is already registered.
I do not need the CEREAL_REGISTER_DYNAMIC_INIT because I already have the same mecanism in my library.

The error is identical using VS17.

Can someone have an idea of a solution? (maybe @uentity) 
Thanks for your help

PS: I tried to isolate some code but I need to many files to reproduce the error.

**Comment by M2tM** [comment]
When closing issues can you address what the solution was?

**Comment by BotellaA** [comment]
I did not find any solution, I do not use Cereal anymore
