### ISSUE TITLE
It is impossible to specialize std::pair and std::tuple with save/load function: only serialize() is defined in headers

### ISSUE THREAD

**Issue by Epholys** [USCiLab/cereal#547]
As I said in the title, only serialize() is defined for `std::pair` and `std::tuple`. For example, in `utility.hpp`:
```c++
namespace cereal
{
  //! Serializing for std::pair
  template <class Archive, class T1, class T2> inline
  void CEREAL_SERIALIZE_FUNCTION_NAME( Archive & ar, std::pair<T1, T2> & pair )
  {
    ar( CEREAL_NVP_("first",  pair.first),
        CEREAL_NVP_("second", pair.second) );
  }
} // namespace cereal
```

As such, it is impossible to specialize with `load()` or `save()` function.
I suppose this is a deliberate choice, but I think it would be nice to add a less cryptic error message or to have some documentation for this case.

Otherwise, this is an awesome library, keep up the good work!

EDIT:
One workaround is simply to not include the headers and to simply define the save/load functions directly.

**Comment by AzothAmmo** [comment]
Your workaround is a valid solution - another idea you could try (I haven't taken the time to test this myself) is using the `specialization` construct to inform cereal that you wish to use a specific serialization function. Take a look at the documentation [here](http://uscilab.github.io/cereal/serialization_functions.html#inheritance) and the doxygen [here](http://uscilab.github.io/cereal/assets/doxygen/structcereal_1_1specialize.html) and try that out - it may solve the problem as well.

**Comment by Epholys** [comment]
Yes, that works, thanks for the tip! Here's a minimal example:

```c++
#include <sstream>
#include <iostream>
#include <utility>
#include "cereal/cereal.hpp"
#include "cereal/archives/json.hpp"
#include "cereal/types/utility.hpp"

namespace cereal
{
    template<class Archive, class F, class S>
    void save(Archive& ar, const std::pair<F, S>& pair)
    {
        ar(pair.first, pair.second);
    }

    template<class Archive, class F, class S>
    void load(Archive& ar, std::pair<F, S>& pair)
    {
        ar(pair.first, pair.second);
    }

    template <class Archive, class F, class S> 
    struct specialize<Archive, std::pair<F, S>, cereal::specialization::non_member_load_save> {};
}

int main()
{
    std::pair<int, double> pair {42, 3.141};
    std::cout << "before saving pair: " << pair.first << " ; " << pair.second << std::endl;

    std::stringstream ss;

    {
        cereal::JSONOutputArchive oar(ss);
        oar(pair);
    }

    std::cout << "serialized pair :\n" <<ss.str() << std::endl;

    {
        pair = {0, 0};
        std::cout << "resetted pair: " << pair.first << " ; " << pair.second << std::endl;

        cereal::JSONInputArchive iar(ss);
        iar(pair);
    }

    std::cout << "after loaded pair: " << pair.first << " ; " << pair.second << std::endl;

    return 0;
}
```

My main issue is that it's difficult to know what the problem is when you're a beginner with cereal. I'm grateful for the `static_assert` and I know templated code are not really ideal for compile-time error message, so it's already great, but I feel that more clues could not do harm. It could save some time for other people like me :). Anyway, that's just my two cents. Thanks for this project and the answer!

**Comment by tankorsmash** [comment]
Just jumping in to say that this was exactly my problem too. I didn't understand why my pair overload was throwing this error. Now that I understand why, it makes sense but it was not clear to me either.

Maybe a note could be added to utility.hpp's pair overload or something to tell you about this, since I blindly assumed that a builtin cereal header wouldn't cause conflicts with my own code. 

It's my fault for not understanding but I'd love to have some more explicit docs for this specific case.
