### ISSUE TITLE
fallthrough error

### ISSUE THREAD

**Issue by Raviteja1996** [USCiLab/cereal#550]
I am trying to install cereal. I cloned the GitHub url and made a build directory and did 'cmake' until then it was fine. When I tried to do 'make' it is showing,
cereal/./include/cereal/archives/json.hpp:211:33: error: this statement may fall through [-Werror=implicit-fallthrough=] 

I am also attaching the image.

![screenshot 43](https://user-images.githubusercontent.com/17984785/53715678-95b25200-3e78-11e9-8870-62cf05a0c79f.png)

**Comment by furkanusta** [comment]
This warning was suppressed in the develop branch (see #432), can you try that?
Or you can use -DWITH_WERROR=OFF with CMake

**Comment by Raviteja1996** [comment]
Thanks a lot …..its solved !!
