### ISSUE TITLE
Portable Binary Floating Point

### ISSUE THREAD

**Issue by alandefreitas** [USCiLab/cereal#551]
Hi,

Is binary-portable also portable for floats and doubles?
* Could these serialized real numbers fail on a computer that uses different endianness?
* Could these serialized real numbers fail on a computer that does not use IEEE 754?

If it's not portable, how complicated would it be to make it work?

Thank you,

**Comment by AzothAmmo** [comment]
We explicitly take care of endianness, but do not explicitly handle conversion to non-compliant IEEE 754 implementations. If you look at the source code, we require that the floating point implementation is IEEE 754 compliant - this is something that could indeed be replaced by actual conversion, and is something that a third party library can already provide, and potentially could be integrated directly.

**Comment by alandefreitas** [comment]
That's what I thought because IEEE 754 is just too common. So IEEE 754 is an expectation rather than something the portable library deals with. 

I was thinking of using a library such as https://github.com/LiraNuna/soft-ieee754 or https://github.com/kkimdev/ieee754-types to explicitly make this conversion explicit but I wanted to make sure I really needed to do that. 

Thanks,
