### ISSUE TITLE
cmakelists with boost not found

### ISSUE THREAD

**Issue by xiefangping** [USCiLab/cereal#552]
In your cmakelists, even if boost not found, still unittest and sandbox will be built, which cause a problem.

```
# Boost serialization for performance sandbox
find_package(Boost COMPONENTS serialization)

if(Boost_FOUND)
  include_directories(SYSTEM ${Boost_INCLUDE_DIRS})
endif(Boost_FOUND)
  
enable_testing()
add_subdirectory(unittests)

add_subdirectory(sandbox)
```

**Comment by AzothAmmo** [comment]
The unit tests do not use boost, and the portions of sandbox that require boost are already guarded: https://github.com/USCiLab/cereal/blob/develop/sandbox/CMakeLists.txt

**Comment by AzothAmmo** [comment]
This should be fixed now in the sense that the boost unit test (variadic) is now behind `Boost_FOUND`. See #568
