### ISSUE TITLE
can Cereal improve save API by support "abort it" in the middle? 

### ISSUE THREAD

**Issue by hesong-1976** [USCiLab/cereal#553]
for example, our STL container can be very large and can consume a lot time, if during save, it has an new incoming change, and we want to abort the current save in the middle

**Comment by M2tM** [comment]
Would throwing be an option?

**Comment by hesong-1976** [comment]
hi, Mt2M:
    throwing means what? throw the file which is seriliazing now(e.g. delete it and quit save API)?  if so, yes.

**Comment by M2tM** [comment]
In a serialize function try:

throw std::runtime_exception(“cancel save”);

Wrap the root level archive call in a try/catch.

**Comment by hesong-1976** [comment]
thanks M2tM, it can work!
