### ISSUE TITLE
Is Cereal still maintained?

### ISSUE THREAD

**Issue by sssilver** [USCiLab/cereal#559]
We're contemplating using Cereal in our project, but concerned about the fact that the latest commit on master is as far back as February of 2017.

This begs the question -- is this project still actively maintained, or has it been abandoned?

**Comment by AzothAmmo** [comment]
Master has not been updated in a while, develop has some updates that are far more recent. It is my intention to make develop the default branch on github soon to alleviate this concern.

I'm currently not actively working on new features for cereal but do intend to work my way through any bugs or outstanding problems. That does not preclude the chance of merging pull requests with new features, I just don't currently have the time to develop them myself, though that could always change.

**Comment by AzothAmmo** [comment]
I've guilted myself into doing development on cereal again (a light amount to start).

**Comment by M2tM** [comment]
Welcome back, sir!
