### ISSUE TITLE
Has this project died? Take some pull requests and apply them please!

### ISSUE THREAD

**Issue by iplayfast** [USCiLab/cereal#585]
Fall through issue fails build now on modern compilers. Either change case to duplicate code, (which the compiler will optimize out), or use method described here to make it not a warning https://stackoverflow.com/questions/45129741/gcc-7-wimplicit-fallthrough-warnings-and-portable-way-to-clear-them

**Comment by AzothAmmo** [comment]
See #579 which will resolve many, but not all, compilation warnings with newer compilers.
