### ISSUE TITLE
Does PortableBinary archive support std::string?

### ISSUE THREAD

**Issue by p-ranav** [USCiLab/cereal#637]
I'm having trouble serializing a struct like below with `PortableBinaryOutputArchive`.

```cpp
struct Album {
  std::string name;
  std::string artist;
  int year;
  std::string genre;
  std::vector<std::string> tracks;

  template <class Archive>
  void serialize( Archive & ar ) {
    ar(name, artist, year, genre, tracks);
  }
};
```

**Comment by RallyTronics** [comment]
What trouble are you having?  I am using `PortableBinaryOutputArchive` with `std::string` right now.

**Comment by p-ranav** [comment]
> What trouble are you having?

I didn't read the documentation correctly. Once I included `<cereal/types/string.hpp>` and `<cereal/types/vector.hpp>` everything worked. 

Closing this.
