### ISSUE TITLE
braces not closed with JSONOutputArchive and stringstream

### ISSUE THREAD

**Issue by KoyamaSohei** [USCiLab/cereal#670]
hello, I wanted to use cereal library to serialize json and dump to std::string.

so wrote code like below.
```
#include <cereal/cereal.hpp>
#include <cereal/archives/json.hpp>
#include <string>
#include <sstream>

int main() {
  std::string key = "foo";
  std::string value = "bar";
  std::stringstream ss;
  cereal::JSONOutputArchive archive(ss);
  archive(CEREAL_NVP(key), CEREAL_NVP(value));
  std::string dst = ss.str();
  std::cout << dst << std::endl;
}
```

However, this output is invalid
```
{
    "key": "foo",
    "value": "bar"
```

Playground https://wandbox.org/permlink/40FrqdtvJ7dIIsm1

Another case, use std::cout 

```
#include <cereal/cereal.hpp>
#include <cereal/archives/json.hpp>
#include <string>
#include <sstream>


int main() {
  std::string key = "foo";
  std::string value = "bar";
  cereal::JSONOutputArchive archive(std::cout);
  archive(CEREAL_NVP(key), CEREAL_NVP(value));
}
```

this output is valid.
```
{
    "key": "foo",
    "value": "bar"
}
```

Playground: https://wandbox.org/permlink/vA1Wm5Y2wxdmarcU

please let me know if you have any idea to solve this error, thanks.

cereal version: 1.3.0

**Comment by erichkeane** [comment]
Closing braces are appended in the archives destructor.  Since the archive object is still alive in your example, that hasn't happened yet.  Change it to:

    {
      cereal::JSONOutputArchive archive(ss);
      archive(CEREAL_NVP(key), CEREAL_NVP(value));
    }

**Comment by erichkeane** [comment]
See the 'Important' part here on the 'quick start' documentation under Serialize Your Data:http://uscilab.github.io/cereal/quickstart.html

**Comment by KoyamaSohei** [comment]
Thanks for taking your time!
and sorry that I didn't read the documentation (also, I didn't understand RAll).
