### ISSUE TITLE
Cant deserialize with custom vector class

### ISSUE THREAD

**Issue by jep-crain** [USCiLab/cereal#673]
New to CEREAL.  

std::containers seem to work OK - but what about customized containers.

I work in the numerical fields and have to interface with Fortran code often. To do so, I have a custom version of std::vector<T> called TVector<T>.  T

Here is some code that serializes and deserializes a cubic spline.  It does serialize but errors are generated for deserializing:

#include <iostream>
#include <fstream>
#include <vector>
#include <cereal/cereal.hpp>
#include <cereal/archives/xml.hpp>
#include <cereal/archives/json.hpp>
#include <cereal/types/array.hpp>
#include <cereal/types/vector.hpp>
#include <cereal/types/string.hpp>
#include <cereal/types/map.hpp>
#include <cereal/types/unordered_map.hpp>
#include <cereal/types/memory.hpp>       

template<typename T>
class TVector : public std::vector<T>
{
   public:
   T& operator[](int n)
   {
      return std::vector<T>::operator[](n - 1);
   }
};

template<typename T>
struct SplineCubic
{
   size_t num_points = 0;
   TVector<T> x;
   TVector<T> y;
     

   SplineCubic()  {}       // Needed for serialization/deserialization

   SplineCubic(const std::vector<T>& xV, const std::vector<T>& yV)
   {
      this->num_points = xV.size();
      this->x.resize(this->num_points);
      this->y.resize(this->num_points);

      for (int n = 0; n < this->num_points; n++)
      {
         this->x[n + 1] = xV[n];
         this->y[n + 1] = yV[n];
      }
   }

   template <class Archive>
   void serialize(Archive& archive)
   {
      archive
      (
         CEREAL_NVP(num_points),
         CEREAL_NVP(x),
         CEREAL_NVP(y)
      );
   }
};

int main()
{
   std::vector<double> xV = { -1.0, -0.5, 0.0, +0.5, +1.0 };
   std::vector<double> yV = { +1.0, 0.25, 0.0, 0.25, +1.0 };

   SplineCubic<double> loadingSpline(xV, yV);

   {  // Serialize
      std::ofstream outF("spline.json");
      {
         cereal::JSONOutputArchive outputArchive(outF);
         cereal::JSONOutputArchive archive(outF);
         loadingSpline.serialize(archive);
      }
      outF.close();     
   }

   {  // Deserialize
      std::ifstream f("spline.json");
      {
         cereal::JSONInputArchive iarchive(f);
         SplineCubic<double> loadingSpline;
         iarchive(loadingSpline);
      }
      f.close();
   }
   std::cout << "Finished!" << std::endl;
}

Any suggestions?

**Comment by erichkeane** [comment]
I can't really see your error message, and your example doesn't compile since all the template params seem to have disappeared.

**Comment by erichkeane** [comment]
I was able to get it compiling enough to repro this, the problem has nothing to do with your vector type, you can confirm this by removing the vector type entirely.
The problem is with how you are serializing:

    loadingSpline.serialize(archive);

Should be:

     archive(loadingSpline);

You are essentially skipping the outer 'header' and serializing ONLY the object's internals, but then trying to deserialize expecting the outer 'header'.  You can also fix this by changing:

    iarchive(loadingSpline);

To
    
    loadingSpline(iarchive);

If you really prefer the json layout that gets you.

**Comment by jep-crain** [comment]
Your correction works!

I have been playing with Cereal and it is working really good.

I will continue exploring this serialization library.

Thank you for your quick response and help. 

It is very much appreciated!
