### ISSUE TITLE
Website does not exist?

### ISSUE THREAD

**Issue by haohaibo** [USCiLab/cereal#691]
This website https://uscilab.github.com/cereal doesn't exit.

**Comment by haohaibo** [comment]
Find one main page using google search https://uscilab.github.io/cereal/. https://github.com/USCiLab/cereal/blob/master/README.md readme file may need an update.

**Comment by erichkeane** [comment]
Based on the 404 page, i found the same github.io/cereal page, this is apparently a change that github made.

**Comment by AzothAmmo** [comment]
Fixed
