### ISSUE TITLE
JSONOutputArchive Loses a closing brace

### ISSUE THREAD

**Issue by FlyingRhenquest** [USCiLab/cereal#697]
Howdy! I'm trying to use JSONOutputArchive to serialize a simple 4 element struct. If my code goes:
 
 ```
     std::stringstream buffer;
      cereal::JSONOutputArchive arch(buffer);
      arch(resp);
      std::cout << "Sending " << buffer.str() << std::endl;

```

Then the JSON will be serialized with a missing closing brace. However if I do this:

```
      std::stringstream buffer;
      {
	cereal::JSONOutputArchive arch(buffer);
	arch(resp);
      }
      std::cout << "Sending " << buffer.str() << std::endl;
```

Then it will be serialized correctly. In the second case the only difference I can see is I'm forcing the archive destructor to run prior to printing my buffer, so I suspect a flush isn't happening until then.

**Comment by erichkeane** [comment]
See the 'important' tag under Archive Basics here: https://uscilab.github.io/cereal/serialization_archives.html
Basically, the archive doesn't know you are done archiving until it hits its destructor, so it doesn't have the ability to put the closing brace on until you destruct the type.  It is part of the design of the archive types.

**Comment by FlyingRhenquest** [comment]
Got it, thanks! I missed that bit!
