### ISSUE TITLE
New release?

### ISSUE THREAD

**Issue by marehr** [USCiLab/cereal#712]
Hi!

Is it possible for you to do a new release?

Thank you!

**Comment by patlecat** [comment]
The project seems dormant if not dead. I wonder what the strategy is here?

**Comment by AzothAmmo** [comment]
I'll try to do a bit of maintenance and a release this weekend.

**Comment by AzothAmmo** [comment]
Everything is nearly ready to go, I have to fix a few things with the CI pipelines and then I'll be happy to release.

**Comment by bjadamson** [comment]
I just went to update my dependencies and saw this when I was looking into updating my cereal dependency. Thanks for releasing a new version!

**Comment by akesandgren** [comment]
Yes, please produce a new release.

**Comment by eseiler** [comment]
> [...] and always welcome assistance.

Do you have an overview of what does not work and needs fixing (e.g. problems with the code itself, or problems relating to CI)? People might want to contribute, but it's hard to figure out what needs to be done when one is not familiar with the project.

**Comment by AzothAmmo** [comment]
There are three blocking issues for a release right now, that I've worked on a little but have not completed:

1. Doctest needs to be upgraded to a recent release, but also needs to be patched (ideally upstream) to support the older compilers we still officially support (MSVC 2013). My attempt at this is here: https://github.com/AzothAmmo/doctest/tree/noreturn_macro, though I haven't gotten all of their tests to pass yet.
2. The AppVeyor based CI (https://ci.appveyor.com/project/AzothAmmo/cereal/branch/master) is failing on later releases of MSVC and should also be amended to include the latest MSVC (v17).
3. Travis CI, which was previously used for CI, is no longer free and does not run on recent commits. We need to migrate to github actions, which could potentially also run our Windows testing as well.

**Comment by AzothAmmo** [comment]
Update on the above: thanks to PR #727 by @isuruf, I found some motivation and have been playing around with both doctest and appveyor fixes, and think we're pretty close to being able to get a release out. 

Will still need to get OSX CI working with actions, and there are probably some tweaks to be made in doctest to make MSVC 2013 happy.

**Comment by AzothAmmo** [comment]
All the blockers have been resolved, will do some tidy-up and get the release out soon.

**Comment by AzothAmmo** [comment]
Actually have every test passing now, bumped a few minor things to a future release and have everything in for the current one, just awaiting any documentation updates, should actually be out very soon.

**Comment by AzothAmmo** [comment]
1.3.1 released
