### ISSUE TITLE
BSD License issue

### ISSUE THREAD

**Issue by ltoenning** [USCiLab/cereal#729]
In our project we must strictly stick to the 3-Clause BSD license and want to use cereal.

I checked the LICENSE file and it seems you made small changes to license text (maybe that is also why Github doesn't detect the license).

1. In the third clause you're stating:

> Neither the name **of cereal** nor the  names of its contributors may be used to endorse or promote products  derived from this software without specific prior written permission.

but the original says:
> Neither the name **of the copyright holder** nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission. 

2. Further you specify: 

> [...] IN NO EVENT SHALL **RANDOLPH VOORHIES OR SHANE** GRANT BE LIABLE FOR ANY
DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES [...]

where the original says:

> [...] IN NO EVENT SHALL THE **COPYRIGHT HOLDER OR CONTRIBUTORS** BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES [...]

so theoretically nearly all contributors could be liable for damages.

<br/><br/> 

Are these changes compared to 3-clause BSD intended? If not, could you adjust the license?

I know its a very minor thing but we really would like to use cereal but need to stick to the license.

**Comment by ptrdtznr** [comment]
I know this is a critical and an important topic (not only for us, probably for everyone who uses cereal already and who wants to use it in the future) - are there any updates/news regarding the license topics? @AzothAmmo @randvoorhies

**Comment by AzothAmmo** [comment]
Will look into this around the end of the month.
________________________________
