### ISSUE TITLE
How to de/serialize to/from std::vector<char> 

### ISSUE THREAD

**Issue by Dreamykass** [USCiLab/cereal#730]
(or to/from std::vector<std::byte>)

```cpp
    {
      std::stringstream os(std::ios::binary | std::ios::out | std::ios::in);

      auto t1 = TrainingPointsTemp{}; // contains a vector of integers
      auto t2 = TrainingPointsTemp{};

      cereal::BinaryOutputArchive archive_out(os);
      archive_out(t1);

      std::cout << "" << os.str() << "\n"; // ???

      cereal::BinaryInputArchive archive_in(os);
      archive_in(t2);

      assert(t1.acid.size() == t2.acid.size());
      assert(t1.oxygenation.size() == t2.oxygenation.size());
      assert(t1.lockin.size() == t2.lockin.size());
    }
```

Using `std::stringstream os(...);` and then `os.str()` to get the bytes doesn't feel right... It's a **string**stream, but I just want bytes.
My worry would be that it would mess up if there's null-chars? The data in the struct can definitely be zeroes.

I'd like to store the struct as a blob in a database.

**Comment by AzothAmmo** [comment]
cereal will write the data verbatim to the stream - it's how we are able to load it back after serializing it. The bytes in the stringstream will be what you expect them to be. You can look at the binary archive source to see how it is done internally.

An archive that serializes directly to a buffer or dynamically allocated buffer (like a vector) would be pretty cool, but we don't have that currently.
