### ISSUE TITLE
New Release

### ISSUE THREAD

**Issue by andrewkcorcoran** [USCiLab/cereal#737]
It's been 2 years since the last release, I'm assuming there's been a decent amount of bug fixes etc. since then. What's the plan going forward, are there going to be new releases or is cereal master officially considered 'live at head' (if so can the README.md be updated to reflect this change)?

**Comment by AzothAmmo** [comment]
see #712 - regarding master being "live", there are no official guarantees about the stability of master, though in practice it will almost always be passing CI tests. Those who need an official release can use whatever the latest release is, and those with more tolerance for risk can use master.
