### ISSUE TITLE
`CEREAL_VERSION_PATCH` not updated in v1.3.1 release

### ISSUE THREAD

**Issue by lkeegan** [USCiLab/cereal#748]
Many thanks for the latest v1.3.1 release!

Unfortunately `CEREAL_VERSION_PATCH` was not incremented: https://github.com/USCiLab/cereal/blob/1de8fe89471d69ea392ea260ce74e079d5f4b415/include/cereal/version.hpp#L45

This causes e.g. Symengine to not compile with v1.3.1 of cereal (https://github.com/symengine/symengine/issues/1886), as it checks the cereal version number to take into account this change in cereal: https://github.com/USCiLab/cereal/commit/f27c12d491955c94583512603bf32c4568f20929

**Comment by isuruf** [comment]
@AzothAmmo, anything we can do here?

**Comment by AzothAmmo** [comment]
I can get out a patch for this and tag it as 1.3.2 this week.
________________________________

**Comment by isuruf** [comment]
Thanks @AzothAmmo

**Comment by lkeegan** [comment]
Thanks!
