### ISSUE TITLE
Templatized Subclass Question

### ISSUE THREAD

**Issue by kklouzal** [USCiLab/cereal#93]
Is it possible to serialize a vector of shared_ptr to a templatized subclass as outlined in this question here: http://stackoverflow.com/questions/23035263/serialize-templatized-sub-class

A comment was left saying this is not possible, I want to confirm.

Thank you all very much for your time.

**Comment by acmol** [comment]
I have the same problem, and I think I found a solution.
I have a BaseClass and a template SubClass, it seems like this:

`
template<typename T>
class SubClass : public BaseClass {
//  some details here
};
`

I should provide a template method to my user, looks like this:

`
template<typename T>
T& getData(Container& container) {
    CEREAL_REGISTER_TYPE(SubClass<T>);   // won't compile
   // do something 
}
`

I want  register SubClass<T> in the method, but the type T is undetermined when I wrote my code. It's determined when user calls my function. I tried to call the macro CEREAL_REGISTER_TYPE in the template method, but I got some errors. 

Then I started to have a look at the implement of CEREAL_REGISTER_TYPE, and got a solution.
`
// TODO: multiple compiler support
// We make use of gcc specific macro: __PRETTY_FUNCTION__, it only print function
// name. If T is int, then __PRETTY_FUNCTION__ returns something likes
// "void pretty_type_name<T>() [with T = int]". We extract the real type name
// 'int' and return.
template<typename T>
const std::string pretty_type_name() {
    const char* begin_ptr = __PRETTY_FUNCTION__;
    // skip after typename `T'
    bool found = false;
    bool preceeding_space = false;
    while (!found && '\0' != *begin_ptr) {
        switch (*begin_ptr) {
        case ' ':
            preceeding_space = true;
            break;
        case 'T':
            if (preceeding_space && (' ' == *(begin_ptr + 1))) {
                found = true;
            }
            // fall through
        default:
            preceeding_space = false;
        }
        ++begin_ptr;  // skip `T' itself if found
    }
    // skip whitespace after typename `T'
    while (' ' == *begin_ptr) {
        ++begin_ptr;
    }
    // skip `=' sign
    if ('=' == *begin_ptr) {
        ++begin_ptr;
    }
    // skip whitespace after `='
    while (' ' == *begin_ptr) {
        ++begin_ptr;
    }
    const char* end_ptr = begin_ptr;
    while (']' != *end_ptr && ';' != *end_ptr && '\0' != *end_ptr) {
        ++end_ptr;
    }
    return std::string(begin_ptr, end_ptr);
}

template<typename T>
const std::string unique_type_name() {
    // Usually pretty_type_name will return unique name for each type.
    // However, if two cc files all define types with same name inside
    // unnamed namespace, they will conflict each other.
    std::string type = pretty_type_name<T>();
    static const char unnamed_prefix[] = "_anoymous_";
    size_t start_index = type.find(unnamed_prefix);
    while (start_index != std::string::npos) {
        type = type.replace(start_index,
                            sizeof(unnamed_prefix) - 1,   // skip remain tailing "\0"
                            __BASE_FILE__);         // replace with filename
        start_index = type.find(unnamed_prefix);
    }
    return type;
}

} // namespace detail
} // namespace cereal

#define CEREAL_REGISTER_TEMPLATE(TEMPLATE_NAME) \
namespace cereal { \
namespace detail { \
\
template <typename T> \
struct binding_name<TEMPLATE_NAME<T>> \
{ \
    static char const * name() { \
        static std::string ret = unique_type_name<TEMPLATE_NAME<T>>(); \
        return ret.c_str(); \
    } \
}; \
\
template<typename T> \
struct init_binding<TEMPLATE_NAME<T>> { \
    static bind_to_archives<TEMPLATE_NAME<T>> const & b; \
    static void unused() { (void)b; } \
}; \
template<typename T> \
bind_to_archives<TEMPLATE_NAME<T>> const & init_binding<TEMPLATE_NAME<T>>::b = \
    ::cereal::detail::StaticObject< \
        bind_to_archives<TEMPLATE_NAME<T>> \
    >::getInstance().bind(); \
    \
} \
}

#define CEREAL_REGISTER_TEMPLATE_CLASS_INSTANTIATION(T) do { \
    if (0) { \
        cereal::detail::init_binding<T>::unused(); \
    } \
} while (0)

`

Then, I can just use CEREAL_REGISTER_TEMPLATE to register a template at global scope, and then use CEREAL_REGISTER_TEMPLATE_CLASS_INSTANTIATION to register the instantiation in any method scope. The code may looks like this:

`
CEREAL_REGISTER_TEMPLATE(SubClass)

template<typename T>
T& getData(Container& container) {
    CEREAL_REGISTER_TEMPLATE_CLASS_INSTANTIATION(SubClass<T>);   
    // will work, even if it's not actually called.
    // As long as this code is shown in the compile unit, it will work.
}

`

Hope this will help.

If it's usefull, I think maybe I can start a PullRequest.
